### ISSUE TITLE
Spectral blade: Flameblades mechanics

### ISSUE THREAD

**Issue by jimitndiaye** [d07RiV/d3planner#1]
Referring to this line: https://github.com/d07RiV/d3planner/blob/master/simulator/wizard.js#L83
it seems that the number of stacks granted is being limited to a third of the enemies hit. That doesn't sound right, unless there is something I'm missing.

**Comment by d07RiV** [comment]
This has been discussed on my previous issue tracker, it is the correct behavior as it hits each target 3 times, so the number of stacks should be the number of hits divided by 3.
