### ISSUE TITLE
Profiles: Not signed in when signed in

### ISSUE THREAD

**Issue by DVDMaster68** [d07RiV/d3planner#100]
I signed in to my d3planner account and created several profiles.
Now when I sign in, the my profiles section is empty. Under my profiles it says "not signed in".
However in the upper right it says "Welcome, DVDMaster68".

If I choose load and search for a profile by name ("WD LON Locust/Garg/Sacrifice"), I can find it.

**Comment by d07RiV** [comment]
Is it still happening? I messed up when changing the way profiles work (i.e. 'private' checkbox was replaced by 'public' box), but I think I already fixed that.
