### ISSUE TITLE
Change all stats to minimum

### ISSUE THREAD

**Issue by amalys11** [d07RiV/d3planner#101]
Under the global equipment modification section, could a "Change all stats to minimum" option be added to compliment the "Change all stats to maximum" option?

When planning builds, I'd like to see what my numbers would be like assuming the worst possible rolls on the gear. Having this option on the page would allow users to easily flip between the two in order to evaluate the overall range of the build.

**Comment by d07RiV** [comment]
Uh I think a slider would be more appropriate, from 0% to 100% stats.

**Comment by amalys11** [comment]
A slider would definitely be more useful overall, though I understand the concern of overloading the UI. Part of the reason for the suggestion I had was due to it's simplicity, since it's really just a clone of an existing element, albeit with an inverse function.
