### ISSUE TITLE
Archon stacks

### ISSUE THREAD

**Issue by slorange** [d07RiV/d3planner#103]
There are 2 bonuses from archon.
The 150%armor/res & 30% dmg buff from being in archon,
and the 6%dmg (+1%armor/res/atkspeed if 4p vyr) per archon stack.
With swami helm you can have the stacks outside of archon.
Please have the option to include swami stacks in stats without including stats from being in archon.

**Comment by d07RiV** [comment]
If you have the "Active" box on Archon unchecked, the Swami box will let you choose stacks.

**Comment by d07RiV** [comment]
I just found out that Swami stacks are a separate multiplier from the regular Archon stacks, so the Swami slider is now always available, and the simulator has been adjusted to use the same logic.
