### ISSUE TITLE
Invoker's Thorns 2pc

### ISSUE THREAD

**Issue by dominiklohmann** [d07RiV/d3planner#104]
Example profile: http://www.d3planner.com/394492842 

The simulation only lists an average 11.23 Invoker's (2) stacks, which doesn't make any sense considering it should be way more than that from getting hit alone.

**Comment by d07RiV** [comment]
Why?

600 hits/minute is 10 hits/second, with 33% block it gives 6.6 stacks every 2 seconds. Add 120/24=5 stacks from Punish and you get the same result.
