### ISSUE TITLE
/Kadala Enhancements

### ISSUE THREAD

**Issue by emartinezgh** [d07RiV/d3planner#108]
Recently found out the /kadala url. Awesome resource.

There are two possible features that would make this even more awesome. 

#1 is if it could display the drop rate (1.57%) and/or odds (1 in 256) of each item in reference to kadala and in reference to the rare to legendary recipe (1 in 8 mighty swords is a solemn vow but 1 in 1000's kadala 1h words are a solemn vow).

#2 would be to have a check box if you want to get average values adjusted for the 1/10 odds of getting ancient items.

**Comment by d07RiV** [comment]
#1 - Aren't the shard/breath requirements enough to see what the droprate is like?

#2 - I think multiplying by 10 is easy enough.

**Comment by emartinezgh** [comment]
#1 Yes. It is all there already in a compact form. Would be nice to have the odds up front but I understand why people would rather just see average resources instead of number of attempts on average.

#2 As easy enough as it is I had a clan mate that thought the averages shown were for ancients and had no clue about the 1 in 10 chance for a legendary to be ancient. 

Both suggestions are of course not necessary at all and just nice things to have except if it'll just increase clutter. It is redundant information.

**Comment by d07RiV** [comment]
Actually I guess I'll consider those next time I improve this page.
