### ISSUE TITLE
Bane of the Powerful

### ISSUE THREAD

**Issue by rockon8729** [d07RiV/d3planner#110]
Bane of the Powerful's secondary 15% reduced damage from Elites does not seem to calculate when I check the box "Elite"

**Comment by d07RiV** [comment]
Where do you expect it to appear? It always appears under "Elite Damage Reduction" in the stats panel, and is included in your toughness with some weight, similar to how it shows in-game. The checkbox only affects the skill damage values in the Skills/Effects tab.

**Comment by rockon8729** [comment]
Hey d07RiV, Nevermind, I just went back and checked again and the 15% Elite DR is being calculated into the Toughness.  May have been a browser issue yesterday.

Thanks for looking into it!

**Comment by rockon8729** [comment]
Actually, I think I expected that when I selected Elite my Toughness would go up due to wearing the BoP gem and now I realize the 15% is added when I put on the gem in the calc.  If that checkbox is only for damage then that makes sense.
