### ISSUE TITLE
Wave of Force (Arcane Attunement) works for all of Archon (?)

### ISSUE THREAD

**Issue by dominiklohmann** [d07RiV/d3planner#113]
~~Title. This includes every Archon skill for the whole duration of Archon and also Chantodo's Resolve procs as long as the selected Archon rune is of arcane element.~~

Further testing below.

**Comment by d07RiV** [comment]
Is it also the case with cold black hole? Everyone seems to be using cold element with Vyr's.

**Comment by dominiklohmann** [comment]
The Arcane Attunment thing is from Alkaizers stream, he was running it in speed 95s. Can't imagine it to be bullshit if he runs it for over 10 hours straight. Because it's Alkaizer and he's known to be an elaborate troll I'll go confirm it in a bit. Arcane Attunement is a buff that you have until you cast any damaging Arcane Spell, and it persists even through death.

Cold black hole just adds to your cold damage on your character sheet, and can also change your Archon element temporarily. This was used in Season 4 as an alternative to Flame Blades and actually cleared a GR 82 in China (as opposed to the GR 84 with Flame Blades).

**Comment by dominiklohmann** [comment]
Just tested it in the game.

- Wave of Force - Arcane Attunement  
Consumed by any arcane Archon form. has no effect aside from increasing the damage of the first attack. Does not increase damage of Combustion (with Vyr's 2pc).
- Arcane Orb - Spark  
Like Arcane Attunement, but s/arcane/lightning.
- Black Hole - Absolute Zero  
Adds to your +% cold damage and shows on your character sheet. When used with Vyr's and/or Chantodo's, can change your active element dynamically (when your highest element changes to another element).
- Spectral Blades - Flame Blades  
Much like Absolute Zero, except s/cold/fire.

This pretty much confirms that Alkaizer was playing bullshit on stream for a whole day. Wonder if he knew.

**Comment by d07RiV** [comment]
Oh right I forgot the difference.

You're saying it is consumed by Archon, but still boosts the first attack even if it comes with a delay?

**Comment by dominiklohmann** [comment]
You can't see the buff while Archon is enabled, but you don't have it anymore after you used Archon, even when not doing any attacks in Archon form.
