### ISSUE TITLE
Caldessan's Despair Not Importing

### ISSUE THREAD

**Issue by billgunkel** [d07RiV/d3planner#115]
This does not seem to be a new issue, but I could not find a bug report after searching.  Is it no longer possible to import this buff on items, or is too problematic to import these item buffs?

**Comment by d07RiV** [comment]
It was never possible, as Battle.net API does not provide this information (yet). It also doesn't provide paragon levels, and still reports incorrect damage rolls for ancient offhand items. Still waiting for Blizzard to fix/improve it.

**Comment by billgunkel** [comment]
Thanks for the update, and for at least allowing us to enchant all items at a specified level.
