### ISSUE TITLE
Would like a tutorial for this please!

### ISSUE THREAD

**Issue by aeclasik** [d07RiV/d3planner#116]
I know it's not related to d3p but you have a solution and I am in need of it.
<3
http://turbohud.freeforums.net/post/25425/thread

http://i.imgur.com/mnGgbJf.png

**Comment by dominiklohmann** [comment]
WTB open sourced thud...

**Comment by d07RiV** [comment]
Instructions here: http://pastebin.com/raw/Kbsc9Wyj

**Comment by aeclasik** [comment]
OMG YES! TYTY

**Comment by d07RiV** [comment]
Guess this is no longer needed since a new version was released.
