### ISSUE TITLE
Archon Slow Time Not Listed in Buff Stacks Skills List

### ISSUE THREAD

**Issue by Manson1716** [d07RiV/d3planner#118]
Wanted to have the simulator use Archon Slow time (toggle it on) if Buff Stacks of Archon Slow time = 0 but Archon Slow time isn't listed as an available option in the dropdown.

Thanks!

**Comment by d07RiV** [comment]
It uses the regular 'slowtime' buff, which isn't listed as an option when you have Archon (bug). You should be able to select it if you uncheck the box at the top, though.

**Comment by d07RiV** [comment]
Fixed.
