### ISSUE TITLE
Simulator Ignores Endless Walk "Moving" Setting

### ISSUE THREAD

**Issue by Manson1716** [d07RiV/d3planner#119]
Under the skills/effects tab I adjusted the "Moving" setting for endless walk and re-ran the simulator which resulted in the exact same DPS regardless of if moving was set to 0 or 5 or anywhere in between.

Thanks!

**Comment by d07RiV** [comment]
It does, movement in general isn't supported by the simulator atm. I might enable it for just Endless Walk, but there are plenty of other movement-dependent buffs, so it won't be very fair to them.

**Comment by d07RiV** [comment]
Fixed.
