### ISSUE TITLE
Simulator - Cyclone strike cold rune does not seem to freeze mobs

### ISSUE THREAD

**Issue by emartinezgh** [d07RiV/d3planner#123]
The freeze condition does not seem to be set on the simulatior when using cyclone strike with the cold rune.

**Comment by d07RiV** [comment]
I'm surprised it even worked for you, that rune breaks the simulator for me. Fixed now.

Don't forget to set the correct range (I still haven't added range warnings for monks and crusaders) and that targets can be subject to diminishing returns on CC (the conditions are only checked on the primary target, which is usually the boss).

**Comment by emartinezgh** [comment]
I have what seems like a follow up issue with this simulation I was trying.

When I change the hits/min (taken) the simulator gives different (higher) results...

http://www.d3planner.com/557339546

I don't understand why it is doing that. 

I'm not sure what's going on in the simulation but it seems to be doing more than 5 APS. Will continue testing.

**Comment by d07RiV** [comment]
I'm pretty sure the 5 APS is only the cap for your 'sheet' speed, and items like Rivera Dancers can make individual skills attack faster.

I haven't noticed any difference when changing the hits/taken, no it shouldn't generate any spirit.

**Comment by d07RiV** [comment]
Ok found the bug, it was using the hit rate for globes/min as well. I hate javascript scope semantics ;[
