### ISSUE TITLE
Augustine's Panacea - not importing EA bonuses

### ISSUE THREAD

**Issue by jsmachado** [d07RiV/d3planner#126]
#Augustine's Panacea is not showing the bonuses for elemental arrow after importing a character, not using them do display the damage calculation.
I'm testing with this DH: http://us.battle.net/d3/en/profile/Machado-1633/hero/28453583

Evidence: On the left the original item, in Battle.Net website. On the right, the imported one in D3Planner:
http://www.softbr.com/img/diablo3/AugustinesPanacea.jpg

I took the liberty to download the item Json from Battle.Net API, and it seems to bring the value of EA bonuses as a ring type. I've put the JSON here:
http://www.softbr.com/img/diablo3/AugustinesPanacea.json

The EA bonuses seem to be in this key: [Item_Power_Passive#P41_ItemPassive_Unique_Ring_011]. The only thing I couldn't find easy is the Ball Lightning speed.

**Comment by d07RiV** [comment]
I don't look at the actual attributes and instead parse the tooltip lines, as its significantly easier than mapping all attributes to their actual names (although I probably have the tools to do that instead now).

I can fix the bug, but I can't check it as your profile no longer has the item equipped :|

**Comment by jsmachado** [comment]
Sorry bro, I've been playing this weekend and I forgot to re-equip it after finishing. It should be on now.
I've put a 250% bonus version.

**Comment by d07RiV** [comment]
Thanks, fixed.

**Comment by jsmachado** [comment]
You sir, are a legend. Thank you very much!
