### ISSUE TITLE
[Mantra of Retribution - Transgression] IAS bonus incorrectly counted twice with Inna's (2) bonus.

### ISSUE THREAD

**Issue by infintieice** [d07RiV/d3planner#127]
[Mantra of Retribution - Transgression] gives you and your allies a bonus 10% to attack speed.

This is stated in the tooltip as passive aura effect.

Inna's 2-piece set bonus increases the BASE effect of your mantra by 100%. This does not include runed, but passive, effects within the game itself, but does on D3planner. Thus, D3planner incorrectly shows a 20% gain in Attack speed from this Mantra's Rune, when in reality you only gain 10% in-game.

Example, here is my profile with Inna's and set up with Mantra of Retribution - Transgression: http://www.d3planner.com/981278164

You can see the stats say Attack speed increase - 30%. Hovering over this shows the tooltip of the sources of the IAS.

    Paragon points give 10% -- this is correct.

    Mantra of Retribution: 20% -- this is incorrect.  You only get 10%, the Transgression rune is not part of the _base effect_ of the mantra, and is thus not increased by 100% due to Inna's 2-piece set bonus.

Easily confirmed in game; changing to any other rune of Mantra of Retribution causes me to lose 10% attack speed, not 20.

Screenshots can be taken if required, this is an extremely fast thing to check for anybody though.

**Comment by d07RiV** [comment]
Fixed.

**Comment by Griddler** [comment]
Hello,

this does not seem to be fixed.

If you take inna's mantra + the normal one it shows 1.20 ias instead of the supposed value of 1.10 
(Since they do not stack)
