### ISSUE TITLE
Feature request: Additional selections for timeline data source

### ISSUE THREAD

**Issue by TheveninRDM** [d07RiV/d3planner#129]
As the title indicates, this is just a feature request to make additional sources available for tracking in the timeline below the paper-doll. In particular, 

For example, I'm often interested in watching the change to the damage of a particular skill as opposed to sheet or entirely simulated DPS. In this case it would be nice to have access to the "Damage" (or "DPS" value for applicable skills) for each of my equipped skills in the drop-down menu of the timeline.

**Comment by d07RiV** [comment]
Its fairly difficult to do, and I don't like the way the timeline works anyway (it keeps creating tons of duplicate events sometimes) so I'll have to rework it someday.

**Comment by d07RiV** [comment]
Done.
