### ISSUE TITLE
Bane of the Stricken and Zodiac are now fully dynamic

### ISSUE THREAD

**Issue by plopinou** [d07RiV/d3planner#13]
The current simulator behavior is correct only for the 2.3.

Example before : using Hammer of the Ancient with the Bracers of the First Men resulted in only one BotS stack every 2 hits, because it had an internal CD snapshotted to your default Attack Speed.
That's why you had to "potion snapshot" with a stacked legendary Pain Enhancer gem.
That was also the case with the OrotZ in 2.2, and probably to a certain extent in 2.3.

I tested the current 2.4 behavior, and I can confirm that now BotS always stacks once per hit. 100 hota hits = 100 stacks, with or without the bracers. I tested it on Live yesterday, using rend to see the damage difference before and after the 100 hota hits.

Zodiac procs are also always dynamic, the proc rate is changing in real time if you have 1 or 50 mobs around you with Pain Enhancer (confirmed with a 60 fps video).

So I'm pretty sure BotS and Zodiac are fully dynamic. That's why they should proc once every 3 WW hits for example (instead of 6 as in the current sim, at least for BotS).

If anyone is playing another class that greatly rely on those 2 items can confirm that their behavior has been updated, that's be cool :)

**Comment by dominiklohmann** [comment]
Keep in mind that the ICD changed from `ceil(0.9 * 60 / APS)` to `ceil(0.9 * FPA)`, with APS being your sheet APS and FPA being the Frames Per Attack of the skill that last added a BotS stack.

This means in practice that you can get unlucky with a skill with a secondary animation, because they might make the internal cooldown and your attacks desync.

**Comment by plopinou** [comment]
Thanks for your input.
How having BotS ICD be always inferior to your last action time could cause a desync ?
Do you have any link related to the new BotS math in 2.4, I didn't find anything on reddit or the official forums about this new formula.

Anyway the current simulation only adds one stack every 3 hota hit, so changing it to one stack per hit should be a lot more accurate.

**Comment by dominiklohmann** [comment]
I tested this on a wizard with Spectral Blade (+125% IAS from Fragment of Destiny and Shame of Delsere) and Arcane Orbit... when you got Arcane Orbit to proc Bane of the Stricken, it wouldn't proc from Spectral Blade for the next 2 casts.

This change has been announced by Wyatt Cheng on the forums and has been made for Bane of the Stricken, Obsidian Ring of the Zodiac and Chantodo's Resolve. I don't know if they changed it for any other items, but these are what he talked about in the PTR Feedback forums at least.

**Comment by plopinou** [comment]
I see, so yes in the case where you cast a short FPA skill after a slow one, you can skip 1 or 2 stack of BotS.
Implementing this behavior in the sim would be great, but simply changing it to 1 stack would already be an improvment :)

**Comment by dominiklohmann** [comment]
It really only happens with skills that have a delayed hit because of slow missiles (like Arcane Torrent) or spells with a secondary cast animation (like Explosive Blast), but you can manage to do it quite often by accident, so I think it matters for the simulator.

**Comment by d07RiV** [comment]
It should already work for BotS (I fixed it around a week ago), will add to the other two I suppose.

**Comment by d07RiV** [comment]
Uh currently OROZ and Chantodo's are implemented without an ICD, but rather as having a limit per cast. OROZ can only proc once per cast, and Chantodo's can proc 3 times. I'm not sure if that is the correct behavior, but I can try to dig up some discussions that led to this decision. By the way, the game data does not list any ICD values for these effects:

http://www.d3local.com/powers/ItemPassive_Unique_Ring_920_x1 (OROZ)  
http://www.d3local.com/powers/P3_ItemPassive_Unique_Ring_021 (Chantodo's)

**Comment by dominiklohmann** [comment]
That's very interesting, considering Wyatt Cheng listed all of these in the same thread. Considering they all worked the same way before I assumed they would also work like the updated Bane of the Stricken.

**Comment by d07RiV** [comment]
You mean they used to have an ICD? I honestly don't know, its been a while since I made those. I think Chantodo's was researched on the wizard forums when 2.3 was on PTR, I probably picked that up there.

**Comment by dominiklohmann** [comment]
They were snapshottable the same way you could snapshot Bane of the Stricken... It was essentially why Vyr's wizard cleared 84 in season 4, because they used all of them. IIRC Vyr's 6pc worked the same way, but limited to 3 stacks per attack.

**Comment by plopinou** [comment]
Thank you for your correction, BotS now correctly stacks once per hit in the sim.
Except when you use the Slaughter Rune of Wrath of the Berserker. It still only stacks once every 2 or 3 hits.
I just checked in game just to be sure, hitting 100 times a mob with slaughter active, but there isn't any weird behavior, so it's just a bug of the sim.

**Comment by d07RiV** [comment]
Oh, that's an interesting point. Currently, Slaughter (in the simulator) is considered to trigger from WotB, which uses the default attack speed, so if you proc it with the speeded up HotA, it might block the procs from the next few hits. If you're saying that it doesn't have this effect in the actual game, it is possible that all such procs use the speed of the actual attack that triggered it. I'm trying to find a way to make it work that way with my current system.

**Comment by dominiklohmann** [comment]
This is very interesting, are there any procs other than Slaughter with a proc coefficient which can throw this off?

**Comment by plopinou** [comment]
Well, I previously hit 100 times a mob, but not by continuously pressing the HotA skill : I was waiting a little between each hit to be sure I was counting correctly.
So I redid some test by letting the HotA skill pressed, but I find the same result every time :
100 hota hits with wotb active or not, and with either the insanity or the slaughter rune = always 100 BotS stacks.
I also tested it in 2H or DW to confirm there's no different behavior.

No buff was used except WotB.

**Comment by d07RiV** [comment]
Yeah pretty much everything that triggers and deals damage with nonzero proc coefficient will throw off the simulation currently, I guess that needs fixing.

**Comment by plopinou** [comment]
Could this explain the fact that Battle Rage Bloodshed is under performing a lot in the sim with HotA compared to live ? I was going to open an issue about that.

If I can kill a very dense pack of 50 skeletons with no AD and no Bloodshed in 50s, simply using Bloodshed drop the time down to 10s, meaning Bloodshed has done 80% of the damage.
But in the same situation with this settings in the sim : 
- spread 18
- size 2.5
- globes/min with reaper's for rage
- whites 50
Bloodshed is only at 40% of the damage done, meaning the sim DPS is 3 times inferior to what's really happening on live.

**Comment by d07RiV** [comment]
I see the problem with Bloodshed, it seems to ignore the number of targets hit (and crit chance, too).

c53690e1a4f2d046cdb40b8e58a77a6ac855aa29

**Comment by plopinou** [comment]
The bloodshed change is live, the damage is now a lot more realistic, thanks !
But could you change the Cleave's Broad Sweep rune to have the correct proc coefficient ? It seems to be the same 0.667 that the other ones instead of 0.4.

A lot of info about barb's proc coefficient are in this master Nubtro topic :
http://us.battle.net/d3/en/forum/topic/18719273416

**Comment by plopinou** [comment]
After some further testing, bloodshed seems to not take into account proc coefficients.
If I sim a WW barb hitting 2 targets with infinite rage, bloodshed is representing 10% of all the damage done, which can only mean it procs on 100% of the crits, considering it will only hit the other target.

I tested in game with bash :
- with no rune, 1 crit = 1 proc on the other target 100% of the time
- with the pulverize rune, 1 crit = 1 proc every 3 hits on average on the other target, which corresponds to the 0.333 coefficient found by Nubtro.

**Comment by d07RiV** [comment]
Should it take proc coefficients into account then? That seems really strange, as its already doing damage based on the actual damage done, so making it consider proc coefficient makes no sense as it punishes faster hitting attacks for no reason. So it definitely works like that in-game then?

**Comment by plopinou** [comment]
Yes, I tested it thoroughly with 2 mobs : the lower the proc coefficient, the less bloodshed is useful.

I also did multiple sessions of testing on very dense skeletons packs in the Crypt of the Ancients to see the behavior of multiple AE skills.

What is certain, is that Bloodshed is incredible for HotA, but at best average for whirlwind.
With no AD, it's ok, but with high AD (100+), bloodshed benefit is hardly noticeable, because it doesn't proc AD. By hardly noticeable I mean that if I killed 20 mobs out of 50 in 30s without, I killed them in 28 or 29s with. This behavior is not specific to the 2.4, some quick test in 2.3 a few months back already showed this behavior with whirlwind.
That's why I never really understood why top leaderboard barbs in the previous season were using bloodshed in WW builds while stacking 150+ AD, because actual in game testing shows nearly no dps gain for a lot more density lag.

On the other hand, WotB Slaughter, which also depends on proc coefficient, does seem to proc AD, and so is always incredible on high density packs (but it's even worse density lag wise).

**Comment by d07RiV** [comment]
WotB Slaughter has an actual proc coefficient (of 0.25), so it indeed procs AD.

I think I've fixed Slaughter+BotS, and added proc coefficient into consideration for Bloodshed.

**Comment by d07RiV** [comment]
Can someone help out with testing OROZ, Chantodos and Gogok cooldown mechanics? It seems that they follow a similar pattern, but Chantodos always stacks faster than Gogok so I'm not sure what causes the difference.

**Comment by d07RiV** [comment]
Ok I did some testing myself, results are here: https://docs.google.com/spreadsheets/d/1Ftdzee5uafJgS3phu9LSX5FPzmc30FxejfR9r6bRPx8/edit#gid=2044139806

I simply held down AT (discharge) and periodically used Nova.

First 4 columns are time when various effects proc'd. Column E indicates when I used FN. F&G are stack counters, I is attack speed, and M/N/O are times between procs (chantodos column ignores FN uses here).

What I'm getting is that Gogok has fixed 0.9 second ICD, OROZ has a cooldown that scales with APS, and Chantodos either has no ICD at all, or its ICD is per-skill, since every time I used FN it gave a stack independently of stacks gained from AT.

**Comment by dominiklohmann** [comment]
Chantodo's behaviour changes if you pot/zone after your sheet APS changed. You can also get double procs from Arcane Torrent (Static Discharge) if you're lucky.

**Comment by d07RiV** [comment]
Didn't they fix it?

**Comment by emartinezgh** [comment]
Does the Zodiac  cooldown (that seems to scale with APS) work the same way for channeled and non channeled skills?

Zodiac is weird. Last I read was that it was supposed to have no ICD and proc exactly once per cast that deals any damage.
