### ISSUE TITLE
Bug damage% ball ligthning in damage and ...

### ISSUE THREAD

**Issue by TheDark424** [d07RiV/d3planner#130]
Shoot a ball of lightning that electrocutes enemies along its for 300% weapon damage as Lightning.

Damage calculator ...  Skill multiplier is 150% not 300%??? 
![capture ball](https://cloud.githubusercontent.com/assets/19966356/16104875/f5e74e7a-3352-11e6-9c51-ea5d4747bbac.PNG)

**Comment by d07RiV** [comment]
It actually does 150% damage every 0.7 seconds, the tooltip is misleading.
