### ISSUE TITLE
PTR 2.4.2

### ISSUE THREAD

**Issue by dominiklohmann** [d07RiV/d3planner#132]
Can we get some PTR d3planner going?

**Comment by d07RiV** [comment]
Uh yeah will work on that tomorrow.

**Comment by d07RiV** [comment]
Any info on new FB mechanics? Does it only trigger off actual skills, i.e. no Chantodos and stuff?

**Comment by dominiklohmann** [comment]
Chantodo's doesn't, but the Archon skills do. FWIW, Magic Weapon: Ignite procs it for whatever reason.

Firebird's mechanics are probably gonna change again - the current iteration must be the reason for some of the most hatred I've ever seen in the PTR Feedback forums. Not sure if it's worth toying around with that until we've seen another 1-2 iterations of 2.4.2.

**Comment by d07RiV** [comment]
Hmm I'm guessing it is considered underpowered and/or clunky? It certainly seems underwhelming for a set that requires 3 offensive skills and provides no defense bonuses.

**Comment by dominiklohmann** [comment]
It's like a worse version of Tal Rasha, you need 3 skills, the setup takes too long, and the damage buff is lower. It features no damage reduction at all. There's really no reason to play it outside of combinations with Archon (although you now have to ignite enemies outside of Archon, which is really, really annoying).

**Comment by d07RiV** [comment]
I'm getting a few weird things in the game data, not sure if its the same way in-game.

New crusader belt seems to have only 3 primaries? They also seem to have kept most of the old affixes on new items, such as bleed damage on the new fist weapon, and a lot of new items seem to have 3 secondaries?

Also, unruned Spike Trap seems to still deal fire damage despite the tooltip change.

**Comment by dominiklohmann** [comment]
>  such as bleed damage on the new fist weapon
And here I was trying to roll a good one yesterday. Some didn't even roll mainstat.

Haven't tried Crusader yet, but only 3 primaries seems really weird.

The whole patch seems super rushed, don't think they had all too many people working on it.

**Comment by d07RiV** [comment]
> Spike Traps gain the Impaling Spines rune and are deployed twice as fast.

How does that affect the skill damage? I don't recall any previous item that added a rune effect for a skill that modifies the base damage.

**Comment by opelit** [comment]
I recommend you to wait until next ptr patch , it is coming with sooo many bugfixes and then we will see how it work ;)

**Comment by d07RiV** [comment]
PTR version is up.

**Comment by opelit** [comment]
PTR version is up , but no changes here :)

**Comment by d07RiV** [comment]
Oh damn I forgot to update the php. Fixed now.

**Comment by opelit** [comment]
ok lets go , gazing demise : 
Spirit Barrage isn't channeled spell , the description is bad .
Its ~1s buff stacking up to 5 if you hit an enemy , so it work with Manitou and Phantasm also.

**Comment by d07RiV** [comment]
Ah, that makes more sense.

Yeah I figured Grin Reaper wouldn't work anymore, but I forgot about it when going through the datamined changes as its only mentioned in patch notes.

Invigorating doesn't interact with any other part in the planner so I didn't bother changing it. I'd rather not have it affect healing in the simulator, as its meant to model party healing.

Demon's Demise should work in the simulator, I made a typo in the skills tab which prevents it from appearing.

**Comment by d07RiV** [comment]
Yep as I said, its not there because of a typo.

**Comment by d07RiV** [comment]
Ok still not sure how Gazing Demise would work. If it gets a stack per cast, how would that work with Phantasm and Manitou? If it gets a stack per second, well that's some pretty weird mechanics for a non-channeled skill.

**Comment by opelit** [comment]
it get stack if hit xd , description should look like this 👍 
Spirit barrage deal 500% more dmg every time it hit enemy (max 1 stack per/s) up to 5 stack.

**Comment by d07RiV** [comment]
Ok so its 1 stack per second, which means it would have some weird breakpoints if you want to make it stack faster >.>

**Comment by opelit** [comment]
idk , i would wait for next patch that fix the bug first then i can test it more .

**Comment by d07RiV** [comment]
Okay yeah I guess I'll just leave it as-is until we have more details.

**Comment by opelit** [comment]
i checking it also via cascExplorer :D but the sub-site is much easier !

**Comment by opelit** [comment]
trolololo xd 
patch 2.4.0 Occulus Ring
**The damage bonus provided by this item is now multiplicative with other sources of damage**

: xd

**Comment by d07RiV** [comment]
Huh? Its been that way for a while.

**Comment by opelit** [comment]
atm its addictive with another buffs / debuffs in d3planner

**Comment by d07RiV** [comment]
Indeed, forgot to change it in party buffs. If you equip the ring it works fine though. Fixed.

**Comment by opelit** [comment]
another old : voo;'s juicer is ceremonial knife not a dagger :)

**Comment by dominiklohmann** [comment]
http://ptr.d3planner.com/319162273 This won't simulate for me, probably has to do with the new weapon?

**Comment by opelit** [comment]
I don't think , I had similar build and had another problem that sim only uses sweeping wing .

**Comment by d07RiV** [comment]
Okay there's a new patch up on the CDN, going to see what that's about.

**Comment by dominiklohmann** [comment]
> http://ptr.d3planner.com/319162273 This won't simulate for me, probably has to do with the new weapon?

Okay, I can simulate it now, but something seems wrong with the Sweeping Wind stacks. In the game, I can maintain my stacks against multiple enemies easily by just using LTK, because the DoT of the Vulture Claw Kick rune can proc it.

Not that my comparison here matters much, because as of the latest patch on the CDN LTK is dead again compared to R6. 👎

**Comment by d07RiV** [comment]
Any idea how the new Gazing Demise could work? Would it replace spirit barrage with the Phantasm rune, or will it let you summon spectres in addition to the regular channeling effects (kind of similar to lob blob bomb I think)?

**Comment by dominiklohmann** [comment]
Pretty sure it's gonna do both, otherwise the item would be almost useless.

**Comment by d07RiV** [comment]
Btw updated the /game and /diff pages, they now support more than just two versions.

**Comment by dominiklohmann** [comment]
GNK damage is now considered LTK skill damage and also shares LTKs proc coefficient. This has just been confirmed by Nevalistis on Quins stream.

Also, Scarbringer is actually only +200% instead of the +300% the tooltip suggests, which has been found out by Davlok and posted in the bnet forums.

**Comment by d07RiV** [comment]
So GNK now benefits from LTK% on gear, and causes a second hit with the same proc coefficient? But does not benefit from items such as Rivera Dancers and the new claw?

**Comment by dominiklohmann** [comment]
It benefits from both Rivera Dancers and Scarbringer, aside from the fact that its cooldown still seems to not properly scale with Rivera Dancers attack speed bonus.

There's also gonna be quite a few changes to supports (I hope they don't nerf solo too hard doing that), which Wyatt Cheng announced in the PTR Feedback forums.

**Comment by d07RiV** [comment]
Yeah they seem to all be reflected in the patchnotes. They also doubled GNK rolls (which seems to apply retroactively), so LTK should be doing pretty well now.

**Comment by opelit** [comment]
new build 38066

**Comment by d07RiV** [comment]
Doesn't seem to be any changes in the new build.

**Comment by opelit** [comment]
another 2.4.1 missed change , lakumba bracers DR now addictive , so 60% DR at 10stacks

**Comment by dominiklohmann** [comment]
They updated the patch notes. Some interesting changes... and the knockback changes feel really, really terrible in solo play.

**Comment by d07RiV** [comment]
New experimental feature - visiting /game/builds will automatically download and parse the new patch data if a new build is available (seems to work for 38066, will have to wait for a new build to make sure).

**Comment by dominiklohmann** [comment]
New PTR build, but your experimental feature did not work. It tells you that there's a new build tho.

**Comment by d07RiV** [comment]
Yeah they changed the affix IDs again, I'm looking for a way to update them automatically but I doubt I can do that consistently so the tool will fail to parse some builds without manual intervention.

The build doesn't have anything new, except the power for old RoRG seems to be removed.. wonder if this means legacy RoRGs will become unusable lol.

**Comment by dominiklohmann** [comment]
On PTR, a socketed Topaz with Leorics Crown stacks multiplicatively instead of additively.

While a Diamond in a Helmet gives `12.5% + 12.5% = 25%` CDR, a Topaz only gives `1 - (1 - 12.5%) * (1 - 12.5%) = 23.4375%` RCR. d3planner currently assumes it to be 25% RCR.

Pretty sure this is a bug, and there's also an existing bug report on the PTR forums (that as of now has no replies).

**Comment by d07RiV** [comment]
Looks like a bug, think I'll leave it up for now as otherwise I would have to add it as a special case.

**Comment by dominiklohmann** [comment]
Topaz + Leorics Crown is still bugged on live servers.
