### ISSUE TITLE
DPS of certain skills in Set overview

### ISSUE THREAD

**Issue by OSwoboda** [d07RiV/d3planner#136]
In the Set overview I can compare my sets with each other for e.g. Sheet DPS, Sheet Toughness and so on. But if I choose e.g. Gargantuan DPS it's not displayed there, but the last chosen character stat stays shown. If it's a bug pls fix, if it's a missing feature pls add it. Thx

Profile: http://ptr.d3planner.com/766216135

**Comment by d07RiV** [comment]
I had difficulties adding it to the set list, which is why I restricted it to only the basic stats. I'll fix it once I find a way to do it more easily.
