### ISSUE TITLE
My sim make less damage with multiple targets (maybe "Spirit Barrage - Well of Souls" bug)

### ISSUE THREAD

**Issue by Nemesis666first** [d07RiV/d3planner#139]
Hi, my sim ( http://www.d3planner.com/194834111 ) make less damages with multiple targets, I think it's maybe because the "Spirit Barrage - Well of Souls" don't target the other target.

Any idea ?

**Comment by d07RiV** [comment]
You're right, Well of Souls is coded to hit the same target, I should probably fix that. There's a bigger issue, though - buffs are averaged on all targets, which isn't entirely correct when you have massive buffs such as Zuni 6pc. I'll probably be fixing damage calculations to correctly account for different targets, that's a pretty big task though.
