### ISSUE TITLE
Some legendary gems can go over level 100

### ISSUE THREAD

**Issue by plopinou** [d07RiV/d3planner#14]
That's the case of :
- Bane of the Stricken
- Bane of the Trapped

But not the case of :
- Esoteric Alteration

I'm currently looking at leaderboards to get that information, so this list will probably be updated as I find some other possible level 101+ gems.

Anyone having more information about what gem can go over 100 is welcomed.

**Comment by d07RiV** [comment]
Oh I forgot I capped them at 100, that isn't supposed to be the case. I don't really know what gems have unlimited level (there might be something in the game files, I'll have a closer look), worst case they would all have unlimited level and it would be up to the user to be reasonable (i.e. currently Gogok can be set to any level, even though its capped to 50, it just has no effect).

**Comment by dominiklohmann** [comment]
The cap of these gems is effectively 166, because the highest rift that the game allows you to open is 150 (At least that was the case on the PTR).

**Comment by d07RiV** [comment]
Wouldn't people still have a tiny chance to upgrade gems beyond that?

I guess I'll set it to 200 because round numbers are good (and also I capped Caldesann's at 200).

**Comment by dominiklohmann** [comment]
No, you only get a 1% chance for upgrades for 15 gem levels higher than the greater rift level, meaning that the last 1% upgrade you can get is from 165 to 166 in a level 150 greater rift.

**Comment by d07RiV** [comment]
Ah.. well there was a way to get GR151 on 2.3 PTR, not sure how though. There's a video of ZE doing it.

**Comment by dominiklohmann** [comment]
JFYI they capped it shortly after that video at 150, because the game started to crash at 152.
