### ISSUE TITLE
Pain Enhancer Gem Damage Calculation

### ISSUE THREAD

**Issue by VitaKaninen** [d07RiV/d3planner#140]
Currently, the damage calculation for Pain enhancer includes your crit/crit damage in the calculation, but Pain Enhancer damage tics can never crit.  It is always a flat (in my case 6,000%) damage number.

**Comment by opelit** [comment]
Pain enforcer dmg is DoTs , DoTs include CHC/CHD ratio into the dmg.
as 1+(CHC x CHD)

**Comment by VitaKaninen** [comment]
Thanks for the reply.
I just assumed that since I never see orange colors that it never critted.  I wonder why they just averaged in your crit numbers instead of allowing the DOT to crit...

Does this apply to all DOTS?

**Comment by dominiklohmann** [comment]
> Does this apply to all DOTS?

Yes, it does. This was a change a while back and it was noted in the patch notes back then. I've not heard of any DoT not using the `1+chc*chd` multiplier since.
