### ISSUE TITLE
Flying dragon uptime

### ISSUE THREAD

**Issue by Galarix96** [d07RiV/d3planner#143]
The flying dragon uptime seems very off. If im using a generator with 2.0 aps i get almost 100% uptime which is just not accurate.

**Comment by d07RiV** [comment]
Afaik, it has 7 second duration, 5 second ICD and 5% chance to proc on cast, which puts it slightly above 50% uptime with 2 APS. Does that seem close to what you observe in-game? I can't see why the simulator would give you 100%, do you have a link to a profile where this happens?

**Comment by Galarix96** [comment]
This is the build that I'm using : http://www.d3planner.com/365023568 , just run the simulation as it is and the flying dragon uptime should be around 94,85%.

**Comment by d07RiV** [comment]
Well you have 2.8 APS and crippling wave attacks over 5 times per second, so the uptime is expected to be pretty high isn't it?

**Comment by haasn** [comment]
Seems to be the same issue as #190. It would be cool if you could chip in with any additional info you have on that PR as well.
