### ISSUE TITLE
Buff duration doesn't seem to work for item effects (e.g Convention of Elements)

### ISSUE THREAD

**Issue by jimitndiaye** [d07RiV/d3planner#144]
I can use buff duration properly with something like Tals 6-piece bonus but trying to set a condition for x seconds since CoE switched to Fire doesn't seem to work whereas it does for Tals. It just never triggers in the simulation.
I've tried Buff Ticks, Time Since Cast, etc and none of them seem to do the trick.

**Comment by d07RiV** [comment]
Once the fire buff expires it no longer has a duration, and the other conditions are unrelated. You can check for other CoE buffs, i.e. for wizards the cold buff always precedes fire, so its presence means that fire will be up in less than 4 seconds. Sometimes you might need to check multiple buffs and combine them in an "or" condition.

**Comment by jimitndiaye** [comment]
http://www.d3planner.com/877912679
In that simulation, which buffs do you think I could combine to achieve that? Basically, I'm trying to trigger archon exactly 3 seconds into the cold buff. That way spectral blades buff will fall off exactly as CoE switches to lightning.
The two sets only differ in how they are simulated.

**Comment by d07RiV** [comment]
Duration - CoE Cold - less than 1 second
I would also combine it with (CoE fire is up) condition, in case it somehow misses the 1 second window, though that probably won't happen.
