### ISSUE TITLE
Hammer Jammers bonus not applying on immobilize in simulator (immobilize greyed out?)

### ISSUE THREAD

**Issue by skelenot** [d07RiV/d3planner#147]
Hi,

The 400% damage bonus from Hammer Jammers doesn't seem to apply on enemies hit by Immobilize, at least in this situation: http://www.d3planner.com/231655620 (the Sacred Harness belt procs Judgement along with Falling Sword which immob's)

The damage bonus works correctly if I change the Falling Sword rune to Flurry, which stuns enemies.
EDIT: Actually Flurry doesn't work either (I think it's supposed to work? it's not a stun, it throws the mobs around), only Part the Clouds works.

**Comment by d07RiV** [comment]
Oh, the correct keyword is 'rooted', I put in 'immobilized' by mistake.

I'm not sure if Flurry is supposed to work, I have it coded as knockback, which is not part of Hammer Jammers condition.
