### ISSUE TITLE
Resource Cost Reduction should not affect Blade of the Warlord

### ISSUE THREAD

**Issue by plopinou** [d07RiV/d3planner#15]
I tried to make work some barbarian spec using Blade of the Warlord, and began to put RCR on the gear and see if maintaining full fury was possible.
With enough RCR Cindercoat + CotA I managed it, but then I noticed that the actual Bash damage in the sim was also reduced. 50% RCR = bash damage will be only be equivalent to 20 fury consumed instead of 40.

So I checked in game and did 2 test sessions of ~= 50 bash hits on TVI diablo with at least 40 fury.
- with 0 RCR (no point in paragon RCR)
- with 30% RCR (RCR in paragons/2 yellow rings with 7% RCR and no damage, rolled 10% RCR on weapon)

... having the same exact damage in the character sheet in both case.

Result : bash always consumes up to 40 rage, and does not take into account any RCR at all. The damage remains the same.

So the sim is off on this point, and a Blade of the Warlord spec seems doomed :(

**Comment by d07RiV** [comment]
Er, whoops.
