### ISSUE TITLE
Strength has a wrong mutliplier formula? As well as Akarath's Champion?

### ISSUE THREAD

**Issue by AngryRoleplayer** [d07RiV/d3planner#150]
![snag-0009](https://cloud.githubusercontent.com/assets/22470478/18868255/2c057e60-84b0-11e6-86e4-2a6c354b8d39.jpg)
I specifically have set a default 217 strength, yet it still multiplies by 3.17
With more multipliers it's still looks wrong.
For example multiples by an extra 100 strength here as well. 
And Akarath's Champion multiplies by 7 and not by 6.
![snag-0010](https://cloud.githubusercontent.com/assets/22470478/18868412/c9631aa0-84b0-11e6-8d3d-1c5f18c65e6f.jpg)

**Comment by d07RiV** [comment]
Each point of strength increases your damage by 1%, so 400 strength gives you 400% increased damage. 400% increase = 5 times more damage than normal, hence the multiplier. Same for Akarat's and all other similar effects. The only place where it isn't the case is the skill's own damage coefficient, i.e a 135% damage skill will have a 1.35 multiplier.
