### ISSUE TITLE
Possible bug: Health Globe Healing Bonus seems incorrect

### ISSUE THREAD

**Issue by DannyEnsink** [d07RiV/d3planner#151]
Hi,

If you look at the item Corruption on battle.net the value range is 5978–12794:
![image](https://cloud.githubusercontent.com/assets/8476848/19436834/afcde6c0-9472-11e6-9b4b-7ce477cde1a6.png)
http://us.battle.net/d3/en/artisan/blacksmith/recipe/corruption

In your d3planner it gives the following values:
![image](https://cloud.githubusercontent.com/assets/8476848/19436845/c5e95c32-9472-11e6-9eae-67f91318422f.png)
20,001-29,713 (regular)

![image](https://cloud.githubusercontent.com/assets/8476848/19436855/d8ed6170-9472-11e6-9965-86ceaf449345.png)
32,684-38,625 (ancient)

Do you know why these values are different and which should be correct?

**Comment by d07RiV** [comment]
I'm not sure. What does it say in-game? IIRC there was a patch a while ago when they increased the health globe healing values, but that might not have affected Corruption, since my datamine also says 5978-12794.

**Comment by DannyEnsink** [comment]
Here is an example Corruption taken from my current Wizard (see "current" build):
http://www.d3planner.com/878241804

**Comment by jlhall** [comment]
@DannyEnsink @d07RiV 
If you look at the top 5 Corruption's in the world in terms of item perfection, 2 have low <13k values and 2 have >30k values

Is there a difference between hardcore and regular game mode values? That's about the only difference I can find between 2 of the top 3 as they're both ancient. See below:

http://www.diablo3ladder.com/view-item/Corruption-46567181.html
http://www.diablo3ladder.com/view-item/Corruption-28337512.html

**Comment by d07RiV** [comment]
Yeah that's weird, guess I'll just make a wider range for them just in case.

**Comment by DannyEnsink** [comment]
On Battle.net there is no real distinction made between hardcore and regular items as far as I can see. Though, I did find my Corruption on hardcore.

But would they really do that? Decrease the maximum amount of health gain from Health Globes and Potions on hardcore compared to the regular game mode? Would be kinda silly.

**Comment by d07RiV** [comment]
Pretty sure that's not the case, there's nothing to indicate any differences between hardcore and softcore items, other than Ancestor's Grace which is hardcore only.

You couldn't find them as its a crafted item. When did you make them, could it be before the healing bonus changes a few patches ago?

**Comment by DannyEnsink** [comment]
> When did you make them, could it be before the healing bonus changes a few patches ago?
I made them with a seasonal character during Season 7 on a Hardcore Wizard.

**Comment by jlhall** [comment]
Hey @d07RiV @DannyEnsink Currently by design, Corruption shoulders are rolling in the 5978-12794 range. I tested this over the weekend on softcore seasonal and normal. A bug report exists (as most other shoulders roll at the higher range now and no clarification is made as to why Corruption still rolls at the lower level). 

Guesses argue that: **Corruption rolls lower health globe values due to the guaranteed health globe radius roll on the item.**

Either way, @DannyEnsink I think we can close this up, as @d07RiV now has the info they need

**Comment by DannyEnsink** [comment]
Thank you @jlhall for testing this.
Best @d07RiV can do (for now) is to increase the possible range to 5,978-38,625.

**Comment by d07RiV** [comment]
Thanks, apparently I did that a while ago, but only uploading the change now.

**Comment by d07RiV** [comment]
It seems they updated Corruption to have a higher roll, but it still doesn't seem to be high enough. Also globe radius seems to be just 1-2yd now?
