### ISSUE TITLE
Wrong stats on Spirit guards

### ISSUE THREAD

**Issue by BCLV4** [d07RiV/d3planner#153]
I can't use base armor more than 421 but the one I have is 462.

Can't use Cold damage increase too on it too.

See my battlenet character profile : http://eu.battle.net/d3/fr/profile/BCLV4-2482/hero/84034459

**Comment by d07RiV** [comment]
Not sure what you mean, your bracers have 462 dexterity, not armor. And you can definitely choose cold damage in the planner.
