### ISSUE TITLE
Is http://www.d3planner.com/ down?

### ISSUE THREAD

**Issue by Styxion** [d07RiV/d3planner#154]
Hello,

I've tried to reach your site - but I get "This domain maybe for sale! Buy it now! Click Here".

Have you changed your URL?.

Greetings
Styxion

**Comment by areolysz** [comment]
It did work yesterday, but not today. Looks like the hosting account got canceled. Let's hope it'll be back up again!

**Comment by Styxion** [comment]
I hope too...

**Comment by jlhall** [comment]
@areolysz @Styxion it is back up! Would close this but no permissions. Cheers!

**Comment by Styxion** [comment]
Hi jlhall,

thank you for your info - I close it.
