### ISSUE TITLE
2.4.3 PTR Datamine

### ISSUE THREAD

**Issue by dominiklohmann** [d07RiV/d3planner#155]
Seems like the datamine on the site hasn't updated automatically this time. Was wondering what changes there were that weren't mentioned in the [official patchnotes](http://us.battle.net/d3/en/blog/20362179/patch-243-ptr-patch-notes-11-8-2016).

**Comment by d07RiV** [comment]
Oh I think they changed the format of their CDN a bit, I encountered this already but didn't care to investigate. I'll look into it tomorrow.

**Comment by d07RiV** [comment]
I see, they no longer list all the previous builds. That doesn't change too much I guess.

**Comment by d07RiV** [comment]
Done.

http://www.d3planner.com/diff/items etc

**Comment by dominiklohmann** [comment]
Awesome, thank you very much.
