### ISSUE TITLE
PTR Discussion

### ISSUE THREAD

**Issue by d07RiV** [d07RiV/d3planner#157]
Uploaded the first version of 2.4.3 PTR - currently all new items should have stats and artwork; new legendary affixes and skill changes are not done yet. Neither is the simulator.

Might need some clarification on the new Hellcat Waistguard - how do these grenade work? It seems to be 50% proc chance, but do they bounce in a straight line, what distance etc?

**Comment by d07RiV** [comment]
Updated new legendary powers and skills, only simulator left.

**Comment by dominiklohmann** [comment]
> Might need some clarification on the new Hellcat Waistguard - how do these grenade work? It seems to be 50% proc chance, but do they bounce in a straight line, what distance etc?

Here are some recordings. Seems to be quite random. They also stop when they hit any obstacle, much like Energy Twister.

https://gfycat.com/HilariousZestyDikdik
https://gfycat.com/DifficultPinkKrill

**Comment by jimitndiaye** [comment]
Is Paralysis (wizard) simulation accurate? It's supposed to be a flat 15% procc chance (doesn't depend on skill procc coefficient) but the simulation results don't seem to indicate that. Is it possible to add it to the summary table (uses/second). Could Manald Heal DPS be added to the simulation as well? For the purpose of Manald heal, paralysis ignores CC resistance. Essentially manald heal DPS would be 0.15 * APS * 14000. If Paralysis proccs on any enemy , all enemies hit by that attack will take damage from Manald heal. This means procc chance is 15% * number of enemies hit.
