### ISSUE TITLE
Inna's Mantra 6pc bonus display bug

### ISSUE THREAD

**Issue by arturluizbr** [d07RiV/d3planner#159]
First - Damage of Mystic Ally dont get Inna's Mantra 6pc bonus.
Second - Damage Multiplier displays Inna's Mantras in details only (the total value dont show damage buff)

**Comment by d07RiV** [comment]
Doesn't 6pc only apply to yourself, similar to DH M6? I'm not sure where to check this information.

Not sure what you mean in the second line, I can see the 250% damage bonus in the tooltip and the damage is appropriately increased.

**Comment by arturluizbr** [comment]
![inna1](https://cloud.githubusercontent.com/assets/3036919/20502657/d5bef88a-b01d-11e6-9a83-7f457bc6a84e.PNG)
![inna2](https://cloud.githubusercontent.com/assets/3036919/20502658/d5c33d28-b01d-11e6-927a-152e2a648f2b.PNG)

Inna1 - Show Inna's Mantra being applied
Inna2 - Shows that Inna's Mantra is not being applied

6pc says - "Your damage is increased by 50% per Mystic Ally you have out" (So i think this should be applied to all skills

**Comment by arturluizbr** [comment]
![inna3](https://cloud.githubusercontent.com/assets/3036919/20502725/3b22a064-b01e-11e6-87ce-f90630b8a399.PNG)

I guess the second issue is solves, because it was show Inna's Mantra on detailed tooltip, but the sum was not including it, now it don't show Inna's Mantra at all.
