### ISSUE TITLE
Feature request for sim : rage generated thought damage taken

### ISSUE THREAD

**Issue by plopinou** [d07RiV/d3planner#16]
I've played a lot with the sim this pas few days with barb setups, and one thing that saddens me a little is that I often have to change the kanai's cube item to the Reaper's Wraps and change the Globes/min slider to be sure the sim is not rage starved. That is a great thing and very well though to validate the viability of a spec.

But on live, taking damage generates fury, sometimes more than 15 per s if there's a lot of monster hitting you or your're standing in a fire. It seems to generate 1 rage per hit, without cooldown, but I didn't test this thoroughly.

If you have a lot of life regen, voluntarily standing in a fire can be a trick to use on boss fight or elite packs. This is often used by top leaderboard players.

What would be cool is a new slider letting us choose the rage/min generated between 0 and say 2000, by steps of 10 or 20.

Is that possible ? :)

**Comment by d07RiV** [comment]
Yeah I need some more sliders for sure, this one seems easy to implement I guess.

**Comment by plopinou** [comment]
Adding an option to set an initial rage/resource level would be usefull too. You often fight an elite pack after clearing some whites, and you're generally full rage (except in some specific cases).

For example, in case of an hota spec, balancing the rage gain/cost is crucial, and starting to hit 4 or 5 monsters instead of 3 or 10 will slowly drop your rage (if you have weapon master).

**Comment by plopinou** [comment]
After some rapid testing in game, rage generation through damage taken seems simple :
`damage taken / max hp * 0.5`
Whether you have lot of resist all/armor or nothing does not change anything, neither having more max fury

**Comment by d07RiV** [comment]
Yeah I think I saw something about it giving a flat amount of rage per percent of max life lost. Your formula would give half a point of rage for the full health globe though, which is certainly a bit off :)

**Comment by plopinou** [comment]
oops, yes, x100 is indeed needed :)

**Comment by d07RiV** [comment]
Added starting resource slider, still have to add rage generation for barbs.

**Comment by d07RiV** [comment]
This is solved now too, I suppose.
