### ISSUE TITLE
Tal Rasha's Allegiance

### ISSUE THREAD

**Issue by Digimstr** [d07RiV/d3planner#161]
The low range for both Life After Each Kill and Thorns is not allowing for low enough stats.

Life After Kill on web site shows lowest at 6428.
In game have an amulet with a current state of 5325

Thorns on web site has low end of 5334
In Game have an amulet with 3592

**Comment by d07RiV** [comment]
Is your amulet level 70 or lower? The website currently does not support items acquired at lower levels.

**Comment by Digimstr** [comment]
No it is level 70 

Get Outlook for iOS




On Mon, Nov 21, 2016 at 1:29 AM -0700, "d07RiV" <notifications@github.com> wrote:












Is your amulet level 70 or lower? The website currently does not support items acquired at lower levels.
