### ISSUE TITLE
simulator skill conditions are confusing

### ISSUE THREAD

**Issue by miaomimao** [d07RiV/d3planner#163]
It's really difficult to figure out how the conditions like"buff stacks", "buff duration", "debuff targets", "buff ticks, "charges" work.

like how do I setup WitcherDoctor skill "Haunt" to be casted on every monsters?

Are there  manuals or examples on to set up a skill rotation?

**Comment by d07RiV** [comment]
I should really add an info box for that, I know a lot of these can be confusing and should be clarified.

For Haunt specifically, it should automatically be cast on new targets until everything is affected, then it will keep casting on the first target (the boss). Buff stacks should always be 1 (basically the number of stacks on the boss) and debuff targets should be the number of affected monsters.
