### ISSUE TITLE
Item database auto update broken for PTR 2.4.3.42336

### ISSUE THREAD

**Issue by dominiklohmann** [d07RiV/d3planner#164]
> New build detected. Item database should be updated within a minute.

http://d3planner.com/game/builds has been saying this for way more than a minute now. Seems to be stuck yet again.

**Comment by dominiklohmann** [comment]
Any update on this @d07RiV?

**Comment by d07RiV** [comment]
Fixed.

**Comment by dominiklohmann** [comment]
Thanks!
