### ISSUE TITLE
there is no changes on Roland in 2.4.3 PTR version

### ISSUE THREAD

**Issue by yugnalgum** [d07RiV/d3planner#165]
still increase 750% damage in PTR version of d3planner.
Actually, Roland was buffed in 2.4.3 PTR by 1250%.
Please fix this.

**Comment by TsuKuSs** [comment]
it will be update soon: the owner said on another post: "No, I haven't updated to more recent PTR version yet. I've been away for some time, will be back soon and then I'll update everything."
