### ISSUE TITLE
Are swami and archon stacks really treated additively?

### ISSUE THREAD

**Issue by stolemyowncar** [d07RiV/d3planner#167]
A person on the wizard forums has said that the simulator still treats Swami and Archon stacks multiplicatively instead of additively, based on his spreadsheet values on FB archon when compared to the simulator values. Could you do a quick check to verify that this was fixed? I do see a closed case for it here:
https://github.com/d07RiV/d3planner/issues/148

Also Manald and DMO got a major buff but I'm sure you're going to work that in at some point.

**Comment by d07RiV** [comment]
Yep they should definitely be additive now.

I haven't checked for recent PTR updates yet, will do that soon I guess.
