### ISSUE TITLE
PTR not working for Inna's 6 pc

### ISSUE THREAD

**Issue by Andy88488** [d07RiV/d3planner#168]
I'm not sure how thoroughly the PTR preview is implemented, but I tried equipping 6 pc Inna's, and it still says 50% damage increase per Mystic Ally, when I believe it should be 100%

**Comment by d07RiV** [comment]
No, I haven't updated to more recent PTR version yet. I've been away for some time, will be back soon and then I'll update everything.

**Comment by Andy88488** [comment]
Great! I noticed that the site hadn't been updated yet to 2.4.3. I'm glad to hear that it's still something you're going to do. Your site is really helpful!
