### ISSUE TITLE
Archon: Combustion explosion not providing Tals(6) Fire stack

### ISSUE THREAD

**Issue by jimitndiaye** [d07RiV/d3planner#169]
The simulator indicates that archon activation does deal damage but it does not apply a Fire stack to the Talrasha 6-piece damage bonus resulting in fire never being activated.

http://ptr.d3planner.com/359385656

**Comment by jimitndiaye** [comment]
@d07RiV is there an ETA on a fix for this? Thanks for all your hard work.

**Comment by d07RiV** [comment]
Ye I can fix it if that is the correct behavior, currently Archon is marked as non-offensive in the sim.

**Comment by jimitndiaye** [comment]
This is still an issue by the way. Still not giving fire stack. It is the definitely the behavior exhibited in-game.
