### ISSUE TITLE
Feature request for sim : average healing per second generated

### ISSUE THREAD

**Issue by plopinou** [d07RiV/d3planner#17]
That's not an easy feature request as healing can come from many sources, but to validate a spec in high GR this is an essential data.
Having 2 billions toughness is useless in GR 90 if you cannot heal yourself except for globes.

This is probably a long term endeavor, and I hope you'll find the time to implement it.

**Comment by d07RiV** [comment]
Oh right yeah this would take some work, mostly because there is no framework to provide any healing numbers in the simulator (and no place to display it in the UI).

**Comment by d07RiV** [comment]
Done.
