### ISSUE TITLE
Cannot Import Battle.net Account

### ISSUE THREAD

**Issue by IRLCartoon** [d07RiV/d3planner#170]
Despite having a valid US BattleNet account, I get the message "The account could not be found." Screenshot attached.
![d3p_anf](https://cloud.githubusercontent.com/assets/24969331/21738735/efb54062-d450-11e6-980f-757e80082ff9.PNG)

**Comment by IRLCartoon** [comment]
Usually running Google Chrome, I attempted disabling Add-Ons as well as switching to (BLECH) Internet Explorer, both to no avail.

**Comment by d07RiV** [comment]
I don't see your profile in the armory, either: http://us.battle.net/d3/en/profile/IRLCartoon-1524/career

Do you have a battle.net link to it?

**Comment by IRLCartoon** [comment]
Actually, I may have just realized the problem.. I USED to play on PC long ago, and recently got back into the game on PS4. I think I remember reading somewhere that PS3/4 and Xbox support were not available for D3 Planner. Is that correct? If so, sorry for opening this issue by mistake..

**Comment by d07RiV** [comment]
Yes, console profiles are not available since there is no API for them.
