### ISSUE TITLE
Can't sign in, Recover email not received, Username taken

### ISSUE THREAD

**Issue by x-ProgrammEd-x** [d07RiV/d3planner#171]
Hi,

I can't seem to sign into my Account whatsoever. 
I always get a "Username/Password not found" message.
I have the credentials stored in my Lastpass Vault, so they are correct for sure. Any attempt to send myself a password reset email also fails, i am not receiving it.

Trying to register with the same gives "Username already taken" so my Account must be there.

Thanks for any helpful suggestions.

**Comment by d07RiV** [comment]
My login is working fine, could be something wrong with your DB entry. What's your username, I can check it for you.

**Comment by x-ProgrammEd-x** [comment]
Hi, thanks for the reply. Username is XotoX.

**Comment by d07RiV** [comment]
Uh you don't have an e-mail set, other than that I don't see any problems with the entry. I can update the email if you need.

**Comment by x-ProgrammEd-x** [comment]
That is strange. Yes please do. How can i submit it to you without everyone being able to read? GitHub has apparently disabled private messages.

**Comment by x-ProgrammEd-x** [comment]
Any news? Ok then let's do it via disposable email adress: 
XotoX.D3Planner@byom.de

thanks for the help

**Comment by d07RiV** [comment]
Added the e-mail

**Comment by x-ProgrammEd-x** [comment]
thanks, it worked now.
