### ISSUE TITLE
Hellcat Waistguard damages

### ISSUE THREAD

**Issue by TsuKuSs** [d07RiV/d3planner#172]
Hello,

I think i found a problem with the calculated damages of the Hellcat Waistguard legendary affix.

I noticed that the calculated damages of the legendary affix are wrong, when you set "bounce" to 1-5, it shows you the damages you deal if you always hit the ennemy with that bounce damages.
For exemple with Cluster Arrow: Cluster Bombs + 5 Sentrys + Marauder's set, if you set bounces to 5, it says that the 5 bounces have the 800% additional damages, but it's supposed to be +50% for each bounce until bounce 4 and then 800% for the 5th bounce.
![clusterarrow](https://cloud.githubusercontent.com/assets/24981809/21746147/975ae614-d53c-11e6-9469-2062b65f118f.png)
you can see the "grenades damage: 6x 72 724 363 384" and it's 6 times the damages of the 5th bounce, and same for the sentry grenade damages x30.

I hope it helped and you will fix this soon enough, thanks for reading me.

TsuKuSs

**Comment by d07RiV** [comment]
Cluster bombs has 5 grenades that drop along the way, and I assume each of them can bounce. Sure, having all 6 bombs bounce 5 times and land on the target together is very unrealistic, but the damage numbers only show what you ask them to show, for anything more accurate there is the simulator.
