### ISSUE TITLE
When d3planner be updated to patch 2.4.3

### ISSUE THREAD

**Issue by lordep** [d07RiV/d3planner#174]
Thanks for this powerful tool, but when d3planner be updated to patch 2.4.3 ?

**Comment by d07RiV** [comment]
Sorry I was really busy lately, I should have more time now though.

**Comment by fiddybux** [comment]
Yes, I notice Hellcat Waistguard cannot be cubed at the moment. Is this why? Not 2.4.3 ready yet? Thank you for an excellent tool. There is no other way to save a great set for backup and testing purposes. Really surprised you can't do this in-game TBH!
