### ISSUE TITLE
Barbarian's Whirlwind tick rate is changed

### ISSUE THREAD

**Issue by Xabster** [d07RiV/d3planner#175]
Barbarian whirlwind ticks every 40 frames (2/3rds of a second) and not 20 frames. It ticks for 66.6% of the listed weapon damage.

I'm unsure how this changes the breakpoints.

**Comment by d07RiV** [comment]
Okay will do, do you know whether they changed tornado tick rates? They used to be 30 AFAIK.

**Comment by Xabster** [comment]
They're 60 now.

I don't know tornado spawn rate
