### ISSUE TITLE
Custom weapons appear to cause incorrect calculations

### ISSUE THREAD

**Issue by Xabster** [d07RiV/d3planner#176]
Adding a custom axe to a character and setting the physical damage range to 1-1 will produce a value of 10-13 weapon damage in the right side. A completely new level 70 profile has 217 mainstat. My expected value would be 1 * 3.17 = 3.17 weapon damage.

Changing the equipped weapon to 100-100 weapon damage range produces a value of 323-327 weapon damage (still with 217 strength). My expected value is 100 * 3.17 = 317 weapon damage.

It looks like planner adds 2-3 weapon damage range as a base value or something similar.

**Comment by d07RiV** [comment]
Ah yes, you can't really make custom weapons. You might've noticed that they have no attackspeed and other weapon-specific stats on the tooltip. Setting physical damage to 1-1 effectively adds 1-1 to your unarmed damage, as if you were wearing a piece of jewelry.

**Comment by d07RiV** [comment]
I've added custom weapons a while ago, so it should work now.
