### ISSUE TITLE
Magic Weapon/Hydra/Chantodo not igniting properly for firebirds

### ISSUE THREAD

**Issue by stolemyowncar** [d07RiV/d3planner#178]
http://www.d3planner.com/137707217

I put this simulation in for a build I made. This should ignite 100%. Hydra, Magic Weapon, and the final stack from Chantodo fire wave. However for some reason with FB4 I'm always sitting at one stack. That means out of what I have on there, at least two things do not seem to provide any stacks.

I have actually tested this very same combo out in the game.

**Comment by d07RiV** [comment]
Sorry for the delay, FB4 will always display 1 stack regardless of whether it is doing 1000, 2000 or 3000% damage. Making it show the correct number of stacks would be quite complicated, unfortunately.
