### ISSUE TITLE
Mystic Ally mechanics

### ISSUE THREAD

**Issue by dominiklohmann** [d07RiV/d3planner#18]
http://us.battle.net/d3/en/forum/topic/16527322731?page=17#338

This is a thread from Davlok about Mystic Ally mechanics. They are definitely off in the simulator, since the active effect of Water Ally doesn't scale with attack speed at all?

**Comment by d07RiV** [comment]
Uh so they double dip in attack speed modifiers?

**Comment by dominiklohmann** [comment]
Apparently, yeah. I trust Davlok with this information, he's known for his mechanic testings.

**Comment by d07RiV** [comment]
I posted in that thread; he's saying that ally attack speed is the same as yours, but do they follow the multiples of 6 frames rule that other pets have? Data files have 40 FPA as their base attack speed, not sure if that value is used, though.

**Comment by d07RiV** [comment]
- Does 2pc double their DPS?
- Does 6pc affect ally DPS?
- Does 6pc make the active portion activate all runes at once?

**Comment by dominiklohmann** [comment]
Just went ahead and tested this.

> Does 2pc double their DPS?
No, it only doubles the passive effect you get, e.g. the increased spirit regeneration from Air Ally.

> Does 6pc affect ally DPS?
Yes, it multiplies all your and your pets damage.

> Does 6pc make the active portion activate all runes at once?
Yes, and you can no longer get the unruned ally. You get 10 allies, and the only benefit of having Mystic Ally on your bar is for the active damage.

**Comment by d07RiV** [comment]
Ah cool. But that also means that you kill one earth ally every time you activate the button and lose 50% damage (or more like 10% of your total).

**Comment by dominiklohmann** [comment]
100% damage, you lose both earth allies actually.

**Comment by d07RiV** [comment]
Davlok's post:

> - Despawns and restores health. Note: This reduces your Inna 6pc bonus by 50%. (only 1 ally despawns when you have 2)

So its actually both?

**Comment by dominiklohmann** [comment]
Just tested in game, it's really only 1 ally that despawns. Always only noticed that my damage dropped and never bothered to test any further... So that's not too bad.  
That's so weird, because all the other actives get actually doubled.

**Comment by d07RiV** [comment]
Also, could you check the special attacks on allies that he mentioned - fire, air and earth seem to have an alternative attack that they occasionally use. Does that seem to be cooldown based, or its just used every X attacks?

**Comment by dominiklohmann** [comment]
Sure, will take a look at it. That might take a few more minutes tho.

**Comment by d07RiV** [comment]
Ah okay I'm not sure if its really important, it seems to make a pretty minor difference and is unlikely to affect gearing or anything.

Btw the tooltip says that Fire Ally active creates 5 clones that explode for 480%. Davlok says there are 4 explosions. Game data says there are 10, for 290% each. >.>

**Comment by d07RiV** [comment]
Uploaded a fix, will possibly edit as I get more info.

**Comment by dominiklohmann** [comment]
- The shortest time I noticed between the special attacks was slightly above 11 seconds (over about 20 special attacks). This does not apply to Fire Ally.
- Fire Ally looks like 5 smaller allies to me when activated, and they all seem to explode once. It also only shows 5 damage numbers for the explosion.
- The Air Ally special attack really deals no damage for whatever reason.

**Comment by dominiklohmann** [comment]
ffs, I just had an Air Ally take 14 seconds between to special attacks.

**Comment by d07RiV** [comment]
Eh I guess I'll just leave some random delay for those attacks, it shouldn't matter too much. Yeah Davlok mentioned that air ally special does no damage.
Does fire ally look like its doing 5x 450% then?

**Comment by dominiklohmann** [comment]
Fire Ally seems to work like the tooltip suggests, so yes.
