### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Ashtor** [d07RiV/d3planner#181]
Hi
I just got 1 suggestion.
There is a delay when updating your class with new items on them,but I don't know how long the delay is between each update. So I was wondering.. Could you remove the delay or fix it so there is no delay at all. That way players can update on the site whenever they equip new items instead of wait few hours or days or something

**Comment by d07RiV** [comment]
The delay on Blizzard's side - I can only retrieve the same data as on your battle.net profile (i.e. http://eu.battle.net/d3/en/profile/Riv-2568/career).
