### ISSUE TITLE
Vo'Toyias Spiker + Provoke shouldn't affect Invoker 6pc

### ISSUE THREAD

**Issue by MarioVX** [d07RiV/d3planner#182]
In d3planner for crusader, equipping a Vo'Toyias Spiker and checking "Include in stats" for the skill Provoke will double the Thorns damage on Punish/Slash from Invoker's 6pc. 

According to [this source](https://www.reddit.com/r/Diablo3Crusaders/comments/41psfg/invoker_interactions/) this is not true for the actual game, so I just tested it myself with video capturing and frame by frame analysis and found that indeed, this interaction doesn't work in game: Provoke does **not** increase Invoker 6pc damage in game, so it shouldn't in the planner as well. 

Hope this gets fixed soon, many players take Vo'Toyias with Invoker because they don't know better.

Cheers!

**Comment by d07RiV** [comment]
Hmm my code indicates that other effects that increase damage taken by enemies work multiplicatively for thorns (normally they are additive with DIBS category). Does that seem to be the case for Invoker P6?
