### ISSUE TITLE
Using a dye completely changes the 3D model

### ISSUE THREAD

**Issue by strohhut** [d07RiV/d3planner#184]
![temp1](https://cloud.githubusercontent.com/assets/15095059/22741640/28efdbe4-ee14-11e6-8b61-37814b52d433.PNG)
![temp2](https://cloud.githubusercontent.com/assets/15095059/22741643/291989ee-ee14-11e6-83ec-89ba600979af.PNG)
![temp3](https://cloud.githubusercontent.com/assets/15095059/22741641/2916af44-ee14-11e6-9a7e-9ed253233338.PNG)
![temp4](https://cloud.githubusercontent.com/assets/15095059/22741642/2916eb08-ee14-11e6-862a-285210d0081b.PNG)

**Comment by d07RiV** [comment]
"Fixed" it, but it might break recolors for some other armors, will have to keep an eye out.
