### ISSUE TITLE
Fists of Thunder: Bounding Light is not correctly simulating single target DPS

### ISSUE THREAD

**Issue by haasn** [d07RiV/d3planner#187]
Fists of Thunder: Bounding Light reads “dealing 240% weapon damage as holy to up to 3 additional enemies.”

As the tooltip describes, this only hits additional enemies besides the first - so it does not trigger at all for single target. Yet d3planner thinks it does, and reports erroneously high single target DPS in simulations as a result.

**Comment by haasn** [comment]
Thunderclap is also not correctly simulated for single target. The description reads that every hit causes the bonus explosion damage, but for some mysterious reason, the first two explosions hit the same target again - the third one can.

So to be faithful, it should check if (index < 2), and if so, remove the ability target from the list of targets to hit with the explosion.

**Comment by d07RiV** [comment]
Fixed.
