### ISSUE TITLE
cannot manually alter damage range on imported ancient orb

### ISSUE THREAD

**Issue by cad908** [d07RiV/d3planner#188]
STEPS / ACTUAL BEHAVIOR
1. open d3planner.com and import characters from battle.net profile "cad#1340"
2. select wizard "zatanna"
3. select ancient offhand orb -- see screen shot
![image](https://cloud.githubusercontent.com/assets/26046775/23343452/cf1fe0bc-fc39-11e6-9a52-b9f25055d647.png)
4. note actual damage range is 367-410 (see https://us.battle.net/d3/en/profile/cad-1340/hero/83613908 )
5. click unlock
6. note that damage range still shows as locked -- see screen shot
![image](https://cloud.githubusercontent.com/assets/26046775/23343523/07a412a4-fc3b-11e6-9c11-1ac4e06f3ade.png)

EXPECTED BEHAVIOR
4. correct imported damage range would be nice (I know this is a known issue with battle.net API)
6. damage range should unlock, so that user can correct it themselves.

NOTE
great tool! thank you for your efforts!

**Comment by d07RiV** [comment]
Not sure why it stays locked, I'll try to fix that. Correct damage can't be 367-410, because ancient offhands have higher damage ranges. Battle.net website has the same issue of showing incorrect values.

**Comment by d07RiV** [comment]
Oh I think you misunderstood it. The lock icon indicates that you can't change the stat (since sources must have a +damage stat), you can still change the values since the boxes aren't grayed out.
