### ISSUE TITLE
Call d3planner via script?

### ISSUE THREAD

**Issue by Xyaxux** [d07RiV/d3planner#189]
Hi there, I like this project, its insane!
However I would like to try out a lot of combinations to see which setup gives me the highest damage. To not do that manually I wonder if there is a possibility to call the d3planner simulation via some script? One would need to input the gear stats, skills and simulation priorities somehow.
Thank you in advance!

**Comment by d07RiV** [comment]
The simulator is ran in a separate worker (all simulator scripts/data are in one folder) so it should be fairly easy to separate.

You can see the input data format if you type `DiabloCalc.exportProfile()` in javascript console on the website.
