### ISSUE TITLE
Whirlwind fury cost per second isn't correct

### ISSUE THREAD

**Issue by plopinou** [d07RiV/d3planner#19]
I'm pretty sure this wasn't like that in 2.3, but the fury cost for Whirlwind seems to have changed in very weird way in 2.4.
I tested a lot of different setups to try and figure out the formula, but I didn't manage to do it in 100% of the case.
What I'm sure so far is that the fury cost is based on the current whirlwind breakpoint : changing your AS while keeping the same breakpoint does not change the fury cost at all.

I also test with 37.4% RCR, but numbers are simply the same multiplied by (1-RCR/100)

The closest formula I found is :

`10 * (1-RCR/100) * SQRT(20/(WW_FRAMES+1))`

It matches quite closely for anything ranging from 9 to 15 frames. between 16 and 20, it's a little off, and quite off for 8 frames and lower.
There must be some rounding behavior in the actual formula, but I can't figure it out.

I also test the Bul Kathos set, and it seems there is a special condition for it : it simply multiplies the theorical fury cost without the attack speed bonus by 1.3. It means that it now actually cost more to use the BK set that to simply have more AS and hit at the same speed (but the BK set also gives 10 rage/s so that's ok).

The istvan's set has nothing special as it simply adds 6% per stack attack speed to the character sheet.

Here are a sample of the data I gathered for those who'd want to try and figure out the formula :

frames | fury cost per s (+/-0.1) with 0 RCR | formula
-------|-------------------------------------|--------
  20   | 10.1                                | 9.75
  18   | 10.6                                | 10.25
  15   | 11.4                                | 11.18
  13   | 12                                  | 11.95
  11   | 12.8                                | 12.91
   9   | 14.2                                | 14.14
   8   | 14.5 (tested multiple times)        | 14.91
   7   | 16.4 (also tested a lot)            | 15.81
   6   | 17.6                                | 16.9

At the 6 frames breakpoint, the in game fury cost with no RCR is only at 17.6 per s, while the sim would calculate 33.33 per s. So even a dirty fix is very much needed :)

**Comment by d07RiV** [comment]
According to game data (http://www.d3planner.com/powers/Barbarian_Whirlwind#Continual Resource Cost):

Formula seems to be 7/(APS*3)+1 per tick, which fits your data pretty well. It does, however, seem to indicate that the cost can actually vary within the same breakpoint, unless there is some rounding involved somewhere.

**Comment by plopinou** [comment]
It's perfect ! thank you again :)
