### ISSUE TITLE
DH's Marauder set's 6 pieces bonus is not correct

### ISSUE THREAD

**Issue by jeffxu71** [d07RiV/d3planner#193]
In English version, the display is correct(1200%), but the damage calculation is not. It still uses the old number (800%). Meanwhile, in Chinese version, neither display nor the real calculation is correct.

**Comment by jeffxu71** [comment]
Update file d3planner/simulator/itemsets.js, line 246&253, it will fix the problem.

**Comment by d07RiV** [comment]
I haven't updated the github in a while, but the planner should have been using the correct values for a while now.

**Comment by d07RiV** [comment]
Oops, found the issue, should be fixed now.
