### ISSUE TITLE
Hydra not triggering Manald in Simulator

### ISSUE THREAD

**Issue by arturluizbr** [d07RiV/d3planner#198]
Hydra not triggering Manald in Simulator

**Comment by d07RiV** [comment]
I don't know the proc coefficients for hydra attacks, will have to investigate first.

**Comment by Manson1716** [comment]
Hi Riv,  I assume you've seen this by now, but just in case...

https://us.battle.net/forums/en/d3/topic/20753695205

Couple of the more important bullet points:

> - Each head has 15% chance to proc Paralysis, and therefore MH. (Yes, it's the same chance regardless of which head cast.)
> - Hydra is treated as a speed coefficient = 1 spell. This means when your hydra head procs paralysis it will proc manald heal exactly one time.

**Comment by Manson1716** [comment]
It has to be lightning hydra but if I'm understanding it correctly... Every lightning damage attack has a flat 15% chance to proc paralysis and when paralysis is proc'd, so is manald heal:

> Hydra is treated as a speed coefficient = 1 spell. This means when your hydra head procs paralysis it will proc manald heal exactly one time. It does not have a "proc window" mechanism.

**Comment by d07RiV** [comment]
Oh right, silly me. So 15% per zap, seems easy enough. Does it also say that the 255% multiplier from the skill is included somehow?

**Comment by Manson1716** [comment]
Yes (looks like you found it) and attack speed:

> Attack Speed is factored in as a damage component for Hydra MH procs. Higher AS will increase your hydra MH proc damage. Hydra MH proc damage scales 1:1 with any AS increase or decrease.

**Comment by d07RiV** [comment]
I added the mechanic, though I ignored the last section with the list of stats that don't affect proc damage, since it is a bit too complicated to separate these atm.
