### ISSUE TITLE
Orb damage range on import seems fixed.

### ISSUE THREAD

**Issue by aeclasik** [d07RiV/d3planner#20]
The damage range on Orbs are always 407-450. Which takes the lowest (407) range from Ancient item and takes the highest range (450) from non-Ancient item. Actual Ancient Orbs in game have a much higher range of 407-600.

**Comment by dominiklohmann** [comment]
For legendary items:
`damageOffhand: {min: 340, max: 370, min2: 380, max2: 450}`

For ancient items:
`damageOffhand: {min: 407, max: 485, min2: 495, max2: 600}`

I assume that only occurs when importing characters?

**Comment by d07RiV** [comment]
You mean you're getting incorrect offhand damage when importing a character? That's a bug on battle.net side, and has been around for ages. Official armory has the same issue.

Or do you mean something changes about it?

**Comment by aeclasik** [comment]
Ah yes you're right, I didn't even check the official battle.net armory. Well I guess that's not something that can be fixed then.
