### ISSUE TITLE
Simulation does not cumulate Soul Harvest stacks

### ISSUE THREAD

**Issue by ManuelPhelouzat** [d07RiV/d3planner#200]
Hello !

In game, when you cast Soul harvest on some monsters having some stacks of soul harvest actives ti completes to the max number of stacks.

Exemple 1 : You can have 10 stacks, you have 6 stacks, you cast soul harvest on 3 monsters, you now have 9 stacks. On theses 9 stacks, 6 use the timer of the firsts stacks and 3 the timer of the new stacks.

Casting soul harvest on fewer monsters than you have stacks does not replace the number of stacks you have by the number of monsters you just casted soul harvest (it used to be like this, but that sucked  a lot). It adds the new stacks to the old ones.

Example 2 :  you can have 10 stacks, you have 5 stacks, you cast soul harvest on 6 monsters, you now have 10 stacks. On theses 10 stacks, 4 use the timer of the firsts stacks and 6 the timer of the new stacks.

You can "refresh" the timer to avoid runing low on stacks. (since the same patch that introduced the adding of stacks).

Thank you for this tool.

**Comment by d07RiV** [comment]
Did they changed it? I'm 100% certain that it used to override your old stacks, so for instance you could never have more than 1 stack on single target.

**Comment by ManuelPhelouzat** [comment]
Yeah, since : [2.3 ](https://eu.battle.net/d3/en/game/patch-notes/2-3-0)

Soul Harvest
Gaining additional Soul Harvest stacks will no longer remove all existing stacks and will instead be added to them. Any new stacks over 5 will replace the stack with the shortest remaining duration.

And of course, it's the same with 10 stacks when you have the Sacred Harvester.

**Comment by d07RiV** [comment]
Ok, should be fixed now.
