### ISSUE TITLE
Suggestion: SSL cert

### ISSUE THREAD

**Issue by JTelcontar** [d07RiV/d3planner#202]
Now that there's a bigger push to notify browser users of "Not Secure" sites, I'd like to suggest that you add an SSL cert for d3planner.com. Let's Encrypt offers a free service for this, and depending upon your hosting company it could be a 5 minute setup process.

**Comment by d07RiV** [comment]
I tried it before, couldn't find out how to do it without buying a service from my hosting.

Is it a big deal though? The login passwords are hashed on client side before being sent to the server, so it shouldn't cause any security issues.

**Comment by arturluizbr** [comment]
@d07RiV check up letsencrypt site, they offer ssl certs for free, and they are valid among all browsers.

**Comment by JTelcontar** [comment]
> Is it a big deal though? The login passwords are hashed on client side before being sent to the server, so it shouldn't cause any security issues, unless someone spoofs the site.

Whether it's a big deal or not is open to interpretation I think. If user #1 is on a public network (such as Starbucks or other free wifi), and another user is eavesdropping on user #1's network traffic, the eavesdropping user will see user #1's login submission. Maybe they end up seeing an email address/username with an associated encrypted password-- depending upon why they are eavesdropping, this might be enough to associate the info with user #1's account on another service (especially if that user has a really insecure password or is in a habit of using the same password everywhere). To this user, it could potentially be a big deal.

For most users who are at their home on their own WPA2 wifi-- probably not a big deal to them, since it is unlikely anyone is eavesdropping on their activity. But they may be more hesitant due to Chrome/Firefox/Safari (etc) bringing non-SSL connections into the forefront with new UI changes.

My recommendation would be to look into SSL again-- what host are you using?

**Comment by d07RiV** [comment]
Yeah they would see the login name, but the password is encrypted so its useless to the attacker, unless some other site happens to be using the same encryption (which is pretty much impossible since I append some garbage to it before hashing).

I'll look into it, back when I was first attempting it I only had shared hosting, now its on a VPS so I shouldn't have trouble adding it since I have root access.

**Comment by d07RiV** [comment]
Okay, everything seems to be working now.
