### ISSUE TITLE
Archon Combustion Explosion Not Adding Tal's Fire Stack in Simulations

### ISSUE THREAD

**Issue by Manson1716** [d07RiV/d3planner#204]
The Tal's-6/Vyr's-4 builds don't include any fire specific skills (usually Glacial Spike, BH-Spellsteal, Calamity and Archon) because the explosion from Combustion counts as fire and then the archon skills count as lightning from +lightning damage on bracers and/or neck.

Simulated DPS for this build seemed a little low and after zooming in on the rotation, it appears the fire stack is never applied.

**Comment by d07RiV** [comment]
So the explosion is always fire, regardless of what your highest element is?

**Comment by Manson1716** [comment]
The explosion always procs the fire stack of the Tal's 6-piece set bonus.  Whether or not it's actually "fire damage" I don't know for sure.  I would assume so, but that's a very unsafe assumption given the ridiculously convoluted bliz mechanics.

**Comment by d07RiV** [comment]
Fixed.
It seems that the explosion damage actually chooses the damage type based on your selected rune, but I'm going to take your word that it always triggers the fire stack.

**Comment by Manson1716** [comment]
Oh awesome thank you!  Can you just double check this for me to see if I set something up wrong?  https://www.d3planner.com/950293494  When running the simulator the fire stack still looks inactive.  This planner is a direct copy of the build used on the top solo boards just with the rolls adjusted to perfect.  Note the lightning damage on the bracers and lack of any fire damage skill with the exception of combustion.  I tried adjusting the range on the wizard too to see if the fire stack would show up if it were closer to the target (even though combustion does not need to hit to get the fire stack) and that didn't seem to work either.
