### ISSUE TITLE
Wand of Woh

### ISSUE THREAD

**Issue by Striferx84** [d07RiV/d3planner#207]
Wand of Woh has an attribute that says "Quadruple Explosive Blast"; which means 4 blasts. The actual Wand of Woh states 3 extra blasts; which should be "Triple Explosive Blast". Typo needs correction as well a verification on the calculating side of things to make sure it's being registered as x3 and not x4.

**Comment by AntoRod** [comment]
"3 additional Explosive Blasts are triggered after casting Explosive Blast" which means that you trigger the spell, and then the spell triggers 3 other times, so 4 times... i don't see where the spell trigger only 3 times...

**Comment by Striferx84** [comment]
I know what it means, that's the point of this post. In game the wand of woh description says 3 additional blasts granted by the wand. D3 planners description says 4 additional blasts granted -- see the issue now? D3 planner needs adjusting.

**Comment by d07RiV** [comment]
You mean the short legendary effect description? It makes your explosive blast hit 4 times instead of 1, hence the name. I highly doubt anyone would get misled by this.
