### ISSUE TITLE
Seismic Slam - Rumble Needs Update

### ISSUE THREAD

**Issue by FarlsBarkley** [d07RiV/d3planner#208]
The current rune for Seismic Slam - Rumble reads as follows:
"Expend all remaining Fury to cause the ground to shudder after the initial strike, damaging enemies in the area for 15% weapon damage for every point of Fury expended as Physical over 2 seconds."
The rune that is on the planner is the old rune.

**Comment by d07RiV** [comment]
You mean the tooltip text is outdated? I think the actual skill works correctly, as it has the Fury slider bar. I must've forgotten to update the tooltips (they're automatically generated so I don't usually look at them), fixing it now.
