### ISSUE TITLE
Signing Forgotten - always

### ISSUE THREAD

**Issue by Meat5000** [d07RiV/d3planner#211]
I can only sign in using the password reset form. Otherwise my information is "Not found". Even when Ive signed in, if I attempt to change my password I am greeted by the same message.

Password reset allows successful auto-login.

**Comment by d07RiV** [comment]
That's strange, what's your account name?

**Comment by Meat5000** [comment]
meat5000 is my username. If I use my email address it says its too long. Otherwise I get username/password not found.
 };-#)> Meat5000@yahoo.com 

    On Wednesday, May 17, 2017 11:04 AM, d07RiV <notifications@github.com> wrote:
 

 That's strange, what's your account name?—

**Comment by d07RiV** [comment]
Your username is just 'Meat', maybe you're typing in the wrong name?

**Comment by Meat5000** [comment]
What's odd about this is I never use just Meat... always Meat5000; but yes it seems you are right here.
 };-#)> Meat5000@yahoo.com 

    On Monday, May 22, 2017 10:17 AM, d07RiV <notifications@github.com> wrote:
 

 Your username is just 'Meat', maybe you're typing in the wrong name?—

**Comment by Meat5000** [comment]
Thank you. I figure the problem was not a coding issue of any kind. The issue may appear to be the switching of prompts between sign-up, sign-in and password reset with regard to the use of Username or Email. I suppose my brain has gotten used to a particular expectation when dealing with webforms of this kind and it somehow threw me off. As noone else seems to be having an issue it would seem I had simply gotten confused. Dumb-ass moment I guess; but my brain still tells me there's something to it, however the results would border on pedantry.
Kind Regards
 };-#)> Meat5000@yahoo.com 

    On Wednesday, June 14, 2017 10:10 PM, d07RiV <notifications@github.com> wrote:
 

 Closed #211.—
