### ISSUE TITLE
holy point shot / impale

### ISSUE THREAD

**Issue by slorange** [d07RiV/d3planner#213]
Holy Point Shot quiver picture missing.
Holy Point Shot damage multiplier not showing up under Impale damage in skill tab
Impale damage not showing dps scaling based on attack speed

**Comment by d07RiV** [comment]
I wasn't sure how the additional knives work. Does it actually increase single target DPS by 3x?

I'll need to add DPS I guess.

**Comment by slorange** [comment]
The first half of this video shows it pretty clearly:
https://www.youtube.com/watch?v=ruAwq5FfFjk

>

**Comment by d07RiV** [comment]
Done.
