### ISSUE TITLE
(Suggestion) New graph idea for the simulator

### ISSUE THREAD

**Issue by vert642** [d07RiV/d3planner#214]
Could it be possible to have a graph that would show damages according to different torment levels?

Like maybe have a difficulty option with all difficulties (It would maybe make the simulator more precise.) And maybe add a randomize option to get the simulation to be randomized each time we start it, so this way it's a bit more precise and right about what could happen in-game. ^^
You could also add another option for an amount of groups which would then make an average to show what the build would be like in some different scenarios.

(Sry if I didn't post this suggestion right, I'm not really used to Github much ^^'...)

**Comment by d07RiV** [comment]
What do you mean by different torment levels? I wanted to have a torment/GR tier dropdown next to the monster health slider, but the health amounts vary a LOT depending on monster type, and even the same monsters often have varying health pools.

I'll add a proper randomizer at some point, currently the simulation intentionally eliminates all randomness to make the results consistent when you change some pieces of gear, but it does have some side effects.

**Comment by vert642** [comment]
I meant to have an indicator on the side or an option to choose which torment level we'd like (GR would do as well as it would be more singnificative than those general torment tiers.)
It would be nice to have as the hitpoints and the damages varies depending on the Torment level we're in or the greater rift we're in as well.
It would greatly help in showing what those different builds can really do and whether they're good or not.

**Comment by d07RiV** [comment]
Maybe if I do another simulator rework, don't have that in plans right now.
