### ISSUE TITLE
D3planner some stats are not showing up.

### ISSUE THREAD

**Issue by Layne66** [d07RiV/d3planner#216]
![d3planner](https://cloud.githubusercontent.com/assets/28829938/26278659/012072fa-3d6e-11e7-8bda-2d8ebda8716a.png)

To be more specific, the stats such as "dps per 100 strength" and "toughness per 100 vitality" are missing and I can't figure out how to get them back. It's also missing the sheet dps, toughness, and recovery stats that are normally below the attributes.

**Comment by lordep** [comment]
It's true, please fix !

**Comment by d07RiV** [comment]
Oops, messed up in the last update. Fixed now.
