### ISSUE TITLE
Max wrath at wrong range

### ISSUE THREAD

**Issue by Layne66** [d07RiV/d3planner#217]
the planner currently only allows max wrath to be put at 8-10, but in game it's only allowed to roll a range of 6-7. I don't know if this only affects the Piro Marella or all crusader items.
![piro bug](https://cloud.githubusercontent.com/assets/28829938/26278839/06aa4f12-3d72-11e7-8ada-39f8e8b9d7ea.png)

**Comment by d07RiV** [comment]
Hmm that's strange, I'm pretty sure I checked it in-game a while ago. Maybe its due to Piro Marella being a crafted item?

**Comment by Layne66** [comment]
Yes I looked in my stash and found a Frydehr's Wrath that also rolls a 8-10, so it seems to be a piro marella specific issue.

**Comment by d07RiV** [comment]
Added exception for Pyro Marella
