### ISSUE TITLE
Distance influences dps output in simulate 

### ISSUE THREAD

**Issue by egesia** [d07RiV/d3planner#219]
Changing distance from 1 to 5 with melee abilities gives five different dps results

**Comment by d07RiV** [comment]
What ability/what enemy setup? I can't reproduce it for 1 target.

**Comment by egesia** [comment]
Sure, i am using roland shield bash/shield glare setup (https://www.d3planner.com/409737239), target is 1xboss and health NON adaptive (10,000,000,000,000,00). I am using non PTR version.
cheers

**Comment by d07RiV** [comment]
Uh did you put in the correct profile link?

I might have deleted it when cleaning up the database recently, but it should only affect profiles that haven't been accessed in several months. I'll check my backup tomorrow.
