### ISSUE TITLE
Max Essence on Reilena's Shadowhook is wrong

### ISSUE THREAD

**Issue by T1nyTim** [d07RiV/d3planner#223]
![reilena s shadowhook](https://user-images.githubusercontent.com/28727758/27769208-459445ba-5f79-11e7-9315-00ea70de1faf.png)

It's currently 30-36, should be 36-40

**Comment by d07RiV** [comment]
Okay so there's no difference between legendary and ancient for that stat? Fixing.

**Comment by d07RiV** [comment]
Fixed.
