### ISSUE TITLE
Necromancer - Bugs

### ISSUE THREAD

**Issue by wow-config** [d07RiV/d3planner#226]
[Ring]-[The Johnstone] Currently scales with each stack. It should function similarly to Pestilence P6

[Ring]-[Krysbin's Sentence] dev confirms that with S11 it will be fixed a Necromancer only ring (https://www.youtube.com/watch?v=AaS3BFmR1Aw&feature=youtu.be)

[Head]-[Mask of Scarlet Death] Missing scaling meter for Revive while this helmet is applied.

[Weapon]-[Bloodtide Blade] Scaling Meter is applied to the ability but should be applied to the item in case a player uses the [Iron Rose] without the ability itself but relies on proc.

[Rune]-[Satiated] Lacking a scale meter.

[Rune]-[Aura of Frailty] Currently display's a cost. Once it becomes an aura it is on all the time and has no cost.

[Ability]-[Simulacrum] Currently does not show up on scalings. Simulacrum's cast a clone of secondary skill's which double's the damage or triple's the damage if the Blood & Bone rune is selected. This also duplicate's the [Iron Rose]s Proc's.

[Ability]-[Skeletal Mage] You can currently have an indefinite amount on the scaling meter however the cap should be 10 as it is ingame.

Note: Skeletal Mage's should maybe display how many are summoned each time. the ring double's summons and simulacrum double's that which means with Blood & Bone you could summon 6 at a time.

[Passive]-[Draw Life] Currently does nothing. It is supposed to increase Life per second.

**Comment by d07RiV** [comment]
Krysbin's Sentence - class restrictions are currently pulled from the game data automatically  
Mask of Scarlet Death - Revive currently doesn't display any information, so there is no point in having a stack slider for it

**Comment by wow-config** [comment]
`Simulacrum - I'm assuming it also works with Bryner's Journey?`
I would strongly assume so.
`Skeletal Mage - don't really see the point in showing the number of summons per cast, it should be self explanatory imo. I am going to try to add a total damage indicator once I've figured out some of their mechanics, though.`
Still the lack of cap can be misleading to new players as blizzard sadly does not specify or describe mechanics. :) at the current moment one might assume that they can get more than 10 skeletons thus getting even more scaling From Rathma etc. there are even still the occasional forum question if ring increases cap.
`Mask of Scarlet Death - Revive currently doesn't display any information, so there is no point in having a stack slider for it`
True you have a point there, i will see if i cannot think up a method to get an estimate calculation of it's % damage.

Thinking something along the lines of taking off all gear except a grey weapon and testing on normal/hard etc.

I simply cannot fathom how often Blizzard developers make beginner mistakes... :/ stuff like dmg should be common sence to apply.
