### ISSUE TITLE
Necro Stone of Jordan bug

### ISSUE THREAD

**Issue by SirPhoenixKnight** [d07RiV/d3planner#228]
stone of Jordan just freaks out on necro.

doesnt have elite dmg - doesnt have essence - gets stuck with Arcane Power regeneration and usually cause D3planner to lock up as well.

![bandicam 2017-07-04 18-35-42-278](https://user-images.githubusercontent.com/29846249/27823313-d671610c-60e7-11e7-9d8e-4c1eec98aefb.jpg)

**Comment by d07RiV** [comment]
Fixed.
