### ISSUE TITLE
Bloodshard Page "Leoric's Crown"

### ISSUE THREAD

**Issue by Hurric4ne** [d07RiV/d3planner#229]
https://www.d3planner.com/game/kadala

"Leoric's Crown" shows the image of the "Broken Crown".
The CSS background-position is set to -0px, should **probably** be -216px
(yes, i peeked at your source code ;D )

**Comment by d07RiV** [comment]
Ye, the tooltip/icon generator for that thing is broken atm :|

**Comment by d07RiV** [comment]
Okay fixed.
