### ISSUE TITLE
Provoke - Cleanse

### ISSUE THREAD

**Issue by wow-config** [d07RiV/d3planner#233]
Missing Scale Meter

Currently has no scaling meter and displays no additional heal on hit in stats.

**Comment by d07RiV** [comment]
Does it actually get more than one stack? According to https://www.d3planner.com/powers/46006/X1_Crusader_Provoke max stacks is 1, but it might be unused.

**Comment by wow-config** [comment]
Yes i tested it yesterday and based on how many sorrounding me i got more or less the most common was 5-12 while the highest i had was close to 30. the number is shown in the corner of provoke while it's up and each new use overwrite's the old with new stacks.
