### ISSUE TITLE
Consecration

### ISSUE THREAD

**Issue by wow-config** [d07RiV/d3planner#235]
Currently you cannot Include Consecratioin in stats.

It grants Life per second.

**Comment by wow-config** [comment]
Hmm i will double test this  just to be sure using the Death's Bargain leggings to see if it is added to your stat or if it seperately heals.

**Comment by d07RiV** [comment]
Yeah I think I assumed that all these effects are actually healing and not regen. If they show up in character sheet as life regen then I suppose I'll add them.

**Comment by wow-config** [comment]
Tested and it is indeed more of a heal than an addition. Was kinda confused on how they worded it but i guess thats blizzard for ya XD
