### ISSUE TITLE
Invoker set P6

### ISSUE THREAD

**Issue by wow-config** [d07RiV/d3planner#238]
Currently Simplicity's Strength & Depth Digger's Increase both thorn and normal damage of your primary skill however after testing it turns out these only increase the ability's own damage and not the thorn's added from the 8 set bonus.

**Comment by MarioVX** [comment]
Just tested it myself & can confirm. Furthermore, the damage *is* affected by Physical skill damage % in game, but not in d3planner.

**Comment by wow-config** [comment]
I assume you mean skill triggered thorns mariovx or does the P8 thorns scale with physical too ?

**Comment by MarioVX** [comment]
not sure what you mean with P8. I meant the Invoker set 6pc bonus, 800% thorns applied on each Punish/Slash attack. It scales with physical.

**Comment by wow-config** [comment]
ah yeah sorry i meant P6 ^^
But that certainly is rather interesting indeed.

**Comment by d07RiV** [comment]
What about +Punish/Slash% damage? I'm assuming they're also not applied, since depth diggers/simplicity bonuses are directly added to those in the stats panel.

**Comment by MarioVX** [comment]
Correct. In game, skill damage % doesn't affect the thorns portion either. Neither does Vo'Toyias Spiker & Provoke combo (it only affects Invoker 2pc and Hack, not 6pc).

**Comment by d07RiV** [comment]
What about multiplicative bonuses that affect punish/slash?

**Comment by MarioVX** [comment]
> What about multiplicative bonuses that affect punish/slash?

As wow-config said, Depth Diggers & Simplicity's Strength don't affect them in game. Which other multiplicative bonuses do you have in mind?

General multipliers like Endless Walk, Bastions of Will, Convention of the Elements, Bane of the Trapped do work as intended.

However I found one more thing, **Holy Cause** (the passive). Tested this in game as well, it does not affect any Thorns damage (neither Invoker 2pc, nor 6pc, nor Hack, Bombardment - Barrels of Spikes, nothing). It's actually consistent with the tooltip explicitly reading "damage dealt by your weapon".
