### ISSUE TITLE
Omryn's Chain not working in simulator

### ISSUE THREAD

**Issue by Balorlord** [d07RiV/d3planner#239]
The Demon Hunter belt [Omryn's Chain] drops caltrops when using vault, but the simulator does not register this effect

Look at this simulate tab: https://www.d3planner.com/312776818

Vault should be summoning caltrops that deal damage and slow, but the simulator comes up empty

**Comment by d07RiV** [comment]
How many caltrops does it create? Do they function identically to regular caltrops?
