### ISSUE TITLE
[D3Planner] Missing damage reduction

### ISSUE THREAD

**Issue by tsukiyo92** [d07RiV/d3planner#24]
I found that the newly added monk skill {Blinding Flash - Crippling Light} damage reduction isn't included, there is also no option for it to be included. Choosing this rune offers no increase in toughness. Thanks

**Comment by d07RiV** [comment]
It makes enemies deal reduced damage, and doesn't increase your toughness. All such effects currently aren't displayed anywhere, as they do not directly affect your character.
