### ISSUE TITLE
Etched Sigil item effect not working

### ISSUE THREAD

**Issue by jpovoas** [d07RiV/d3planner#242]
The [Etched Sigil](https://us.battle.net/d3/en/item/etched-sigil) effect is not been listed on the Item Effects List, neither is working on the simulator.

Here's a [Test Build](https://www.d3planner.com/346787564) that presents the problem.

**Comment by d07RiV** [comment]
Hmm it *should* work, or at least it worked before. I'll look into it.

**Comment by jpovoas** [comment]
Wow, I didn't realise that... It really is working...
