### ISSUE TITLE
Fetish Darts

### ISSUE THREAD

**Issue by iamleejn** [d07RiV/d3planner#243]
Fetish darts (i.e. Dagger of Darts legendary effect) are not scaling with elemental damage. Dart damage does scale with Mask of Jeram. Other types of Fetish damage (Sycophants, Fetish Army, etc.) are correctly using elemental damage.

**Comment by d07RiV** [comment]
According to https://us.battle.net/forums/en/d3/topic/13349475072

Fetish darts always deal poison damage, no matter the element of your dart skill, or the element of your army/sycophants. Did any of that change?
