### ISSUE TITLE
Corpse Lance DPS

### ISSUE THREAD

**Issue by slorange** [d07RiV/d3planner#248]
It would be nice to have a field for DPS under the Corpse Lance skill to take attack speed and breakpoints into account.
(There are probably many skills where this is the case)

**Comment by d07RiV** [comment]
I don't know how many corpses it consumes with each use, though - it's not mentioned everywhere. I'd assume 5, but need to make sure. Besides, wouldn't the DPS only make sense during land of the dead, since you'll run out of corpses very quickly otherwise?

**Comment by slorange** [comment]
I thought it was just one corpse per lance, but with land of the dead it
doesn't really matter which is currently the top build for solo GR in the
game.

**Comment by d07RiV** [comment]
Doesn't it throw more than one lance per cast, though? I played around with the build and lances were flying everywhere.

**Comment by slorange** [comment]
You get the bonus lance from the Corpse Lance rune but that's already
implemented in the simulator

**Comment by ringo196** [comment]
+1 this suggestion. I'm currently pulling using several tabs of calculators to compare builds, which is very tedious and sometimes adds confusion. 

This analysis shows how many corpses are used per breakpoint in one of the tables below. 

https://www.reddit.com/r/Diablo/comments/6nof0m/an_indepth_analysis_and_guide_on_tragouls_corpse/

**Comment by d07RiV** [comment]
Ah gotcha, this makes sense now. Added DPS/breakpoint table.
