### ISSUE TITLE
Can not delete saved skill priority settings from Simulate page

### ISSUE THREAD

**Issue by mikran** [d07RiV/d3planner#25]
As shown in this image the trash bin and disk icons are shown on top of date and these can not be clicked. I tried with firefox and chrome and same issue with both browsers.

![bug](https://cloud.githubusercontent.com/assets/820244/12909162/d1508406-cf06-11e5-9dd3-c77cb68a3e2a.png)

**Comment by plopinou** [comment]
The date is over the icons, so for the time being I just right click inspect on it, and disable the width: 0 in the css rule '.search-results li .date-saved'.

**Comment by d07RiV** [comment]
Ah the width:0 is there so it doesn't cover the preset name if its too long, there's supposed to be another <span> which I forgot to add.
