### ISSUE TITLE
Manald Heal & Lightning skill damage %

### ISSUE THREAD

**Issue by MarioVX** [d07RiV/d3planner#251]
The most recent credible testing source I could find is [this](https://us.battle.net/forums/en/d3/topic/20752649109). Neither the 2.5.0 nor 2.6.0 patch notes that happened since then stated anything about a change for MH to be affected by Lightning skill damage % now.

So it's safe to assume Manald Heal's damage is still not affected by skill damage % in game, and it being included in d3planner's calculation is an error.

**Comment by ArchonFine** [comment]
I created an account just to confirm this bug, it's kinda big as wizards are one of the most if not the most popular class among experienced players

**Comment by d07RiV** [comment]
Ah yes I didn't think it would be that big of an issue but I see I'm wrong. It is kinda difficult to separate all these damage buffs specifically for that one item but guess I'll have to try.
