### ISSUE TITLE
WD - Locust Swarm disapear after 20 seconds with Creeping Death

### ISSUE THREAD

**Issue by Nemesis666first** [d07RiV/d3planner#253]
Hi Riv,

It seems that there are a bug with the passive Creeping Death of the WD and the skill Locust Swarm.

Lucust Swarm must last "almost forever", but it disapear after only 20 seconds.

Can you check that plz :D !

<3

**Comment by d07RiV** [comment]
Can't reproduce, do you have a link to your simulation?

**Comment by Nemesis666first** [comment]
For exemple on this one :

https://www.d3planner.com/604655628

In the skill priority, you can see that Locust Swarm is cast only when Locus Swarm is not on the target, but the spell is cast 25 times in 10 minutes, that's impossible.

**Comment by d07RiV** [comment]
Ah, I see. As far as I know, Jade actually removes the remaining duration to deal damage, so since your DOTs last 30 minutes with creeping death and quetzalcoatl, after casting soul harvest 6 times they will expire.

**Comment by Nemesis666first** [comment]
Ha...

**Comment by Nemesis666first** [comment]
Hmmmm I have an other question :

With the Jade set 2/6, Creeping Death seems to augment damage of Haunt and Locust Swarm (about ~+15%), is it normal ?

**Comment by d07RiV** [comment]
Dunno, maybe they sometimes expire without the passive, so you miss out on some 2pc procs?

**Comment by Nemesis666first** [comment]
I dont know.
Thx you for your help by the way ;) .

You can clote it :) !
