### ISSUE TITLE
DH - Spike Trap never explode

### ISSUE THREAD

**Issue by Nemesis666first** [d07RiV/d3planner#254]
Hi Riv ;) !

I figured out Spike Trap never explode, can you fix it plz ?

Thx :p !

**Comment by d07RiV** [comment]
Works fine for me. What simulation are you using?

**Comment by Nemesis666first** [comment]
Okay I figured out Spike Trap is not one of the spell needed that can "activate" other Spike Trap.

> Lay a trap that remains dormant until **another** Hatred spender is used to detonate the trap

Thx you and forget this thread :D !
