### ISSUE TITLE
Necromancer:  Skeletal Mage - Singularity DPS Calculation

### ISSUE THREAD

**Issue by Manson1716** [d07RiV/d3planner#259]
The attack speed breakpoints and DPS calculation for Singularity mages is inaccurate.  Recent testing from several sources has shown that they have a default attack speed of 2 and if using Taskers the attack speed is 3.  There are no other breakpoints.  Attack speed from the Necro increases the damage of the mages attacks.  Including some links for further information:

https://us.battle.net/forums/en/d3/topic/20757706310?page=6#post-115
https://us.battle.net/forums/en/d3/topic/20757706310?page=6#post-116
https://us.battle.net/forums/en/d3/topic/20757706310?page=6#post-119

**Comment by d07RiV** [comment]
Fixed, assuming it applies to all skeletal mages.
