### ISSUE TITLE
Necromancer : Bones of Rathma Bonus

### ISSUE THREAD

**Issue by AronDIII** [d07RiV/d3planner#260]
If you select a T6 of Rathma, the bonus apply to Skill DPS is too strong,  the T6 bonus say 250% / Skeletal Mage :
0x Skeletal Mage : 0
1x Skeletal Mage : 625%
2x Skeletal Mage : 1250%
3x Skeletal Mage : 1875%
4x Skeletal Mage : 2500%
5x and More Skeletal Mage : 2500%

The Max seems OK ( 250% x max 10 Skeletal )

**Comment by AronDIII** [comment]
Maybe there : data/item_special.js - line 1368
set_rathma_6pc: {
(...)
        var amount = Math.min(2500, 625 * DiabloCalc.skills.necromancer.skeletalmage.params[0].val);

Maybe changing 625 to 250 ?

**Comment by d07RiV** [comment]
> Each active Skeletal Mage increases the damage of your minions and Army of the Dead by 625% up to a max of 2500%.
