### ISSUE TITLE
Can't raise base armor?

### ISSUE THREAD

**Issue by stayupthetree** [d07RiV/d3planner#261]
Trying to input my Necromancer. I have Rathma's Spikes(Set Shoulders) with 995 Armor. D3Planner won't let me go past 674 for Base Armor. I assume I am doing something wrong.

**Comment by wow-config** [comment]
If you wish for an item to exceed its default/capped armor you will need to add the [Armor] stat ;)

**Comment by d07RiV** [comment]
As mentioned, the armor shown in-game is the sum of base armor and the bonus armor roll, if there is one.

**Comment by symmetriq** [comment]
I just got Ancient Bakuli Jungle Wraps. According to D3 planner the max base armor is 506, but the item has 590, and does not have any bonus armor. I don't know what the max is, but it's clearly not 506.
