### ISSUE TITLE
Custom PTR Change's

### ISSUE THREAD

**Issue by wow-config** [d07RiV/d3planner#263]
I know for you to make all PTR changes is [Impossible/Unreasonable] and thus i had an interresting thought.

How about allowing players to modify legendary affixes, with this i do not mean come up with entirely new functions as that requires new coding however instead allow the percentage or number associated with it to be modified beyond the limit's however once an item is outside the normal scope it is colored or marked in a color or [ptr] [test] or [custom] etc.

the same should be applicable for set bonuses.

This allows players to test how most ptr changes would affect them but i am also of the belief that the latest PTR changes are entirely thanks to your d3planner.com as otherwise they might not have made such ptr. Perhaps blizzard only has a half arsed simulator/planner and in secret began relying on yours ?

**Comment by d07RiV** [comment]
Seems too complicated.. it might work for some of the new legendaries, but most of them add a damage multiplier where previously there was none, or change additive skill damage to a new multiplier.

I'll just add all the new items by hand, as usual.

**Comment by wow-config** [comment]
oh well not all suggestions can make it but i am glad you went through my idea and even considered it 👍
