### ISSUE TITLE
swami should give armor and all res with 4 piece vyr

### ISSUE THREAD

**Issue by slorange** [d07RiV/d3planner#264]
Attack speed and damage working properly for swami.
Armor/allres is missing.

**Comment by slorange** [comment]
item_special.js lines 789 790
res.armor_percent += stacks * 1.0;
res.resist_percent += stacks * 1.0;
should that be += or just =
I'm not too familiar with python so I don't know if it sets vars to 0 by default. In other places in this file where += is used, count is initialized to 0 first so maybe that's the issue.

**Comment by d07RiV** [comment]
Thanks, fixed.
