### ISSUE TITLE
D3planner PTR 2.6.1 when ?

### ISSUE THREAD

**Issue by lordep** [d07RiV/d3planner#265]
When can we expect the release of D3Planner PTR 2.6.1 ? Thanks.

**Comment by d07RiV** [comment]
I'll try to get it up soon, thanks for the reminder.

**Comment by d07RiV** [comment]
Should be up now.

**Comment by lordep** [comment]
Thanks! Wait for Sets update 👍

**Comment by d07RiV** [comment]
Oh! Whoops.

**Comment by d07RiV** [comment]
Okay done that too.
