### ISSUE TITLE
Not able to upload using my Gamertag. 

### ISSUE THREAD

**Issue by DamagingHades** [d07RiV/d3planner#266]
I put my gamertag in the upload section and it says account not found.

**Comment by d07RiV** [comment]
Not sure if I can help without knowing your tag. If you don't want to post it here, you can email me at d07.riv@gmail.com

Or you can check if your profile is visible on battle.net in the first place:  
eu.battle.net/d3/en/BATTLETAG-1234/  
us.battle.net/d3/en/BATTLETAG-1234/
