### ISSUE TITLE
Zunimassa DR

### ISSUE THREAD

**Issue by shialinn** [d07RiV/d3planner#269]
Hi!
I tried to compare Zuni and HT with PTR version and noticed that damage reduction of Zuni 4pc is calculated with 2% per fetish in the Defence section.

Item Effects (middle)
...
Zunimassa's Haunt – 4 pieces
Include in stats
    Damage Reduction: 69%

Defense (right)
Armor8,949
...
Damage Reduction 46.00%.

Same trouble is on live version too.
![default](https://user-images.githubusercontent.com/32094856/30588296-5e3c53f8-9d60-11e7-9e94-0aa5c23319d2.png)

**Comment by d07RiV** [comment]
Fixed.
