### ISSUE TITLE
Implements Remorseless (data inside)

### ISSUE THREAD

**Issue by plopinou** [d07RiV/d3planner#27]
I tested some stuff with CotA, especially on a single target boss, and saw that Remorseless wasn't implemented (with an orange message).

So I suspected that it was because of a lack of data on it for this patch.
I had some free time this evening, so I tested it thoroughly.

Here is the data.

### Preliminary note :
- Except for the CotA damage bonus "bug", everything below is also applicable to the "normal" ancients you cast (I checked that this was the case for the majority of the cases).
- Every single one of the following test were done using the ancients specifically spawned from Remorseless.

### Generalities :
- max 3 ancients spawned, but the high proc make them nearly perma up
- you do not need to hit a target to proc them
- unequipping the weapon make them despawn
- does not take into account your selected cota rune, so they always are equivalent to the no rune skill, and use the physical element
- they have the same base damage as the default ones from the CotA skill

### Buff/Debuff :
- affected by DIBS
- affected by bonus elite damage
- affected by your physical damage bonus (Physical skill deal XX% more damage.)
- **not affected by cota damage bonus (Increases Call of the Ancients Damage by XX%)** <-- probably a bug, opened an issue on the official forum
- affected by attack speed (including Tasker and Theo), didn't check if the breakpoints where the same, but that would be odd if it weren't
- affected by debuff on the mobs that are part of DIBS (like Strongarm Bracers)
- affected by bonus damage like WotB Insanity
- affected by focus and restraint (checked both separated and together)
- affected by Mantle of Channeling if you WW while they dps
- benefit from the Oculus Ring circle buff, whether it's you standing in it or them (does not double dip)
-> probably any other damage bonus, didn't test every single thing

### Procs :
- do not seem to trigger any "on hit" or "on crit" effect like life on hit/Battle Rage Bloodshed/WotB Slaughter/weapons procs
- **proc Area Damage** (Yeah !)
- do not proc Strongarm Bracers themselves
- proc the Oculus Ring circle buff if they kill a target

### Legendary gems :
- affected by legendary gem Enforcer
- affected by Bane of the Trapped. This one is in fact a bit more complex, see below.
- not affected by Zei's Stone of Vengeance in any way
- proc Pain Enhancer if they crit
- proc Gem of the Efficacious Toxin and benefit from its debuff
- do not proc Wreath of Lightning effect (because it's an "on hit" trigger)
- dot not proc Bane of the Stricken stacks, but benefit from its stacking effect. Particularity : they do not benefit from the secondary +25% damage until you hit the boss at least once (same thing for the normal skill ancients)

**_Note on Bane of the Trapped :_**
In theory, you'd believe that you'd need to be in the small 15y range of the mobs they are hitting for them to benefit from it, or at least cc the mobs with something like charge/ground stomp/etc..
The good news is that you don't. From what I've tested, even on mobs 40 yards away, they are benefiting from it.
Well, not exactly...
This needs further testing, but it doesn't seem to be 100% up.
Firstly, my belief was that they are proccing it by cc'ing the mobs themselves, and because it's often the case, the majority of the time it's up.
So to be sure, I checked on a boss without a single add, and... I found the same thing.
When I'm near the boss, they are benefiting from it 100% the time, that point is sure. But from far away, it seems up and down, more up than down.
So there might be the possibility that their own cc procs BotT, even if it doesn't affect bosses, as the BotT self debuff does.
The other possibility is that I didn't test it well enough and it's up 100% of the time, because it's hard to be sure when they deal so much damage with a wide range.
Anyway this is very good news.

... and that's all.

If someone has more input or want to know if they're affected by something specific, they're welcome to post.

N.B. I didn't search if someone already did those check before; probably yes, but at least those info are up to date in the patch 2.4

**Comment by d07RiV** [comment]
Sounds simple enough, except for the area damage part. Do any other pets proc area damage now?

**Comment by dominiklohmann** [comment]
> Do any other pets proc area damage now?
They all do, it was in the patch notes for 2.3 I think (the patch where nobody knew what worked and what didn't with Area Damage) and as of 2.4 this behaviour seems to be consistent.

**Comment by plopinou** [comment]
Thanks !
