### ISSUE TITLE
Wand of Woh (PTR) can't be simulated

### ISSUE THREAD

**Issue by steinwall** [d07RiV/d3planner#272]
With Wand of Woh (PTR) either equiped or in Kanai's Cube simulation will not start (only shows DPS: 0, no chart).
I have tried multiple combinations of skills and skill priorities, all with the same result.

Build with this issue if there is a combination of skills/items causing this:
https://ptr.d3planner.com/196905446

**Comment by d07RiV** [comment]
Fixed. Nice strength gems btw :^)
