### ISSUE TITLE
Not showing right Attacks Per Second on The Barber

### ISSUE THREAD

**Issue by MeGustabo** [d07RiV/d3planner#273]
In game my The Barber have 1.61 Attacks Per Second with 7% attack speed rolled on it, but in D3planner it says it only have 1.50. 
This makes it a bit hard to calculate how much attack speed i need to get for maximum damage output.

**Comment by dominiklohmann** [comment]
The Barber itself only has an attack speed of `1.50`. The game does show weapon attack speed factored in the `1.61` it shows, which makes sense because `1.5 * 1.07 = 1.605`.

Note that attack speed rolls on weapons are a different multiplier from all other attack speed rolls.

**Comment by MeGustabo** [comment]
I took another look at it today, and tried creating a blank set in D3planner with only The Barber equipped. If i do that and don't add attacks speed, i only have 1.40 Attacks Per Second and not 1.50 as i should have. If i add the attack speed, it goes up to 1.50, which makes sense when doing the math.

**Comment by d07RiV** [comment]
Okay I see the problem. Barber is now a ceremonial knife, which *should* have 1.4 attack speed. Is it actually 1.5 ingame, and does the character sheet show the same? That would seem to be a bug on Blizzard's end, because weapon stats should be defined by its item type

**Comment by Lothrik** [comment]
The Barber is only available as a Ceremonial Knife now. Any dagger versions are legacy items from pre-2.5.0. New copies of The Barber have the base attack speed and base damage of a Dagger, but all non-base stats use Ceremonial Knife values.

https://i.imgur.com/RXQPDqJ.png
