### ISSUE TITLE
Cannot get password recovery email.

### ISSUE THREAD

**Issue by Praelanthor** [d07RiV/d3planner#274]
I've lost the acess to my account and when I try the recovery it says that a password reset link was sent but when I check my email there's nothing.

**Comment by d07RiV** [comment]
What's your username?

**Comment by Praelanthor** [comment]
I think it is "Praelanthor". The same name I've used in this account.

**Comment by d07RiV** [comment]
I just manually sent you an e-mail with the recovery code. If you received it, click "Sign in" -> "Lost password" -> "Already have code" and enter it.

**Comment by Praelanthor** [comment]
Thanks for the reply, it worked and the issue is solved by now. Why I'm unable to get the recovery code by the site tool?

**Comment by d07RiV** [comment]
No idea, maybe the email got lost in spam filters. It generated a reset
code and everything, so I just copied it from the database for you.
