### ISSUE TITLE
PTR 2.6.1 update

### ISSUE THREAD

**Issue by lordep** [d07RiV/d3planner#275]
Please update PTR D3planner for last changes https://us.battle.net/d3/en/blog/20976068/patch-261-ptr-patch-notes-8-15-2017 .

P.S. Something's wrong with calculating skill Heaven's Fury (rune Fires of Heaven) - Crusader.

**Comment by d07RiV** [comment]
Done. I couldn't find any problems with Heaven's Fury, please create a separate issue if you can reproduce it.

**Comment by lordep** [comment]
Heaven's Fury (rune Blessed Ground) https://ptr.d3planner.com/225233718 (Damage:  579,744,074,949)
_Change rune_ Heaven's Fury (rune Fires of Heaven) https://ptr.d3planner.com/110629662 (no damage).
