### ISSUE TITLE
Tal Rasha 6 set extends are not working right

### ISSUE THREAD

**Issue by ultimaaaaa** [d07RiV/d3planner#28]
When simulating i lose the 6 set buff when i shouldn't. So when using tals 6 set set on the current version the way it works is, you have to use 4 different elements to build up to 4 stacks of tals 6 set, once the 4 stacks are achieved you only have to rotate 2 elements every 8 seconds to keep it up permanently. You dont have to cycle all the elements again to keep up the extends.

**Comment by d07RiV** [comment]
Ah I was confused about the wording. What does this mean?

> At 4 stacks, each different elemental attack extends the duration by 2 seconds, up to a maximum of 8 seconds.

I thought that would mean that you can only extend the buff for 8 seconds, before it drops? How does it work then?

**Comment by dominiklohmann** [comment]
After you reached 4 stacks, you can extend the duration of the 4 stacks to 8 seconds by using an attack that works for TR 6pc, but was not the last attack that added a stack or refreshed it. So you really only have to alternate 2 skills every 8 seconds, or - in practice - spam the attack you deal damage with and use another attack at least every 8 seconds.

**Comment by d07RiV** [comment]
Ah I see. Do you have to alternate between any two attacks or do they have to be of a different element?

**Comment by dominiklohmann** [comment]
They have to be of a different element, and need to be attacks that can proc TR 6pc. That's why many people have been running Teleport: Calamity or Frost Nova: Frozen Mist, while these skills have other runes that are a lot better.

**Comment by d07RiV** [comment]
Yeah I know you had to run Calamity/Frozen Mist before (played TR a lot in S3), so they didn't change that in 2.4?

**Comment by dominiklohmann** [comment]
Nope, not changed at all. Extending the 6pc does not also extend the 4pc btw.

**Comment by d07RiV** [comment]
Yeah 4pc seems pretty straightforward I guess.

Still a bit confused on the wording:

> At 4 stacks, each different elemental attack extends the duration by 2 seconds, up to a maximum of 8 seconds.

You're saying it refreshes the buff to 8 seconds, so you only have to use the alternate attack once every 8 seconds. Where do the 2 seconds mentioned come into play, then?

**Comment by dominiklohmann** [comment]
That was supposed to be 4 seconds, my bad.
