### ISSUE TITLE
Nercomant/Skelet Mage - [Ru]

### ISSUE THREAD

**Issue by KlipDe** [d07RiV/d3planner#280]
Breakpoint - bag or error 
https://www.d3planner.com/351824991 
+Attack speed > dps Skelet Mage. Breakpoint 24 always
+Attack speed = dps Command Skeletons. Breakpoint 24 always

При увеличение скорости атаки увеличивается дпс у скелет магов. хотя брэйк поинт не меняется. А у обычных скелетов не увеличивается. так же и у дх увеличивается только при смене брэйкпоинта. В чём ошибка?

**Comment by d07RiV** [comment]
Тестирование показало, что скорость атаки скелетов магов не зависит от скорости атаки персонажа, а вместо этого меняется их урон (при этом перчатки Таскер могут менять скорость атаки).

Подобная механика используется, например, для фетишистов ВД. У других прислужников, наоборот, меняется скорость атаки. Я не уверен про обычных скелетов, вроде никто не проводил подробных тестов для них.
