### ISSUE TITLE
Attack Speed Increase does not take any On-Hand weapons into account

### ISSUE THREAD

**Issue by StarseedLure** [d07RiV/d3planner#286]
This is for Demon Hunter. I tried a couple of weapons from each category (1-handed, 2-handed, bows, melee weapons, etc.). None of them, when provided with an attack speed increase, affect the totals column.

Off-Hand weapons are accounted for correctly.

**Comment by dominiklohmann** [comment]
The behaviour of d3planner is correct here. Attack speed on weapons behaves different than attack speed on any other item slot: It is a separate multiplier.

**Comment by StarseedLure** [comment]
I had no idea! So +%aspd is similar to +%dmg on the weapon, in that the % bonus on the weapon stacks multiplicatively with all the [otherwise additive] bonuses on other gear?

**Comment by dominiklohmann** [comment]
Yes. Assuming you use a weapon with 1.4 base APS, have +7% weapon attack speed bonus and three items with +7% attack speed bonus each, your total APS would be calculated like this:

`1.4 * (1 + 0.07) * (1+ 0.07 + 0.07 + 0.07) ≈ 1.81`

**Comment by StarseedLure** [comment]
Thanks, this is good to know!
