### ISSUE TITLE
DH's passive ballistics not adding damage

### ISSUE THREAD

**Issue by Neaco** [d07RiV/d3planner#291]
Hi, when picking the dh's passive ballistics, the simulated damage stays the same.
I used this profile : https://www.d3planner.com/814905925. 
Take another non damge talent instead of ballistics and the simulation will give the same result.

Regards

**Comment by Neaco** [comment]
Same problem with fire damage on amulet not doing anything.

**Comment by d07RiV** [comment]
You haven't specified any priority (rotation), so the simulation is just your companion biting enemies to death.

Here's a fixed profile: https://www.d3planner.com/915926922

**Comment by Neaco** [comment]
I forgot I had to pick one..
Sorry for the disturbance and thanks for the quick answer
