### ISSUE TITLE
DH UE Damage Calculation Not including max essence

### ISSUE THREAD

**Issue by luckyremains** [d07RiV/d3planner#292]
Currently when you sim a demon hunter wearing 6 piece unhallowed essence, there is no damage multiplier based on your current maximum essence.  In the damage calculation it just says 60% from UE...
It should be 100% per point of max essence currently.

**Comment by d07RiV** [comment]
There should be two separate bonuses from UE in the list:

![image](https://user-images.githubusercontent.com/3448203/32915667-b53a644a-cb2a-11e7-8787-67e5b8e86768.png)
