### ISSUE TITLE
Disappearing Saves

### ISSUE THREAD

**Issue by GinaViVi** [d07RiV/d3planner#294]
i bookmarked a bunch of saved builds and when i went to go look at the today the were all gone and reset the the default page. i don't understand what's going on and i am not happy that all my hard work is just gone like that. what's worse is that i can't event make an account with your website to save any new builds i might make in the future. can you please help me with this, or at least explain what is going on?

**Comment by d07RiV** [comment]
I had to restart the server after it was having some issues, everything should be working now.

**Comment by Zeus2403** [comment]
when I go to the build link there is nothing

**Comment by d07RiV** [comment]
Sorry, was having some server issues lately. I disabled some of the more resource consuming stuff on the server side, hopefully it will become more stable.
