### ISSUE TITLE
Maltorius' Petrified Spike multiplies incorrectly

### ISSUE THREAD

**Issue by Binkenstein** [d07RiV/d3planner#295]
Damage calculations for Bone Spear show Maltorius as a separate 700% multiplier, but the in-game details show it being part of the Bone Spear damage bonus (ie: 729% bonus damage vs 29% bonus damage multiplied with a 700% damage bonus)

**Comment by d07RiV** [comment]
Oh that's weird, do you think that's intended?

**Comment by Binkenstein** [comment]
I would imagine it's intended, if other similarly worded abilities work the same way.
