### ISSUE TITLE
Bracers of the First Men attack speed bonus not affecting Hammer of the Ancients

### ISSUE THREAD

**Issue by swmeaney** [d07RiV/d3planner#297]
The Bracers of the First Men should provide a 50% attack speed bonus to the Hammer of the Ancients skill, but that is not occurring on D3Planner.  Note: this was working correctly on the PTR version of D3Planner before 2.6.1 went live.

See attached screenshots showing the attack speed/breakpoints being unaffected by the item:

![image](https://user-images.githubusercontent.com/14301069/33328848-17696d30-d429-11e7-9248-e6a8cff4a769.png)
![image](https://user-images.githubusercontent.com/14301069/33328857-1d761a8e-d429-11e7-8536-b715a928b15e.png)

**Comment by d07RiV** [comment]
Fixed.

**Comment by swmeaney** [comment]
Thanks.
Unfortunately, now the Breakpoint tooltip is showing information as though you are one breakpoint ahead of what you should be.  Specifically, the Next Breakpoint info is actually for two breakpoints ahead, the Previous Breakpoint info is actually for the current breakpoint (as can be seen by it being a positive ASI number instead of negative, with +0% DPS), and the highlighted info in the table is for the next breakpoint instead of the current one.
This appears to only be an issue with the barbarian class, but it affects all barbarian skills, whether or not Bracers of the First Men is equipped.

See attached screenshot with tooltip info for the 19 frames breakpoint even though the current breakpoint is 20 frames:
![image](https://user-images.githubusercontent.com/14301069/33396843-ca95dda0-d517-11e7-949a-68634ecf3d0a.png)
