### ISSUE TITLE
WRAPS OF CLARITY

### ISSUE THREAD

**Issue by Deathnought** [d07RiV/d3planner#298]
Dear Team,
Please update the item Wraps of Clarify. The maximum dex is reduced to 421. This number doesn't increase nor for Ancient or Primal Ancient type of item. I found this issue when trying to optimize my DH.
Please fix it, so I can use the site properly.
Thank you in advance.

**Comment by d07RiV** [comment]
Do you actually have an ancient Wraps of Clarity with 421 dex? Are you sure it is a level 70 item?
