### ISSUE TITLE
Stone of Jordan - maximum Fury

### ISSUE THREAD

**Issue by Hurric4ne** [d07RiV/d3planner#299]
Stone of Jordan (ancient and normal) has 7-8 max. fury, not 10-12.

Noticed it when checking the perfection% of mine and it "said" -150%.

**Comment by d07RiV** [comment]
Ok yeah, 10-12 is definitely wrong, but the correct value seems to be 8-10, not 7-8 (at level 70), according to datamine:

https://www.d3planner.com/game/items#Unique_Ring_019_x1

**Comment by Hurric4ne** [comment]
i have both ingame. https://imgur.com/a/UiRQs

**Comment by d07RiV** [comment]
Okay did some more research and it appears SoJ always uses level 60 values for max resource.
