### ISSUE TITLE
Barbarian attack speed breakpoints off by one

### ISSUE THREAD

**Issue by swmeaney** [d07RiV/d3planner#300]
The Breakpoint tooltip is showing information as though you are one breakpoint ahead of what you should be. Specifically, the Next Breakpoint info is actually for two breakpoints ahead, the Previous Breakpoint info is actually for the current breakpoint (as can be seen by it being a positive ASI number instead of negative, with +0% DPS), and the highlighted info in the table is for the next breakpoint instead of the current one.
This appears to only be an issue with the barbarian class, but it affects all barbarian skills.
Note, this issue appeared when Issue #297 was fixed (I responded to that ticket instead of making a new one like I should have). 

See attached screenshot with tooltip info for the 19 frames breakpoint even though the current breakpoint is 20 frames:
![image](https://user-images.githubusercontent.com/14301069/33720154-0aaf05be-db31-11e7-9a47-0eead4f35ccf.png)

**Comment by d07RiV** [comment]
Fixed. Congrats on bug #300!
