### ISSUE TITLE
jewelry sockets

### ISSUE THREAD

**Issue by iThinkiWin** [d07RiV/d3planner#309]
![image](https://user-images.githubusercontent.com/12555368/36350711-ad9b3de8-146a-11e8-847a-059028c7cbfb.png)
Recently when importing sockets on rings and amulets fail to get added.

**Comment by d07RiV** [comment]
The new blizzard API does not list empty sockets correctly so there isn't much I can do about it.

**Comment by iThinkiWin** [comment]
ah good ol bliz braking things that dont need fixing 🤣
