### ISSUE TITLE
Waist "Blessed of Haull" look like he doesnt work with Justice (=> Blessed Hammer dont appear)

### ISSUE THREAD

**Issue by Nemesis666first** [d07RiV/d3planner#31]
All is in the title, I guess.

**Comment by d07RiV** [comment]
You mean it doesn't show hammer damage in the main planner? I guess I could add it if that's an issue.

It should work in the simulator, though.

**Comment by Nemesis666first** [comment]
I tryed it on Live, and I'm sad that Zodiak dont proc on the Hammer hit :'( ...
So, pay attention that the simulator dont make him work.

**Comment by Nemesis666first** [comment]
I see that the Waist make damage, but they aren't influed by set bonuses (like Akkhan or Light set)

**Comment by d07RiV** [comment]
Huh you mean it doesn't work in-game? Or in the simulator?

**Comment by Nemesis666first** [comment]
In the simulator,
