### ISSUE TITLE
Strange set visualization on firefox

### ISSUE THREAD

**Issue by Fcomp** [d07RiV/d3planner#311]
Browsing from firefox each set is shown like this:
set 1
--set 2
----set 3
------set 4
and so on.

I've found that disabling from the console the css property in bold solves the issue:
.profiles-frame .profiles-set {
    **margin-top: -1px;** 
    display: block;
    list-style-type: none;
    cursor: pointer;
    padding: 2px 6px;
}

**Comment by d07RiV** [comment]
Can't reproduce - looks fine to me on Firefox. Could you post a screenshot or some more details, please?

**Comment by Fcomp** [comment]
Sure, here you are:

![image](https://user-images.githubusercontent.com/17270600/36731850-45070e92-1bcc-11e8-90ca-983e31745a2e.png)

**Comment by d07RiV** [comment]
I'm not getting the wrapping issue, but I noticed that the heights are slightly different in Firefox, which I'm looking into.

Also, it seems that your browser doesn't support Verdana font.

Disabling the margin property adds an ugly double border.

**Comment by d07RiV** [comment]
Added some CSS normalization, this should look more consistent now. I couldn't reproduce your problem in full so I can't guarantee everything.
