### ISSUE TITLE
Augustine's Panacea decreases Ball Lightning average damage

### ISSUE THREAD

**Issue by nattthebear** [d07RiV/d3planner#313]
Without Augustine's Panacea, Ball Lightning's "average damage" is shown as 2x, 3x, or 4x of the "damage" depending on the chosen size of the target.

With Augustine's Panacea, Ball Lightning's "average damage" is shown as 0.8x, 1.2x, or 1.6x of the "damage" depending on the chosen size of the target.

**Comment by d07RiV** [comment]
Oops it was using the 200-250% roll instead of fixed 30%. Fixed.
