### ISSUE TITLE
Hellfire passives missing when importing profile

### ISSUE THREAD

**Issue by F1MBULW1NT3R** [d07RiV/d3planner#317]
When I import characters from my profile the passives are missing from their Hellfire Amulets, can't add the passive back with "add stat" so have to make a new amulet to copy what's used on the character. Another side effect of the new API?

**Comment by d07RiV** [comment]
Probably, I'll check when I get the chance.

What do you mean you can't add the passive back? Can you unlock the item and add the passive?

**Comment by F1MBULW1NT3R** [comment]
If I unlock the item I can only add normal secondaries (resists, goldfind etc), but if I use the dropdown to change the HFA into another amulet then change it back to HFA I can select a passive. Or delete the HFA and create a new one and I can select a passive.
![hfa1](https://user-images.githubusercontent.com/37324476/37547892-312252ea-29d9-11e8-8277-307f01dd351c.png)
![hfa2](https://user-images.githubusercontent.com/37324476/37547893-314ced16-29d9-11e8-91e3-88c3fbaa5c79.png)
![hfa3](https://user-images.githubusercontent.com/37324476/37547894-317b21ae-29d9-11e8-8e06-7ede3423464f.png)

**Comment by d07RiV** [comment]
Oh right yeah I forgot you can't add those. Maybe I should add an additional check to add missing passives to legendaries.

**Comment by d07RiV** [comment]
Should work now.
