### ISSUE TITLE
Tal Rasha 2pc Much More Lenient on Procs

### ISSUE THREAD

**Issue by Khaldei** [d07RiV/d3planner#318]
Hello,

I've found an issue with the Tal Rasha 2pc.  This is very minor, but in the game it is much more lenient than the 4pc or the 6pc.  If you read the bonuses, the 4pc and 6pc specify attacks.  The 2pc only quotes damaging enemies.

What this means is, you can have on a Band of Hollow Whispers and the cold damage haunt will proc an ice meteor.  I can absolutely verify this is true.  I am witnessing this behavior over and over in my current game, and I am dead certain that the ring is the only thing producing cold damage.  Currently the simulator is not capturing this.

**Comment by d07RiV** [comment]
Hmm I dunno why I added the check in the first place, thanks.
