### ISSUE TITLE
Ring of Royal Grandeur Not Giving Full 6 Piece Bonus

### ISSUE THREAD

**Issue by minion-jen** [d07RiV/d3planner#319]
Hi, I am using this planner and I have the Ring of Royal Grandeur as my Kanai's Cube jewelry item. It is only giving me the 4 piece bonus even though i am wearing a 5 piece set and the Ring of Royal Grandeur in the cube which gives me the 6 piece bonus. How can I fix this or what can i do to get the full bonus listed on the planner? Thank you.

**Comment by d07RiV** [comment]
Does your RoRG list the legendary bonus in the planner? Sometimes the bonus gets lost when importing characters so you need to make a new ring manually.

**Comment by d07RiV** [comment]
Works for me, can you link a profile where it doesn't work?

**Comment by minion-jen** [comment]
Thanks for the reply! Here is the link to the profile https://www.d3planner.com/247494928 


 The set items list as all green (giving the bonus) when you look at the individual pieces, but if you click on skills/effect and scroll down then the monkey king set bonus is only listed as 4 items and not 6.


Thanks again for your help.


~ jen ~






-----Original Message-----

**Comment by shchmue** [comment]
Only Item Effects are listed in that section. For Sunwuko, only the 4 piece bonus **deals damage** and so it's listed there. The 2 piece bonus only modifies damage reduction and the 6 piece bonus only modifies skill damage. The number you see under the 4 piece bonus in item effects is just the damage the exploding clones does.

**Comment by d07RiV** [comment]
Thanks for the response, closing.
