### ISSUE TITLE
Just some ideas/plans

### ISSUE THREAD

**Issue by d07RiV** [d07RiV/d3planner#32]
Going to leave it here so I don't forget, and in case someone wants to suggest these. I might add more in the future.
- Add monster kill events to the simulator - very tricky, as it requires separating the number for buff stacks and number of enemies it applies to, so a correct number of buff instances can be removed when a target dies.

**Comment by dominiklohmann** [comment]
Some ideas I've had (might expand the list later).

- Add percentage of damage dealt per skill from Area Damage to simulation output (We had this for a while with all damage combined, but a per skill breakdown would be nice)
- Group simulation. Allow up to 4 sets and simulations to be simulated at once, taking group buffs into account. 
- Follower simulation. Allow up to 1 sets and a special follower set to be simulated at once. Also move followers from group buffs to their own set.

To expand on the monster kill events, maybe take a look at rift monster groupings (see [silecs list](http://warpath.eu/progression.html) and find out their health at a certain GR difficulty level and have certain presets with these mob combinations and their respective health values.

You could also take a look at elite kill events for In-Geom and Bane of the Powerful.

**Comment by VitaKaninen** [comment]
Another thing that would be very useful would be to have the option to enable shrine buffs.  I use Gloves of Worship a lot, and would like to see what effect different shrines have on my character.

**Comment by tw33dl3dee** [comment]
You actually have shrine buffs in the party/follower buffs group.

**Comment by d07RiV** [comment]
An update, I'm currently reworking the buff system, so I can have separate debuffs per target, this would also allow me to finally make death events. I just need to go through all the skills and make sure they work with the new system.

**Comment by tw33dl3dee** [comment]
It feels like it depends on your latency heavily (because the client won't allow you to use a skill until server tells it that the CD has finished; yeah, having no client-side prediction sounds very lame).

Also, NumLock spams skills considerably slower than that, approx 1/sec.

I've been using D3Helper for casting EB in a FlashFire build (which should be the fastest possible way to cast it) , and based on AP regen needed, the delay was between 600 and 650 msec. My usual latency is 20-30 ms, so this isn't even close to 500 ms + ping (or 500 + 2*ping) that you could expect).

EB is different from Teleport, though, because it has secondary animation, so doesn't depend on your AS at all.

**Comment by d07RiV** [comment]
Explosive blast doesn't scale with AS not because its a secondary animation, but because its attack speed is fixed to 1.5:

http://www.d3planner.com/powers/Wizard_ExplosiveBlast#TAG_POWER_ATTACK_SPEED

Compared to

http://www.d3planner.com/powers/Wizard_MagicMissile#TAG_POWER_ATTACK_SPEED

So I suppose the actual cooldown could be either 2/3rds of a second (667ms), or it could match the actual animation length, which would be 38 frames, or 633ms.

Regular teleport skill also has a fixed animation speed, which is 2.5, so either 400ms, or 21 frame (350ms).

But Archon Teleport does scale with attack speed, which is why I figured it would be the easiest to test, especially since you can stack crazy amounts of AS with Vyr's set.

**Comment by tw33dl3dee** [comment]
Ah, I see.

I'm going to test it more precisely with my flashfire Wizard, but 633ms sounds closer to my old data (judging by AP regen) than 667ms.

Teleport, however, certainly doesn't feel like 350ms - I don't think you can cast it 3 times a second with In-geom.

**Comment by d07RiV** [comment]
Updated to support kill events. I haven't tested it thoroughly, though >.>
