### ISSUE TITLE
Wrong Values of the 'Etched Sigil'

### ISSUE THREAD

**Issue by Brom24** [d07RiV/d3planner#320]
In the Game the Offhand 'Etched Sigil' has an 150% damage boost, but here it don't

**Comment by Brom24** [comment]
Items normally have the original value, but if you search and implement a build you get items with wrong values. 
Here with the Etched Sigil : https://www.d3planner.com/726248047
And here with the Bracers of the First Man: https://www.d3planner.com/116877321

Both builds are just loaded and not altered, both are from Rhykker.

**Comment by d07RiV** [comment]
They're using legacy versions of the items. You can see that by clicking the item and the box in the middle section will say (Legacy).

I noticed that some of the featured builds use wrong versions of items, I'm guessing the authors modified old builds and forgot to replace the items. Not much I can help with here.
