### ISSUE TITLE
Soul Harvest mana doesn't match in-game values

### ISSUE THREAD

**Issue by shchmue** [d07RiV/d3planner#323]
I did some testing and figured out 3 things:
* Soul Harvest - Swallow Your Soul only gives up to 5 stacks' worth of mana even if you have more than 5 stacks (ie with Sacred Harvester)
* the SYS mana boost only affects base mana, not mana from items and paragon
* Spiritual Attunement percent **does** apply to mana from all sources

Since the d3p code for SA and SYS just adds the percentages together, I fixed it by making SYS add a stack-based amount (up to 5) to maxmana instead of maxmana_percent to keep it from modifying +mana from items/paragon. It now matches all the tests I've run in game.

In the meantime I submitted a bug report to Blizzard because every other Soul Harvest mechanic seems to scale up to 10 stacks. Not sure there are actually any builds that need tons of mana, so I doubt this will affect simulations, but in the interest of accuracy...

**Comment by d07RiV** [comment]
Thanks, merged.
