### ISSUE TITLE
battletag not found

### ISSUE THREAD

**Issue by mateopotato** [d07RiV/d3planner#324]
I used the text#1234 format (actually cut and pasted from my D3 account), tried re-selecting the country; the battletag is reported as 'not found'. I did recently change the battletag (the one free change). 

Suggestions? I don't remember my old battletag.

**Comment by d07RiV** [comment]
Are you using the correct upper/lower case letters? Does your profile show up correctly on the official website?

**Comment by mateopotato** [comment]
Yes, actually copy/pasted the battletag. I just logged into the official
site and it shows my new battletag, as does the battle.net client. I logged
into D3planner and tried again and no luck. I tried different combos of
upper/lower case as well as what is reported by D3.

One thing, before I changed the battletag D3planner did show my main
character but not with her actual gear and the new toon had stats I wish my
toon had. I did not enter my battletag then.

I also tried it on my laptop (as another computer) and still no luck. Reset
my gaming rig and no luck. I go solo with D3 so changed to public and still
no go. I even tried the number alone (as in #1234) and no go (no surprise
here).

**Comment by d07RiV** [comment]
Well I have no power here, because the data is obtained directly from battle.net API, there is no caching on d3planner side.

Usually the API data is in sync with whatever is displayed on your battle.net profile (i.e. https://eu.diablo3.com/en/profile/Riv-2568/hero/101097970) - if that's also outdated for you, you can try asking on battle.net or D3 forums, otherwise something is wrong on API guy's end, but in either case it would be Blizzard's problem.

**Comment by mateopotato** [comment]
Now my profile does not exist on battle.net. Not sure what this means and
this must be the problem.

Thanks for your help, it was truly great not being ignored.

**Comment by mateopotato** [comment]
I did some digging and it appears this is a common problem after a
battletag change. The fix appears to be to wait for servers to sync up, not
sure which servers though. My profile is now available and I see my toons
on your website.
I've gotten used to evasive support staff at Blizzard, you are the
exception to that.

**Comment by mateopotato** [comment]
****take care I just got an alert from my virus checker*****

One of the websites I went to might have been compromised.
