### ISSUE TITLE
Leoric's Crown missing legendary property

### ISSUE THREAD

**Issue by Eglin** [d07RiV/d3planner#326]
Hi,

Thanks for a wonderful tool!  Unfortunately, I find that after importing a character wearing Leoric's Crown the helmet lacks a legendary power.  It seems to function properly in the cube, but the equipped version strangely lacks legendary powers entirely.  I do not see any way to add the legendary power after the fact, either.

**Comment by d07RiV** [comment]
Importing parses the text on your items (blizzard removed raw attribute data from the API somewhat recently), which unfortunately isn't very reliable if there are small spelling mistakes. I'll check this particular case when I get the chance.

There's no way to add legendary powers to existing items, but you can create a new item and copy the stats over.
