### ISSUE TITLE
Area Damage not calculated in either simulation or elemental DPS

### ISSUE THREAD

**Issue by dpastern** [d07RiV/d3planner#329]
This is rather frustrating, because I am not sure if an item with AD on it is worthwhile moving to...

I have looked through the menus and can't see anything regarding to activating AD calculations in sim etc, so please correct me if I'm wrong!

Cheers,

Dave

**Comment by d07RiV** [comment]
AD should be factored in if you set multiple targets that are close enough (spread isn't too high).

**Comment by dpastern** [comment]
OK, got it working - changed spread to 10 yards and whites to 6 etc and it does change the sim calc.  

I'm new to AD, this is the first season i have used it (I typically have went with IAS in the past seasons since s10).  

Despite what everyone says about AD (being so great), my experiences are that it SUCKS and massively so.  AD on shoulder (19%), weapon (24%) + paragon and it just does SFA.  Trying a 109 and can't even get close - typically @ 50% timer by 12 minutes (meaning it's gonna take me 2*12 + RG kill time to complete the 109).  p1200 (low paragon i know, I'm a solo player and D3 fucks over solo players massively).  

In s13, with IAS on gloves (7%) and weapon (7%) and elusive ring (7%) and p1600 I was regularly coming within 30 seconds of successfully completing the 109.  I had a *chance* of actually doing it, with AD and s15, I can't even get remotely close.  

AD shows massive damage buffs in sim on d3planner, but in real life, I am seeing nothing even remotely like this.  Perhaps I am unlucky and not proccing AD with the 20% chance, but like 2%.  I say this because my lgem upgrades for 60% are around 38% over 2k GRs - significantly below what everyone, including Blizzard says is the RNG...

note: I play on console, and typically, mob density SUCKS on console compared to the PC version of the game.  We also have the stupid NG mechanism to deal with and I'm finding that I simply cannot kill quick enough to get NG, let alone maintain it, so I am stuck at 50% PC dmg, which completely screws your chances of successfully doing the GR and puts console players at a serious disadvantage to the PC version of the game...

Sorry for the rant, just getting very frustrated :/
