### ISSUE TITLE
Focus/Restraint - Leap

### ISSUE THREAD

**Issue by chatmanm2** [d07RiV/d3planner#33]
I noticed when using the sim that Leap doesn't proc the Generator part of the F/R set. This leads to issues on the dps since there's no up time on that half of the set.

**Comment by dominiklohmann** [comment]
Did you test that in the game? I am pretty sure it did not work in 2.3.

**Comment by chatmanm2** [comment]
I just did yes. I was running on my Leapquake barb in game and have both buffs from F/R up. Attempting to see if I could min max it a bit I ran it in the sim and noticed the up time was only there for the spender half (Ancient Spear Bolder Toss).
![screenshot003](https://cloud.githubusercontent.com/assets/17239768/13036797/a320944e-d33f-11e5-8115-fb81e383f7e7.jpg)

Screenshot for evidence :)

**Comment by dominiklohmann** [comment]
Good thing to know, that is not listed anywhere in the patchnotes or hotfixes list.

**Comment by chatmanm2** [comment]
Also, I noted that it does proc it both without the Earthen Might and with the Earthen Might passive. Tested with both just to make sure it was actually leap causing the buff proc and not the fury gain from the passive.

**Comment by d07RiV** [comment]
Can't reproduce. Leap generates resources just fine in the current version. Are you sure that your range is low enough such that leap is actually hitting the enemies, aka does it appear in the damage output (the simulator assumes that you're leaping in place)?

**Comment by chatmanm2** [comment]
Actually, that did fix the issue. I didn't see that slider previously to move it from the default 40. I apologize for the confusion.
