### ISSUE TITLE
DH - impale/grievous wounds rune not being calculated correctly

### ISSUE THREAD

**Issue by dpastern** [d07RiV/d3planner#333]
Set impale to the grievous rune.

test dmg on simulation. 

Also check elemental DPS.  

now, remove this rune and set the impale skill to no rune.

Both sim and elemental DPS are unchanged.  

When setting skill/conditions under skill priority, there is no option for impale/grievous, which I believe there should be.  

DMG increase is probably not huge, since it's only an additional 330% weapon dmg, but, d3planner isn't taking it into account at all.

**Comment by d07RiV** [comment]
Indeed, it was adding way too little damage. Should be better now.
