### ISSUE TITLE
[PTR] Damage multiplier for set items

### ISSUE THREAD

**Issue by MarkusTo** [d07RiV/d3planner#341]
Hey.

Are there any plans/any way to update the damage multipliers for set items (e.g. Tal Rasha dmg increased from 750% to 3000%) introduced on PTR for the upcoming season 16? They may change, but would love to try out some stuff with the updated damage multipliers.

Keep up the good work!

**Comment by iThinkiWin** [comment]
![PTR Gear](https://i.imgur.com/ZIiPKTY.png)

**Comment by iThinkiWin** [comment]
Though ^ the simulator still works. just the items are displaying the old values. so not a biggy

**Comment by bglpuppy2** [comment]
Actually if you move over to the skills, and then to the damage numbers of one of your skills, the multipliers are still the old ones not the new ones.

**Comment by iThinkiWin** [comment]
![talsp](https://user-images.githubusercontent.com/12555368/49335377-48dd8780-f5ba-11e8-8fd6-969092536482.png)

I never mentioned the skills tab (also no skills are changed in the patch only set damage is being balanced). I said Simulator still works as ^ shows Live Version Tal SP is only 45Q for the 50/3 stack hit PTR sim shows 149T as it is supposed to.

**Comment by Kamekazzi** [comment]
Still does not work.

**Comment by d07RiV** [comment]
Have you tried hard refreshing page (ctrl F5) or clearing cache? If PTR version is showing old values in tooltips (i.e. Tal Rasha's 750 instead of 3000) then it must be using old data cached somewhere.
