### ISSUE TITLE
Lost 90% of my saved profiles.

### ISSUE THREAD

**Issue by elkaonline** [d07RiV/d3planner#345]
Hi, 

I have not used d3planner for a year or so. I just went to it, but I have only 2 saved profiles. Before, I had around 10 or so saved profiles.

Where did they go ?
I've spend a lot of time doing those.
Can someone help me recover them ?

I don't feel like redoing all that.

Thanks.

**Comment by d07RiV** [comment]
I cleaned up the DB some time ago, deleting profiles that haven't been used (loaded or edited) for a year. Sorry for not making a backup at the time, but I have a backup from June 2017 - I can try restoring them for you if you leave your username.

**Comment by elkaonline** [comment]
Hi, 

My username is "elkalaarz". I pray for this backup having all my sweet profiles.

Thanks for replying.

**Comment by elkaonline** [comment]
Hi, 

Just checking for follow up concerning the potential backup for my lost profiles :D 
(username : "elkalaarz" )


Thanks !

**Comment by elkaonline** [comment]
hi, still waiting for some backup to show up :D 
It has been almost a month. Ty in advance !

**Comment by d07RiV** [comment]
Sorry for *very* late reply, I couldn't find any profiles for your user in the dump from June 2017 :(
