### ISSUE TITLE
[Easy] 2.6.4 S16 LoN 750%

### ISSUE THREAD

**Issue by dtruffaut** [d07RiV/d3planner#346]
The Legacy of Nightmare rings set bonus, on patch 2.6.4.54724 (Season 16), should be 750% instead of 100%.

This issue is easy to fix.

**Comment by BeJiXiong** [comment]
For me it shows 500% as it was on the PTR. The final patch notes state 750%.
Also the sets which buff got a bit nerfed with respect to the PTR are still not updated (like e.g.: Tal Rasha, still 3000% bonus instead of 2000%).

Cheers.
