### ISSUE TITLE
Bone Ringer - Stacks selector

### ISSUE THREAD

**Issue by dtruffaut** [d07RiV/d3planner#348]
Just like the Bane of the Stricken gemn, the Bone Ringer phylactery buffs damage with stacks.

Please add a stacks selector for Bone Ringer.

**Comment by eXisFOHDR** [comment]
I can verify that the damage increase from bone ringer does not have a cap; it will continue growing so long as the mob the skeletons are commanded on does not die and that the mob that you commanded on remains on an actively loaded tile.

**Comment by dtruffaut** [comment]
In patch 2.5.8, Bone Ringer is capped to 60 stacks.
Issue closed :)
