### ISSUE TITLE
Cannot choose skill in skill priority

### ISSUE THREAD

**Issue by dominiklohmann** [d07RiV/d3planner#35]
The CSS update from e86e9824 made it impossible to choose a skill in the Skill Rotation part of the simulator. 

Tested in Google Chrome 48 (with disabled plugins).

<img width="492" alt="screen shot 2016-02-19 at 15 29 36" src="https://cloud.githubusercontent.com/assets/4488655/13178132/9ff615fa-d71d-11e5-9170-f85aa68d1c20.png">

**Comment by d07RiV** [comment]
Seems to work for me. Do you have any skills selected in the skills tab? If you don't uncheck the "Only show applicable buffs/skills." box, it will only list the skills used in the build.

**Comment by dominiklohmann** [comment]
Even with the box unchecked it didn't load any skills for me.

However, I since emptied the cache and reloaded the page and now it's working again. Must've been an issue with my chrome, I guess. Still weird.
