### ISSUE TITLE
No Import Possible

### ISSUE THREAD

**Issue by XiNaru** [d07RiV/d3planner#357]
Hey You,

i cant import my charakters. every time i write bei battletag an search, thera was seen the error, The account could not be found.
my account is on the EU servers und my battle tag ist XiNáru#2173

I will not spend 10 euros just to change the á to an a. eswäreschön if there could be looked over in the code of you over it.

**Comment by XiNaru** [comment]
i have a answer :)
synsx? Try this code to import

%E5%86%B0%E8%89%B2%E5%B0%8F%E8%88%9F#3377

**Comment by d07RiV** [comment]
Fixed.
