### ISSUE TITLE
Save Function and Login Issues

### ISSUE THREAD

**Issue by Trueneverborn** [d07RiV/d3planner#361]
Unable to login, save a profile, or open previously saved profiles via links. Requesting code does not recognize email. Similar post from yesterday, but did not list everything that I was experiencing. Tested on Windows 10 x64 with both Firefox and Chrome, different machines, different locations, all of which worked yesterday up until 4pm.

**Comment by Kamiikaze** [comment]
yea the same for me. I think server is rip from d3planner

**Comment by thisisatest81** [comment]
Nobody is able to login at d3planner right now and you cant even make a new account.
I dont know who the owner is but somebody please check the services. It seems like its either broken or they lost their data!

**Comment by Trueneverborn** [comment]
While a loss of data is 'upsetting' it's not the worst case scenario for something someone is offering free of charge and only asks for donations. Hope the issue isn't a symptom of a larger issue but I'm open to help testing.

**Comment by d07RiV** [comment]
Server ran out of disk space (damn auto backups) and the database stopped working. I cleaned it up but still had to repair the DB, hopefully nothing was lost in the process.

**Comment by Trueneverborn** [comment]
Verified:

- 8 links created from 1/15 through 1/21 now valid and active once again
- Able to log into account with previous credentials
- Requested backup code with email; still waiting on email after 15 minutes
