### ISSUE TITLE
Missing item in the cube

### ISSUE THREAD

**Issue by XiNaru** [d07RiV/d3planner#362]
Hey,
if i want to import my non-season character, in-geom and gathering of elements is in the cube. the broken crown that I actually have missing in it. This seems to be currently only with one chara the error.

**Comment by XiNaru** [comment]
non season, level 70 crusader
charaktername: XiNáru

battle tag: XiNáru#2173

**Comment by d07RiV** [comment]
I see the same on the official site: https://eu.diablo3.com/en/profile/XiN%C3%A1ru-2173/hero/92246374

Must be something on Blizzard's end that the item isn't visible from outside the game.

**Comment by XiNaru** [comment]
o.o very suspect o.o
i know, the charakter has 3 cube items, and this a long time
