### ISSUE TITLE
Endless Loading Circle

### ISSUE THREAD

**Issue by Jamezee33** [d07RiV/d3planner#363]
I have tried on 3 different computers and on every browser I know of. No matter what I do when i click my character to import it just endlessly loads but nothing ever happens.

**Comment by d07RiV** [comment]
Try opening dev tools (F12 in chrome) to see if it prints any errors to the console? My imports seem to be working fine.

**Comment by Jamezee33** [comment]
on all browsers and 2 different computers I get an error.

Chrome: "VM145 adsbygoogle.js:1 Uncaught H {message: "adsbygoogle.push() error: No slot size for availableWidth=44", name: "TagError", stack: "TagError: adsbygoogle.push() error: No slot size f…syndication.com/pagead/js/adsbygoogle.js:1:72545)"}
kd @ VM145 adsbygoogle.js:1
ud @ VM145 adsbygoogle.js:1
Zh @ VM145 adsbygoogle.js:1
(anonymous) @ VM145 adsbygoogle.js:1
(anonymous) @ VM145 adsbygoogle.js:1
The resource https://pagead2.googlesyndication.com/pagead/js/r20190122/r20180604/show_ads_impl.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
core:1 Uncaught TypeError: Cannot read property 'drop' of undefined
    at Object.DiabloCalc.setSlot (core:1)
    at Object.DiabloCalc.setProfile (data.js:1)
    at core:1
    at Object.success (core:1)
    at l (script:4)
    at Object.fireWith [as resolveWith] (script:4)
    at k (script:6)
    at XMLHttpRequest.<anonymous> (script:6)"

**Comment by d07RiV** [comment]
Could you link your character profile so I can investigate?

**Comment by Jamezee33** [comment]
https://us.diablo3.com/en/profile/jamezee-1458/hero/108430266

thanks for the help

**Comment by d07RiV** [comment]
Sorry for the delay, it seems to be working correctly now? Maybe there was a bug with some item you were using back then :(

**Comment by Jamezee33** [comment]
Thanks for the responses. No it is still not working. I can see my list of characters but I cannot import their gear or anything into the planner. When I click a character it just hangs forever.

**Comment by Jamezee33** [comment]
Very strange. I can see your link but still cannot import a character myself.
