### ISSUE TITLE
Dual Scythes = Leger's Disdain x2 ?

### ISSUE THREAD

**Issue by dtruffaut** [d07RiV/d3planner#364]
**Leger's Disdain**
_Grim Scythe deals an additional 80% damage for each point of essence it restores._
https://us.diablo3.com/en/item/legers-disdain-P61_Unique_Phylactery_03

**Grim Scythe**
_Generate: 12 Essence per enemy hit_

**Grim Scythe / Dual Scythes rune**
_Generate: 12 Essence per enemy hit
Slash with two summoned Scythes (...) and push enemies together_
https://eu.diablo3.com/en/class/necromancer/active/grim-scythe
Pushing ennemies together means ennemies are touched by the two scythes.
If you look at the description of Grim Scythe / Dual Scythes rune, you'll see it is the only one rune that restores an additional amount of 12 essence points per ennemy hit (because there is a second scythe).

**Grim Scythe / Dual Scythes rune + Leger's Disdain**
Therefore, Grim Scythe / Dual Scythes rune + Leger's Disdain equiped should multiply by 2 the damage performed by Leger's Disdain bonus. 
Which means, with the Dual Scythes rune, Grim Scythe deals an additional **160%** damage for each point of essence it restores.

**NB : I'm not sure. To check.**

**Comment by d07RiV** [comment]
You can move the slider further. It represents the number of hits, after all. Sorry, but I don't see it as an issue.

**Comment by dtruffaut** [comment]
Fine.
