### ISSUE TITLE
Bombardier's Rucksack

### ISSUE THREAD

**Issue by StevenAston** [d07RiV/d3planner#365]
The planner doesn't _appear_ to account for the [Bombardier's Rucksack](https://us.diablo3.com/en/item/bombardiers-rucksack-Unique_Quiver_102_x1) ability to drop up to 5 sentries. I'm unsure if it's just the simulator saying it's not optimized or it's not accounting for it at all.

**Comment by d07RiV** [comment]
Not sure what you mean, it seems to be working correctly in both the skill tab (60000% damage from M6) and simulation (try [this profile](https://www.d3planner.com/192514640)).
