### ISSUE TITLE
Wave of Force - Debilitating Force

### ISSUE THREAD

**Issue by lolesch** [d07RiV/d3planner#371]
Hey, I was working on a zWizard build and I wondered why the Wave of Force - Debilitating Force is not listed as a debuff to monsters for group members. Is this missing or wizard exclusive?
than I realized Blinding Flash - Crippling Light might be the only debuff listed, things like Slow Time -Exhaustion is missing too.
would be great to see all these in the chart! 
Cheers

**Comment by d07RiV** [comment]
There's no stat for enemy damage reduction, don't think it's particularly needed either, since it's not used in any calculations.

Blinding Flash - Crippling Light is there by mistake, from back when it added regen.
