### ISSUE TITLE
Import of chinese btags not working at all

### ISSUE THREAD

**Issue by sebflex** [d07RiV/d3planner#373]
Hello,
the import of chinese battletags/profiles not working at all, for every btag you wanna import it shows "Profile not found"!!!

![image](https://user-images.githubusercontent.com/13700528/53297941-6a02ec80-3826-11e9-8ca1-4ee174a52c11.png)

**Comment by d07RiV** [comment]
Thanks, I probably haven't updated the site for new API on chinese side, will look into it when I get a chance.

**Comment by d07RiV** [comment]
Could you provide a link to some working Chinese profile? I tried the one in the picture and it seems the issue is on their side, but I'm not sure if I wrote it correctly (花无缺#51108).

**Comment by d07RiV** [comment]
Found the problem, seems to work now.
