### ISSUE TITLE
Delete Account

### ISSUE THREAD

**Issue by Duessel123** [d07RiV/d3planner#374]
How can I delete my D3 Planner account?

**Comment by d07RiV** [comment]
There isn't a way, but if you really need that I can delete it for you.

I don't have a good procedure for it, but can you change your password to something you don't care about, then e-mail me username+password at d07.riv@gmail.com?

**Comment by Duessel123** [comment]
Hi,

That would be great. My username is Duessel and I've changed the password
to 123456.

Many thanks

**Comment by d07RiV** [comment]
Ok, done.
