### ISSUE TITLE
Suggestion: Season 17 LoN buff option

### ISSUE THREAD

**Issue by darthnorman** [d07RiV/d3planner#375]
Please add in an option to toggle on the season 17 buff that is set to permanently give everyone the effect of the LoN set bonus for theory crafting.

**Comment by d07RiV** [comment]
Oh yea I forgot about the PTR version, I'll include it there.

**Comment by MarkusTo** [comment]
I still only have the option to toggle the RORG-buff from S16. Something wrong on my end?

**Comment by d07RiV** [comment]
PTR version should be up now. I haven't really tested it, let me know if anything is wrong.

**Comment by darthnorman** [comment]
Just tested it on ptr.d3planner.com and the bonus is not represented in the stats. The damage buff should be applied as long as one ancient item is equipped, right?
What I did: Checked the box, gave the wizard an ancient weapon and a skill, checked if the buff is applied to the skill.

**Comment by gdejohn** [comment]
I'm not seeing the PTR LoN bonus either. And the [Sin Seekers](https://us.diablo3.com/en/blog/22933131/patch-265-ptr-preview-4-22-2019#items) quiver is missing its new 300% Rapid Fire damage increase.

**Comment by Schtenk** [comment]
have been trying to figure out why the buff isn't applied and it seems like because the items are never added to:
`this.info.sets` 

The affix is never added in the loop
`for (var s in this.info.sets) {
	var i = DC.itemSets[s], e = this.info.sets[s];
	e >= 2 && this.leg_ringofroyalgrandeur && (e += 1);
	for (var a in i.bonuses)
		if (e >= parseInt(a)) {
			statInfo[r = "set_" + s + "_" + a + "pc"] = { args: 0 }, this.add(r, !0);
			for (var n = 0; n < i.bonuses[a].length; ++n)
				i.bonuses[a][n].stat && this.add(i.bonuses[a][n].stat, i.bonuses[a][n].value, 1, s);
			this.affixes[r] = { slot: this.setSlots[s], set: s, pieces: a, value: [] };
		}
}`

The buff seems to apply if this code is added right before the above for loop(maybe a bit of a shitty fix but it works)
`if(DiabloCalc.options.seasonal && location.hostname.toLowerCase().indexOf("ptr") >= 0){
   this.info.sets["nightmares"] = 2;
}`

**Comment by d07RiV** [comment]
Oh yea, made a mistake there. It set the set_nightmares_2pc stat, but didn't add it to list of affixes so the actual bonus was never applied (though I think the simulator would've picked it up).

I saw the pull request, but extraFx wasn't really intended for that so I'll just add it to stats initialization instead.
