### ISSUE TITLE
Swamp Land Waders

### ISSUE THREAD

**Issue by GMaith** [d07RiV/d3planner#376]
Should be accessible to other classes (IE. Necro). But is not an option

**Comment by Schtenk** [comment]
You can choose swamp land waders if you uncheck "hide items for other classes" in the upper middle of the page and just check it again to not show all items after choosing the pants.

**Comment by d07RiV** [comment]
They're still considered WD drop, so it's working as intended. As mentioned, you can use the checkbox to use items for other classes (same goes for using non-primary stat on support gear).
