### ISSUE TITLE
Site is very slow

### ISSUE THREAD

**Issue by dabachel0r** [d07RiV/d3planner#379]
Hey guys!
The site is really slow since yesterday. Not able for me to use the website :( Maybe you can take a look into it? Or is it only because the season started and there is much traffic?
Thx and best regards!
Username: dabachel0r

**Comment by d07RiV** [comment]
Yes, there's a lot of traffic currently, something I wasn't prepared for. I tried to fix a couple potential bottlenecks but it seems that wasn't enough.

The traffic will fall off by tomorrow.

**Comment by IonFoXx** [comment]
A good solution would be to add Cloudflare as CDN in front of your website. This should reduce the load on your server as they no longer need to serve the image content all the time a new user visits your site.

**Comment by d07RiV** [comment]
I actually just did that. Nameservers will take up to a day to update, hopefully it works out of the box - I have no idea how it handles dynamic content.

**Comment by IonFoXx** [comment]
Oh great, this should reduce the load significantly.

Well cloudflare respects the Cache Headers so if you set them for your dynamic routes they will be applied. So for profile stuff it usually is no cache just let it through. 
cache-control: no-cache
If I'm correct.

Otherwise you could tell cloudflare to not cache specific routes.

**Comment by andreaskromann** [comment]
Cloudflare only cache's static content per default. You can enable it for dynamic content as well with page rules.

Google DNS has been updated with the new IP, but Cloudflares own 1.1.1.1 has not yet updated:

```
C:\src> nslookup www.d3planner.com 1.1.1.1
Server:  one.one.one.one
Address:  1.1.1.1

Non-authoritative answer:
Name:    www.d3planner.com
Address:  162.144.52.41

C:\src> nslookup www.d3planner.com 8.8.8.8
Server:  google-public-dns-a.google.com
Address:  8.8.8.8

Non-authoritative answer:
Name:    www.d3planner.com
Addresses:  2606:4700:30::6812:2b7b
          2606:4700:30::6812:2a7b
          104.18.43.123
          104.18.42.123
```
The images load fast when you hit the Cloudflare cache, but it is still a problem to get the initial request through for the website. You can tell by the response headers if you hit the Cloudflare cache.

**Comment by d07RiV** [comment]
Yeah looks like I'll have to fiddle around. Like, I want requests to /123456789 to pull the main index.html instead of making a new request every time.

The main site will be slow as long as there's lots of people with old dns records in cache.

**Comment by d07RiV** [comment]
Seems to be working now. Need to make sure it doesn't cache things like logged in status though.

**Comment by inph** [comment]
@d07RiV Not sure if it's related with CF DNS, Register seems to always return `Sorry, your registration failed.`

**Comment by d07RiV** [comment]
Database broke earlier today, everything should be fine now.
