### ISSUE TITLE
Shadow's Mantle 6pc Piece Bonus Implemented Incorrectly

### ISSUE THREAD

**Issue by tastysoup1157** [d07RiV/d3planner#38]
I was checking out your damage calculator/simulator for the DH's Shadow Mantle set and noticed that the 6pc bonus might not be implemented correctly. From your dmg breakdown tool tip it reads as if it is a 400x dmg multiplier, but the 6pc bonus is additive to the base skill, it is not a multiplicative buff:
Ricochet = 750% Base Skill Damage
SM 2pc = 600% more Damage
SM 6pc = +40,000 Base Skill Dmg
"Impale deals an additional 40,000% damage to the first enemy hit"

=(Base Skill + S6 Bonus) * S2 * Any bonuses that would normally effect impale
=(750 + 40,000) * (1 + 600 * 0.01) * Any bonuses that would normally effect impale
=40,750 * 7 * Any bonuses that would normally effect impale
=285,250% * Any bonuses that would normally effect impale

You can reference these two bug reports I made if you'd like:
http://us.battle.net/d3/en/forum/topic/20418712688#1
http://us.battle.net/d3/en/forum/topic/20419192810#1
It includes videos, time stamps for the damage samples and a breakdown of the damage equation for the select sample damage numbers shown in the videos. I've reproduced the damage numbers shown in game down to the decimal, so I feel that should be quite conclusive that this is how the set actually works. Let me know if I can provide any extra assistance.

Thanks,

TastySouP#1157

**Comment by d07RiV** [comment]
Huh, that's already how it currently works. The 40000% damage is calculated separately, it doesn't affect the main damage calculation.
