### ISSUE TITLE
Setting up d3planner locally with importing/exporting

### ISSUE THREAD

**Issue by Schtenk** [d07RiV/d3planner#380]
I would love to be able to set this up locally to help lessen the traffic to the d3planner a tiny bit.
Is there any specific reason why the scripts for importing/exporting/saving etc, isn't a part of this repository?
Is there another way of doing this if the scripts can't be included?
Like saving/loading from/to files.

Sorry if these aren't appropriate questions here or to much of a hassle.

**Comment by d07RiV** [comment]
Importing isn't in repository because it uses my blizzard API key; I guess I could put it somewhere in configs though. Saving/loading wouldn't be too difficult to add I guess.

Traffic should fall off by tomorrow, and I'll try to reduce the server load before the next season.

**Comment by Schtenk** [comment]
Allright :) sounds good!
Thanks for the reply!
