### ISSUE TITLE
Builds were deleted. Can't even open them after using the saved link. 

### ISSUE THREAD

**Issue by Darikis** [d07RiV/d3planner#381]
Had maybe close to 40 different sets and now only a few random 20 are left. Even if I use the saved link it gave me nothing comes up besides an empty character. Not sure if this is an error or they were deleted to make space. Just bringing this to your attention.

**Comment by d07RiV** [comment]
I deleted old builds recently (180 days not used, 90 if not registered); I can restore them from backup if you have their numbers or a username.

**Comment by Kwadjo** [comment]
There was a lot of helpful actual builds on https://www.patreon.com/Bluddshed , and now nothing working. Is it possible to restore links to builds (if you don't mind)?

**Comment by d07RiV** [comment]
That is unrelated, I had a database issue today that should be fixed now.

**Comment by TipsyEmu** [comment]
Hey, I took a break for season 16 and came back this season to see that all my builds were gone. 

here are the links:

https://www.d3planner.com/794599612
https://www.d3planner.com/531212673
https://www.d3planner.com/252392827
https://www.d3planner.com/621739519

**Comment by TipsyEmu** [comment]
Links cont.

https://www.d3planner.com/815362706
https://www.d3planner.com/929584105
https://www.d3planner.com/242625487

**Comment by d07RiV** [comment]
Done.
