### ISSUE TITLE
Simulator not functioning

### ISSUE THREAD

**Issue by eXisFOHDR** [d07RiV/d3planner#388]
It has been about a week now that the simulator section does not function. to be specific: when I press the start button in the simulator, it generates the damage graph with no values (0 DPS).
I am not loading any saved characters.  I can just throw any random build(any class) together and still no results.  I have attempted to load the tal rasha build that is in the simulator by default, and it will not generate any values for the graph either.

I have attempted this on 3 separate browser platforms and 5 separate devices/computers, getting the same results each time.

**Comment by d07RiV** [comment]
Thanks for the report, I probably forgot to test the simulator when optimizing some things.

**Comment by d07RiV** [comment]
I tried some simple simulations and they seem to work fine. Can you link a profile  that is outputting 0?

The default tal rasha build is horribly outdated but it should still output some values if you equip the appropriate skills.

**Comment by JamesChen1202** [comment]
I got the same issue on my character 598964509 but it's fixed now. Thank you!
