### ISSUE TITLE
Your site is a mess!@

### ISSUE THREAD

**Issue by Noobilite** [d07RiV/d3planner#389]
Not giving you much more info since you can't manage your own code fundamentally. Your crap is deleting saves and digging up old gone info  and auto saving and deleting info all over the place. Try getting your crap together and manage your base code.

Because of some of this it's refusing to actually save. And if you have more than one set and save it instead of save all it will do nasty things. INCLUDING DELETING ALL OF THE OTHER SETS!! You guys need to learn how to program fundamentally. 

I advise you go over your entire code base and fix it from the ground up.

Not only that it's doing this across all saves. FROM THE ACTIONS OF ANOTHER SAVE! Why don't you learn what you are doing before making  a site like this. This sees to be a huge issue with programmers today. And they can't learn from their mistakes either anymore.

It's even digging up unsaved info out of nowhere. Why don't you get rid of whatever conveluted mess you put in and stop snapshotting usaved builds and leave it up to the user to save on their own info... It's not complicated. Then you woudn't have to worry about deleting people build saves over a year old as you wouldn't be waisting server space on constantly saving our builds invisibly every few seconds.

All of my saves are now a massive mess and basically irreparable. Especially as it won't save when I try to resave it now. FIX YOUR FING SITE! And quite breaking it to start with. You are the problem if you can't keep track of and fully implement your changes. It's sloppy. LEARN WHAT YOU ARE DOING!!!

**Comment by d07RiV** [comment]
It's not saving anything to the server without the user explicitly pressing the save button. Everything else is saved to browser cache and only retrieved when user accepts the prompt upon loading the page. Since you won't give any specific examples, I can't help you further. And it doesn't look like you want help, anyway.
