### ISSUE TITLE
Schaeffer's Hammer

### ISSUE THREAD

**Issue by KylVonCarstein** [d07RiV/d3planner#390]
The Schaeffer's Hammer power has an empty skill multiplier field when cubed, and a correct multiplier when equipped.

**Comment by d07RiV** [comment]
You mean you can't enter the values when selecting it in cube, or it's coming up that way when importing a character? I can't check right now since cube items can't be changed on mobile for some reason.

**Comment by KylVonCarstein** [comment]
When I select it in the cube, it's getting all the appropriate modifiers from character stats, but not the 850% from the legendary power itself.

**Comment by d07RiV** [comment]
Oh ok, fixed.
