### ISSUE TITLE
not open in IE11 ( Loading does not end )

### ISSUE THREAD

**Issue by flexn** [d07RiV/d3planner#392]
![123](https://user-images.githubusercontent.com/18647425/60047411-a37c3380-9704-11e9-8e58-74b39a7bd6c2.png)

just see loading ...

can you fix it ?

**Comment by d07RiV** [comment]
That's a pretty old browser and doesn't support a lot of things. I don't even have it anywhere, not sure if I can do much here.

**Comment by flexn** [comment]
@d07RiV It was open a week ago. Can you roll back?

**Comment by d07RiV** [comment]
Oh, seems the new ad provider breaks it, I'll try to resolve it with them ASAP.

**Comment by flexn** [comment]
@d07RiV Thank you 😆

**Comment by d07RiV** [comment]
I disabled ads on Internet Explorer for now, seems their script is using a lot of new language features so I'm not sure if they will be able to add support.

**Comment by d07RiV** [comment]
Edit: going to enable ads again for a bit so they can have a look.

**Comment by flexn** [comment]
@d07RiV i checked just now in IE11, now working !! thank you
