### ISSUE TITLE
hello,please update diablo3 2.65 dates

### ISSUE THREAD

**Issue by hu1110** [d07RiV/d3planner#393]
D3planner current data is an old version. It doesn't match current version

Please update

**Comment by d07RiV** [comment]
Not sure what you mean, it's been updated as the patch went live. Is something missing?

**Comment by hu1110** [comment]
> Not sure what you mean, it's been updated as the patch went live. Is something missing?
![20190702113624](https://user-images.githubusercontent.com/52347869/60481467-04d17300-9cc0-11e9-800d-890b10aa4ccf.jpg)
![20190702113625](https://user-images.githubusercontent.com/52347869/60481468-056a0980-9cc0-11e9-83df-1e1218e65aa3.jpg)

Okay, I know what went wrong

I chose Chinese on the website, and the data of Chinese and English are different

For example, in the Chinese language page, tal rasha 6P display is 750%, but in the English version of the page, display is 2000%. The data is inconsistent.

Can you fix this bug?

Github is blocked in China, so maybe no one has explained this to you before

**Comment by hu1110** [comment]
Another problem.
I can't search my role data in China server
But a few months ago, it worked
![20190702120454](https://user-images.githubusercontent.com/52347869/60481851-da80b500-9cc1-11e9-844e-547aab9ca78e.png)

**Comment by d07RiV** [comment]
Oh you're right, I haven't updated translation data.

Could you post your battle tag in plain text so I can test it?

**Comment by d07RiV** [comment]
Okay the tooltips should be correct now.
