### ISSUE TITLE
No base armor stat for custom items

### ISSUE THREAD

**Issue by renegadefencer** [d07RiV/d3planner#396]
When creating custom armor items, there is no option to set the base armor stat. This would mostly be for recreating items below level 70, so I understand if it is not a high priority. It is possible to work around this by adding a stat, however the planner will give a warning about impossible stats.

**Comment by d07RiV** [comment]
Using the "armor" stat is probably the best way to do it, don't worry about the warning. I don't think base armor will work very well considering the same custom item type works for rings and other slots as well.

**Comment by renegadefencer** [comment]
Ah ok, didn't know if the warning affected anything else in the sheet. Sounds like the workaround is fine then, thanks!
