### ISSUE TITLE
Crit damage calculation is correct ?

### ISSUE THREAD

**Issue by hu1110** [d07RiV/d3planner#397]
I want to say something about meteorite damage calculations, which are wrong

For example, crit rate is 64% and crit damage is 480%

According to the experiment, with each attack,

If crit, the damage is 1+480%, if not Critical strike, damage is 1

The 1+64%x480% data is incorrect
![QQ拼音1234](https://user-images.githubusercontent.com/52347869/60560299-c9977880-9d81-11e9-9d02-dca179c58dcd.jpg)

**Comment by d07RiV** [comment]
Why is that incorrect? You always do 100% base damage, and if you crit you deal extra 480%. It's the same thing.

**Comment by hu1110** [comment]
> 为什么这不对？你总是会造成100％的基础伤害，如果你爆击，你会额外获得480％的伤害。这是同一件事。


I don't know. Maybe it's just a display problem.

some dot damage is 1+crit64%*extra480%

but Meteor crit dagame is 1+extra480%

**Comment by d07RiV** [comment]
Oh I think I see what you mean. The calculation is for average damage using your crit chance. You can see crit damage range above the formula line, it's quite a bit higher.
