### ISSUE TITLE
Stats not updated

### ISSUE THREAD

**Issue by iXtai** [d07RiV/d3planner#401]
Since ca. 1 day stats on the right side are not updated when I import a profile
![1](https://user-images.githubusercontent.com/53487719/62146634-1a08e400-b2f6-11e9-80dc-74064aeed190.png)
![2](https://user-images.githubusercontent.com/53487719/62146642-1d9c6b00-b2f6-11e9-81b4-b1c3484353cb.png)

**Comment by d07RiV** [comment]
Should be fixed now.
