### ISSUE TITLE
Legacy of Dreams is broken

### ISSUE THREAD

**Issue by gdejohn** [d07RiV/d3planner#402]
https://ptr.d3planner.com/321783042

The damage buff and damage reduction for the Legacy of Dreams legendary gem aren't factoring in every slot, and the slots that are counted change depending on which jewelry slot the Legacy of Dreams occupies.

If it's in the amulet, only the head, shoulders, and neck slots are counted. If it's in the left ring, every slot except the right ring, main hand, and off hand are counted. If it's in the right ring, every slot except the main hand and off hand are counted.

**Comment by d07RiV** [comment]
Oh that's unfortunate, guess I can't do legendary bonuses like that because they're evaluated before it's finished checking all items. Will have to think of a better way to do it.

**Comment by d07RiV** [comment]
This should work now.

**Comment by gdejohn** [comment]
I'm getting this when I socket a legendary gem in any jewelry slot:

```
ReferenceError: getGemValue is not defined 3 core.js:4:8480
    applyGems https://www.d3planner.com/core.js:4
    each https://www.d3planner.com/script.js:1
    applyGems https://www.d3planner.com/core.js:4
    computeStats https://www.d3planner.com/core.js:4
    getStats https://www.d3planner.com/core.js:4
    t https://www.d3planner.com/core.js:14
    a https://www.d3planner.com/scripts/data.js:1
```
