### ISSUE TITLE
Preview o not working

### ISSUE THREAD

**Issue by thisisatest81** [d07RiV/d3planner#403]
Usually when I hover over an item it shows me a preview like it does in the game game. Sonce a couple of days it doesnt do it anymore. Also the dmage and other stats on the right are not updating all the time!

**Comment by gdejohn** [comment]
I've noticed this too, but it depends on the items that are equipped. I've seen it with Squirt's Necklace, Echoing Fury, and the Endless Walk set (when both items are equipped).

**Comment by d07RiV** [comment]
Oops, fixed.
