### ISSUE TITLE
Incorrect stat priority for toughness

### ISSUE THREAD

**Issue by Kika-kun** [d07RiV/d3planner#404]
Hey. 
When I tried to use the stat priority feature to auto choose stats on an item for me for a zDps (monk but not relevant) build, I noticed it valued armor higher than dexterity. Meaning, you would get 516 armor on shoulders and belt even though dexterity goes up to 650 and thus gives 650 armor. 

Step to reproduce: equip belt (crimson) and shoulders (pauldron of the skeleton king), set the stat priority to CDR > RCR > toughness. Items should roll with Vitality, Armor, Cdr, Rcr for shoulders and vitality, all rez, life%, armor for belt. 

While this is not a high priority change, I don't think it would be too difficult to account for.

**Comment by d07RiV** [comment]
Stat priority feature? Haven't heard of it >.>

**Comment by Kika-kun** [comment]
[This is what I'm talking about](https://i.imgur.com/was1E0J.png). Is it not called "stat priority" ?

**Comment by d07RiV** [comment]
Oh never mind me, I forgot I added that :D

I'll look into it.
