### ISSUE TITLE
How are you generating the attribute id -> name lookup?

### ISSUE THREAD

**Issue by sanktanglia** [d07RiV/d3planner#405]
Im looking to get back into some diablo projets and yours is the only one that seems updated, care to share how you are getting the attributes lookup from the game data?

**Comment by d07RiV** [comment]
You mean decoding attribute IDs from game data?

For the main site I don't do any mining and put in all item stats by hand.

For https://www.d3planner.com/game it's running script from this repo: https://github.com/d07RiV/AutoParser

The initial mapping was made by hand by looking at AffixList data, and then patching it based on known affixes.

You can find the data here: https://github.com/d07RiV/AutoParser/blob/master/Work/affixes.js

And the code to generate the correct mapping in the first function here: https://github.com/d07RiV/AutoParser/blob/master/affixes.cpp

**Comment by sanktanglia** [comment]
thanks!
