### ISSUE TITLE
Update D3planner to Patch 2.6.6 + fix issue

### ISSUE THREAD

**Issue by lordep** [d07RiV/d3planner#406]
1. Please update D3planner. Patch 2.6.6 is Now Live https://eu.diablo3.com/en/blog/23093788/patch-266-is-now-live-20-08-2019

2. D3planner don't calculated crusader skill **Laws of Valor** (rune Unstoppable Force) with set Captain Crimson's Trimmings.

**Comment by d07RiV** [comment]
(2) is similar to the legacy gem issue, when legendary effects depend on other stats it makes everything order-dependent.

**Comment by d07RiV** [comment]
Oh, there's another issue preventing Crimson's + Laws from working. I currently have it as *wrath* cost reduction, as stated by skill description. While Crimson's only reads global cost reduction.

Does the game really not differentiate between the two? I initially made those into separate stats to support cases such as DH having separate cost reduction for discipline and hatred. It can come up in a lot of places, such as

* [Crusader] Laws of Valor - Unstoppable Force - 50% wrath cost reduction
* [Barbarian] Sword and Board - 20% fury cost reduction
* [Barbarian] Relentless - 50% fury cost reduction when triggered
* [Demon Hunter] Perfectionist - 10% *discipline* cost reduction
* [Necromancer] Devour - Voracious - 2% essence cost reduction per stack
* [Necromancer] Land of the Dead - Invigoration - 100% essence cost reduction
* [Witch Doctor] Blood Ritual - 20% mana cost reduction
* [Witch Doctor] Pierce the Veil - 30% mana cost *increase*

Can anyone confirm which of these work with Crimson's and which don't?

**Comment by d07RiV** [comment]
Updated for live patch, aside from the simulator. For Crimson's, I'm going to assume everything except Perfectionist and Land of the Dead works for now.

**Comment by lordep** [comment]
[Crusader] Laws of Valor - Unstoppable Force - 50% wrath cost reduction
100% work - test in game.

**Comment by d07RiV** [comment]
Same error again? I'll check when I get home.

**Comment by logam555** [comment]
Was doing builds and found where this bug comes from. When having legendary gems the builder breaks. Adding any legendary gem to a build will result in the stats bug shown in this and #400 this goes from not loading damage on the skills and effects tab to not showing the item's info when hovering over it on the left-hand side of the screen. I haven't tested all the gems to see if only specific ones break it, but so far at least Bane of the Trapped does if you want to replicate. Hope this helps solve the bug. :)

**Comment by logam555** [comment]
Gems that work: Bane of the Horder, Wreath of Lightning

Works when below level 25: Bane of the Powerful, Pain Enhancer

Seems to be Legend Gems that give stats that break it. Probably something else though
