### ISSUE TITLE
leap should spend more time and Skular's Salvation 

### ISSUE THREAD

**Issue by hy418618674** [d07RiV/d3planner#41]
Skular's Salvation 
Increase the damage of Ancient Spear - Boulder Toss by 100%. When your Boulder Toss hits 5 or fewer enemies, the damage is increased by (120-150)%.
the last  150% is another increasing  ,so the damage will be increased by 400% for the result

BB's Leap should spend about 0.93s and it has nothing to do with attack speed

sorry my english is very bad,hope you can understand

**Comment by d07RiV** [comment]
Oh, I thought it would work the same as Nilfurs and other similar items, with the 150% replacing the 100%. Strange how they have the same wording but different meaning.
