### ISSUE TITLE
Aegis of Valor - issues.

### ISSUE THREAD

**Issue by lordep** [d07RiV/d3planner#420]
Aegis of Valor (6 pcs bonus) don't increase damage of Fist of the Heavens and Heaven's Fury.

**Comment by d07RiV** [comment]
Fixed. Grats on the dank issue number.

**Comment by lordep** [comment]
> 
> 
> Fixed. Grats on the dank issue number.
Thanks, "Heaven's Fury" - calculated correct, but "Fist of the Heavens" don't calculated with Aegis of Valor (6 pcs bonus). Example https://www.d3planner.com/964468452
