### ISSUE TITLE
Necro Bone Ringer damage formula

### ISSUE THREAD

**Issue by fabiocavalcanti166** [d07RiV/d3planner#421]
damage of bone ringer 30% up in 60 times `(30 * 60 = 1800)`
but in planner just up to 500% its like a 17 times `(30 * 17 = 510)`
you can see in this [print](https://imgur.com/FW22PK3)
Am i wrong?

**Comment by d07RiV** [comment]
Right, I set a 500% cap because it appeared to be that way in game data, but that was wrong and I forgot to remove it. Fixed now.
