### ISSUE TITLE
Zodiac does not apply in simulation when importing from BNet

### ISSUE THREAD

**Issue by Binkenstein** [d07RiV/d3planner#423]
The Zodiac ring doesn't apply in simulations correctly when a profile is first loaded from Battlenet. I can work around this by replacing Zodiac with another ring and then setting it back to Zodiac.

Bnet Profile: https://us.diablo3.com/en/profile/Binkenstein-6359/hero/89843495
D3Planner Profile: https://www.d3planner.com/156133820

**Comment by d07RiV** [comment]
Fixing.
