### ISSUE TITLE
Wrath of the Berserker - Insanity should not be DIBS

### ISSUE THREAD

**Issue by MarioVX** [d07RiV/d3planner#427]
The Barbarian skill Wrath of the Berserker - Insanity rune has its 50% damage increase added to DIBS, like Marauder's Rage or Battle Rage. However, in game, in character details, WotB Insanity does not appear to increase DIBS, unlike all other similar such effects (Marauder's Rage, Battle Rage, Taeguk etc).

Instead it appears that Insanity is its own multiplier by now.

**Comment by chriscardwell-iq** [comment]
i noticed that if you don't have Mortick's Brace equipped, it's its own multiplier. but if you equip Mortick's Brace, it gets put into DIBS

**Comment by chriscardwell-iq** [comment]
here's some screenshots:

no Mortick's equipped, WotB is in it's own multi:
![noDibs](https://user-images.githubusercontent.com/8418896/71905177-3c1c5300-312d-11ea-98da-ddc4e9ec5223.PNG)


Mortick's equipped, WotB's multi is gone and DIBS has increased by 50%:
![dibs](https://user-images.githubusercontent.com/8418896/71905208-4d655f80-312d-11ea-8d57-203821b846f0.PNG)

**Comment by d07RiV** [comment]
Thanks, fixing.
