### ISSUE TITLE
d3planner.com: This site is temporarily unavailable

### ISSUE THREAD

**Issue by dominiklohmann** [d07RiV/d3planner#44]
If you need help hosting d3planner, I'm pretty sure the community would be able to come up with something. 

<img width="1002" alt="1457108910" src="https://cloud.githubusercontent.com/assets/4488655/13532981/98caffae-e22e-11e5-9c0d-f357d955933e.png">

**Comment by d07RiV** [comment]
I think they're upgrading hardware atm. I'm okay with the hosting for the
most part, thanks.

**Comment by d07RiV** [comment]
I asked them to upgrade my hosting plan, hopefully this won't take too long.

**Comment by dominiklohmann** [comment]
Do you have any metrics for the resource usage of d3planner - bandwidth usage, CPU and memory usage, disk usage?

**Comment by d07RiV** [comment]
No, I don't have access to those except access logs, plus whatever google analytics tells me.

I've already started the migration process, they said it will take 2-3 days I think :(

**Comment by d07RiV** [comment]
Actually the domain name will be changed to the new account within 12 hours so I can have a working version available soon, then they will finish transfering the profiles and everything else.

**Comment by dominiklohmann** [comment]
Sounds good. :+1:

**Comment by d07RiV** [comment]
Done.
