### ISSUE TITLE
Bnet Profile Import Not Working

### ISSUE THREAD

**Issue by Manson1716** [d07RiV/d3planner#46]
I assume you're aware of this but just in case... Hasn't been working since the site move.  Thanks!

**Comment by d07RiV** [comment]
Strange, its working for me. Do you have a specific profile that doesn't load?

**Comment by Manson1716** [comment]
None of them work for me.  Google Chrome Version 49.0.2623.75 (just updated and tried again no luck, also tried clearing cache).

Try importing Manson#1716 on US server.

Always returns "Profile not found."

**Comment by d07RiV** [comment]
D:

That's really strange, the queries are done server-side, so I don't know how it could fail, unless it cached the IP address or something.

Glad to hear its working for you now.
