### ISSUE TITLE
PTR Discussion

### ISSUE THREAD

**Issue by d07RiV** [d07RiV/d3planner#47]
Let's use this for things that need clarification.

Is Archon (now) 300% bonus still additive?

**Comment by dominiklohmann** [comment]
Archon everything is multiplicative with each other. 300% is in its own category, Archon stacks are in their own category, 50% from that one rune are in its own category. It's insane.

**Comment by d07RiV** [comment]
Okay, just wondering why they haven't mentioned that its multiplicative now, because I'm pretty sure the old 20% was additive.

I assume Gogok now follows the same mechanics as Stricken?

**Comment by dominiklohmann** [comment]
Gogok still uses proc coefficients, you can easily gain all 15 stacks at once. It's basically the same as before, except now it's at a fixed 100% proc chance multiplier and scales the dodge as well. It is no longer capped at level 50.

**Comment by d07RiV** [comment]
Ah I see. I assume the rest of the gems are also damage multipliers now?

**Comment by dominiklohmann** [comment]
The only one I'm not sure about is Gem of Efficacious Toxin, haven't tested that yet.

**Comment by d07RiV** [comment]
> Your Shield Glare deals damage equal to up to your last 5 Shield Bash casts

Is that 5x the damage it was *supposed* to do, or the actual damage done? I.e. what happens to overkill, crits, damage buffs/debuffs?

Does the next shield glare still use 5 shield bashes even if haven't used it 5 times between glare casts?

**Comment by dominiklohmann** [comment]
> Your Shield Glare deals damage equal to up to your last 5 Shield Bash casts

I just tested this in game. It takes the damage you would have dealt without any buffs, then adds the up to last 5 together and deals it with Shield Glare. Shield Glare keeps its proc coefficient and damage, so this can deal Area Damage and the damage type will always be holy. This means that when not using CoE or elemental damage and when not landing Critical Hits, the damage dealt by Shield Glare would be the exact damage your Shield Bash dealt to the enemies you targeted with it. Keep in mind that this only counts the damage dealt to the enemy you targeted.

It adds a buff counter on Shield Bash in your skill bar that goes up to 5, casting Shield Glare removes all stacks you have. For an implementation, you could probably rotate through a fixed size array (n=5) and then calculate the sum when Shield Glare is cast (and clear the array).

**Comment by d07RiV** [comment]
Uh so if you had a buff active while using Shield Bash, but then lost the buff, the Glare will deal less damage, or the same damage? What about the other way around?

Also apparently you mean that it will not turn single target damage into area damage if you say, hit one enemy 5 times, then hit everything around you with the glare?

> Fleshrake: Dashing Strike increases the damage of Dashing Strike by 75-100% for 1 second, stacking up to 5 times.

I assume this doesn't affect the current Dashing Strike cast?

**Comment by dominiklohmann** [comment]
> Uh so if you had a buff active while using Shield Bash, but then lost the buff, the Glare will deal less damage, or the same damage? What about the other way around?

It only takes the buffs you have when casting Shield Glare into account. So if you wanna cast it on Holy CoE for example. If you lose buffs, you lose damage. If you gain buffs, you gain damage.

> Also apparently you mean that it will not turn single target damage into area damage if you say, hit one enemy 5 times, then hit everything around you with the glare?

It does do exactly that. What you need to keep in mind is that the buff only holds the damage dealt to one enemy per Shield Bash cast instead of the total damage of the last up to 5 casts. This damage is then dealt to every enemy hit by Shield Glare.

> > Fleshrake: Dashing Strike increases the damage of Dashing Strike by 75-100% for 1 second, stacking up to 5 times.

> I assume this doesn't affect the current Dashing Strike cast?

It does, you gain the buff as soon as you cast Dashing Strike, not when hitting an enemy with it. The buff stack does not refresh btw, so you need to have 5 APS to get the full value from Fleshrake.

**Comment by d07RiV** [comment]
Oh so basically it doesn't really matter how much damage you do, it just does (shield bash tooltip damage %)*5, plus whatever buffs you have. So you don't need to count the damage at all, just the number of stacks?

**Comment by MCPtz** [comment]
Carnevil:
Currently Depth Diggers doesn't affect Carnevil darts.

Still need clarification if Simplicity Strength Gem and Poison Dart % on Gear affects fetish darts.

Since they moved SS and DD to separate multipliers, they may have fucked up the code.

On going results here:
https://us.battle.net/d3/en/forum/topic/20742824077

**Comment by d07RiV** [comment]
Aren't Depth Diggers only supposed to affect resource generators? Or did they change it to all signatures now?

**Comment by dominiklohmann** [comment]
They changed it to all primaries that actually generate resource. This affects the rune Spined Dart on Poison Dart and all Wizard primaries when either Shame of Delseres or Prodigy are used.

**Comment by d07RiV** [comment]
Yeah I know it works with those that generate resource, forgot there's a PD rune for that.

**Comment by MCPtz** [comment]
Depth Diggers and SS do not affect fetish dart damage with Carnevil:
https://us.battle.net/d3/en/forum/topic/20742924198

Depth Diggers and SS do correctly increase the damage of the WD's own dart multiplicatively.

**Comment by d07RiV** [comment]
I'm guessing its a bug that will be fixed at some point =|

**Comment by dominiklohmann** [comment]
There is another PTR patch to be datamined.

**Comment by d07RiV** [comment]
Downloading it now, thanks.

**Comment by d07RiV** [comment]
Updated, will add the changes to the planner in a minute.

**Comment by dominiklohmann** [comment]
According to the patch notes, the damage buff given by Akarat's Champion is now multiplicative.

**Comment by d07RiV** [comment]
Does anyone know, what's going on with Kanai's Skorn? I see people saying it was nerfed/removed because people used it for leveling, but what was its purpose anyway? It seems to have the exact same model as a regular Skorn, which is still available >.>

**Comment by Manson1716** [comment]
FYI: the Wave of Destruction from Chantodo's Will uses whatever element you have stacked the highest on your gear.  At the moment, the simulator doesn't seem to be aware of this.   I have 20% fire damage on my bracers and no other fire damage in my build and the simulator dps comes out terribly low.  If I change static discharge to flame ward the damage comes out closer to what I would expect.

**Comment by tw33dl3dee** [comment]
Did they change it in 2.4.1? In 2.4, it's using the element from the Archon rune.

Afaik Kanai's Scorn was only there in April (same as Kanai's cow quest), conveniently removed before the season start ;)

**Comment by d07RiV** [comment]
But its still April? What season start? oO

From what I can tell, it was only added in 2.4.1 PTR and initially had no model, which was added in one of the more recent updates. I currently added it as a transmog option (orange Skorn recolor).

I'll wait for confirmation on Chantodo's element. Highest element actually makes more sense since its an item proc, but everything is possible.

**Comment by dominiklohmann** [comment]
It's actually a bit more complicated. I'll explain this on the example of the Firebird's + Archon + Chantodo's build, and why they use 20% Fire Damage and 19% Arcane Damage increase on gear.

Chantodo's damage type is determined by your highest +% elemental damage bonus. In the above case, this is Fire, which we need because Chantodo's Wave of Force also stacks Firebird's for whatever reason. 
However, the actual damage of the Wave of Force increased by the element of the Archon rune used, which is why players also want 19% Arcane Damage on their gear, since Chantodo's still makes up for the most damage you deal.

I don't know why it works this way, but it has worked the same on 2.4 and you can see this exact stat distribution on the PTR leaderboards as well for this exact reason.

**Comment by d07RiV** [comment]
Oh that's curious, do you know if the damage bonuses from different elements stack multiplicatively, then?

**Comment by dominiklohmann** [comment]
They don't stack at all, Chantodo's damage is not increased by fire damage at all in that scenario.

**Comment by d07RiV** [comment]
Oh, so its only there to stack firebirds?

**Comment by dominiklohmann** [comment]
Yes, you get the 20% fire damage only so it deals fire damage to proc Firebird's.

The 20% fire damage increase the damage of your Firebird's DoT.
The 19% arcane damage increase the damage of your Chantodo's and your Archon attacks.

You will probably have to make some weird special case in your code to get this to work properly.

**Comment by Manson1716** [comment]
Bliz has some whacked mechanics but this one takes the cake... I just want to see if I have this straight:

Firebird's DoT does fire damage so of course it's buffed by the 20% fire...
Your Archon skills deal arcane damage so of course they're buffed by the 19% arcane...

The blasts from Chantodo's do fire damage but are buffed by the 19% arcane??  

So do the Chantodo blasts double dip elemental damage? Because I would expect them to also gain the 20% fire damage since they're doing fire damage...

Bliz has such mad skills when it comes to complicating game mechanics...

**Comment by dominiklohmann** [comment]
No, it actually doesn't double dip. Fire damage being the highest only determines the damage type of the Chantodo's wave, but does not actually increase its damage, because Archon is arcane in this scenario.

**Comment by d07RiV** [comment]
So if you have CoE, which element will boost the damage of Chantodos in this situation?

**Comment by dominiklohmann** [comment]
> So if you have CoE, which element will boost the damage of Chantodos in this situation?

Fire

> How does Archon's own damage work? Just goes off your max element?

Goes off the selected rune. If you have all runes (Vyr's) it takes your highest element.

> How do Swami stacks interact with Archon stacks? Both are separate multipliers?

Additive with each other, so your current approach of making them both separate `dmgmul` values will not work.

**Comment by d07RiV** [comment]
Oh so Vyr's goes off the highest element, but Chantodo's ignores Vyr's.

So I need to fix the Swami stacking and we're good to go.

**Comment by d07RiV** [comment]
Fixed the elemental scaling, still haven't fixed the swami/archon interaction though.

**Comment by d07RiV** [comment]
Is twister no longer the best solo/group build? I ran a simple comparison of Blades vs Twister vs Orb, it seems that Orb is by far the highest damage, but has a lot less survivability due to lack of Infinite Depth, while Blades build is slightly higher DPS than orb, while only losing Esoteric for toughness, but it has more options such as stacking shields from Barrier Blades/Deflection (possibly with Ashnagarrs), or using Aquila (though its probably best to stick with APD). It also has no AP issues on single target.

http://ptr.d3planner.com/645246595

**Comment by dominiklohmann** [comment]
Twister turned out to be the best with Tal Rasha. The thing about Twisters is that you can get them stuck on corners so they hit all enemies with every single tick. This allows you to get massive benefit from your group.

**Comment by tw33dl3dee** [comment]
The canonical Orb version actually uses Orb in the weapon cube slot and Aquila in armor slot for more toughness. But now that monster damage has been reduced, you can probably trade that for more damage.

**Comment by d07RiV** [comment]
A bit unrelated, does anyone know if its possible to gamble Depth Diggers on a wizard? >.>

**Comment by dominiklohmann** [comment]
Should be, otherwise they'd be impossible to get with Intelligence (not rerolled), and I have a pair of those. That is of course assuming that they changed it equally for Wiz and WD when they allowed them to work with both.

**Comment by tw33dl3dee** [comment]
Yes it is, they changed it in 2.4 (when they introduced Shame of Delsere).

**Comment by d07RiV** [comment]
Oh well it turns out spectral blades build is pretty bad atm, barely finished GR62 lol (though I built way too defensively, didn't take any damage). After the patch it will be like 50% stronger, not quite enough.

**Comment by d07RiV** [comment]
> > How do Swami stacks interact with Archon stacks? Both are separate multipliers?
> Additive with each other, so your current approach of making them both separate dmgmul values will not work.

The damage gap between double and single stack seems very high in-game, and others seem to think so too: http://us.battle.net/d3/en/forum/topic/20743735397#1

I'll see if I can get some testing done myself.

**Comment by d07RiV** [comment]
Yep, can confirm that they are indeed multiplicative.

Using this gear: http://www.d3planner.com/939048028

I'm getting ~100K crits with Archon punch during double stacks on Ghom, but putting in 96 stacks shows the crit damage as 41K-62K.
