### ISSUE TITLE
Missing  Simulation  tab

### ISSUE THREAD

**Issue by jeremybtmn** [d07RiV/d3planner#479]
I've been away for a few seasons and have recently returned to d3 & d3 planner. I used the simulation functionality a ton in the past, has it been discontinued because I can't find it now?

**Comment by d07RiV** [comment]
Yes, simulations has been discontinued. It was designed back in the time when most of the focus was on single target damage, to kill rare elites or rift guardians quickly. Nowadays it's all about stacking up tons of mobs to make use of area damage, and stacking buffs to kill rift guardian  even faster, which is not covered well by simulations.

It hasn't been used much and is too much trouble to maintain.

**Comment by jeremybtmn** [comment]
Ahh, that's understandable. I assume enough of the code is available that I could branch and put it back in place for fun?

**Comment by d07RiV** [comment]
You could do that sure, but it hasn't been updated for a few patches now so it would take some work to get new item effects in.
