### ISSUE TITLE
Caldesann does not sync to character sheet

### ISSUE THREAD

**Issue by mrsmart83** [d07RiV/d3planner#48]
Whenever I'm importing a character, Caldesann's Despair does not get included, I've to add it manually.

**Comment by dominiklohmann** [comment]
The battle.net API does not give any information about Caldesann's Despair enchantments or Paragon point allocations, so this is something you will have to wait for Blizzard to fix for.

**Comment by d07RiV** [comment]
Yup that's not something I can do at this time unfortunately.

**Comment by tw33dl3dee** [comment]
How about just adding an option to add X level Caldesann to *all* ancient items? Paragon is auto-populated once it's over 800, but putting on all augments takes quite a lot of time.

**Comment by mrsmart83** [comment]
Yeah, I very like this idea. For now, I'm using 4 pieces of gear to add like 3500 paragon (3x1000+500). Until Blizz gives us a valid API, tihs could be used as a workaround.

**Comment by d07RiV** [comment]
I don't like adding a whole interface option just to cover a gap in the API.

You don't even need to add augments to your items - just add more stats in Paragon tab, its the exact same thing.

**Comment by mrsmart83** [comment]
True :) Thanks for the idea... I missed that somehow.
