### ISSUE TITLE
The sets without class requirements (Tal Rasha, Invoker, etc) can't be equipped by all classes

### ISSUE THREAD

**Issue by Eglin** [d07RiV/d3planner#485]
I can see how this might be a problem on the back-end, but some builds are running these items on alternate classes as stat sticks (TR chest for attack speed, Invoker for guaranteed thorn roll, etc) and d3planner does not currently seem to allow these configurations.  Not a huge deal, but would probably be nice to be able to properly configure builds.

**Comment by d07RiV** [comment]
You can already do it, just uncheck "Hide items for other classes" box. It seems I didn't disable set bonuses for other classes, but in most cases they don't do anything without appropriate skills anyway (shadow 2pc would be insane if it actually worked, though).
