### ISSUE TITLE
Relentless Assault passive is a separate multiplier?

### ISSUE THREAD

**Issue by mrsmart83** [d07RiV/d3planner#49]
I'm wondering why does RA makes separate +20% dmg but e.g. Unity included in "Damage increased by skills" section only? What's the difference? Does it make RA overpowered?

**Comment by d07RiV** [comment]
Unity is an additive damage bonus (it is added together with other similar effects, known as DIBS), while RA is multiplicative. Yes, multiplicative bonuses are more valuable.
