### ISSUE TITLE
Suggestion for skills & loadout area

### ISSUE THREAD

**Issue by aeclasik** [d07RiV/d3planner#50]
![photoshop_2016-03-17_23-35-59](https://cloud.githubusercontent.com/assets/17107146/13869354/5c4570f8-ec99-11e5-91a8-96c0773f8298.png)

**Comment by d07RiV** [comment]
There's no empty space on 1080 displays.

**Comment by emartinezgh** [comment]
I was just gonna suggest to show cubed items right below passives, since there's already space there. It somehow looked like that was the plan all along. Should work like shortcuts, just like skills and passive work, taking you to the correct tab/widget to change the selected cube power.

**Comment by d07RiV** [comment]
Yeah I need to photoshop the frames for it but I keep forgetting about it whenever I'm on a PC that has it installed :(

**Comment by emartinezgh** [comment]
![cube slot texture](https://cloud.githubusercontent.com/assets/2294593/15685501/9f680436-2731-11e6-9ec2-e75fe370b66f.png)

Best I could do, original texture size but without any kind of transparency. Tried to keep as much original detail as possible. Should resize easily to any size you need.

**Comment by d07RiV** [comment]
Oh no I have the originals, I need to make small square ones or something. I'll figure it out.

**Comment by d07RiV** [comment]
Done.

**Comment by d07RiV** [comment]
Also split the loadout and timeline boxes; loadout box can now be resized vertically.
