### ISSUE TITLE
Convention of Elements (physical) does not buff Thorns damage in the simulator

### ISSUE THREAD

**Issue by dominiklohmann** [d07RiV/d3planner#52]
That should be changed, because it actually does in the game. Should be a simple enough fix.

**Comment by d07RiV** [comment]
Okay assuming thorns (including hack) work off physical damage?

Fixed, also changed the way damage is attributed to casts, so you can see the damage of hacks and other procs in the 'sample' breakdowns now, but it might have some undesirable side effects. Perhaps I should think about making unit tests for the simulator >.>
