### ISSUE TITLE
Checkbox to indicate that affix is enchanted

### ISSUE THREAD

**Issue by tw33dl3dee** [d07RiV/d3planner#53]
This may sound like a strange idea, but would be nice to have a checkbox in item editor to indicate that this affix is enchanted. Currently, you can only import that info info from your character, but when you edit the affix, the enchanted symbol is gone, which makes it difficult to remember what you can reroll when you're optimizing your gear in planner. :)

**Comment by d07RiV** [comment]
I think it already has some logic that will remember the enchanted affix until you change the item in an "impossible" way - at least I remember trying to add that.

I thought about making imported items "locked" by default, which only allows modifying the enchanted stat (or one stat if the item was not enchanted initially), and an option to unlock the item to allow arbitrary editing. I guess its somewhere on the to-do list when I have more time.

**Comment by tw33dl3dee** [comment]
That's definitely a nice idea! Right now if you change the rerolled affix, it looses the enchanted icon.

**Comment by d07RiV** [comment]
Okay done, hope its not buggy as I kinda rushed it.
