### ISSUE TITLE
Sanguinary Vambraces

### ISSUE THREAD

**Issue by wow-config** [d07RiV/d3planner#54]
Source: http://us.battle.net/d3/en/blog/20057106/patch-241-ptr-patch-notes-3-15-2016
Text: Now benefit from all sources of bonus damage

Bugs: 
1:Does not benefit from CoE, i will check to find more that it does not yet benefit from
2: Blood Brother is a weapon that affects next hit not legendary effects however it currently affects the bracers

note: yo its me crowlock from reddit if u remember ^^ back to report again :)

**Comment by d07RiV** [comment]
Bloodbrother is 'intended'. In the skills tab it simply adds 30% damage to everything - I don't have the option to differentiate between skills and other effects very easily so I would have to add extra code just for one item. In the simulator it should correctly only affect the next used skill, though.

Yeah I haven't updated Sanguinary Vambraces yet, thanks for reminding.

**Comment by wow-config** [comment]
I am uncertain regarding how much main stat it benefits from tho as currently it benefits 25% while Hack benefits 100% on live & ptr.

**Comment by wow-config** [comment]
Now these bracers are the only thing left i can find unaffected by CoE :)

**Comment by d07RiV** [comment]
Does it still benefit from 25% of mainstat though?

**Comment by wow-config** [comment]
http://ptr.d3planner.com/888184029

Made a theorycraft ptr build with exactly 10.000 thorns, 900 strength and 40% physical% and thorn  common thorn items. Here is what it currently does or does not do :)

- Benefits 100% from strength
- Benefits from Vo'Toyias Spiker
- Does not benefit from physical%
- Does not Benefit the CoE ring

**Comment by d07RiV** [comment]
I mean in-game.

**Comment by d07RiV** [comment]
Ok so again, in-game, should it benefit from physical% and/or CoE?
