### ISSUE TITLE
Suggestion: Anicent & Max Option

### ISSUE THREAD

**Issue by wow-config** [d07RiV/d3planner#55]
option that while marked converst all non-ancient equipped items to Anicent
option that while marked sets all equipment stats to max.

Reason: most want to test their imported builds from D3, some might even have the perfect items but just not ancient or not maximized in stat due to bad rolls which is where this comes in to show the difference from now to best case scenario. I would suggest placing the options under.

**Comment by d07RiV** [comment]
Shouldn't be hard, guess I can add it eventually.

**Comment by d07RiV** [comment]
Done (0000e24bd1538c851969130b5e94ee94c236e658).
