### ISSUE TITLE
Punish

### ISSUE THREAD

**Issue by wow-config** [d07RiV/d3planner#57]
Unaffected by CoE & Laws of Valor

**Comment by d07RiV** [comment]
Works for me. Do you have issues with the Skills tab or the simulator? Can you link a profile that doesn't work?

**Comment by wow-config** [comment]
http://ptr.d3planner.com/999494588

The bug was not in the ability but rather the P6 Invoker set as the thorns added where not improved by the CoE.

**Comment by d07RiV** [comment]
Oh yeah it seems that physical damage % does not buff 6pc, but CoE does. I currently don't have code for that (its either both or neither) :(

**Comment by tw33dl3dee** [comment]
Ouch, that basically means all Invoker simulations are totally incorrect :(

The way CoE works should really be separate from elemental damage%, because it's a weird buff that's apparently applied to *any* damage dealt dynamically no matter how elemental% affects that damage.

**Comment by wow-config** [comment]
I think you can take the code almost directly from "Hack" aside from the damage is 800% instead of 100% they should function almost identically. Same goes for Sanguinary Vambraces i reported in another case which are also unaffected by the ring in the planner atm :)

**Comment by d07RiV** [comment]
Hack benefits from physical damage, though.
