### ISSUE TITLE
[Suggestion] Paragon

### ISSUE THREAD

**Issue by wow-config** [d07RiV/d3planner#58]
Could paragon level if set to be above 800 automatically max out  Offense, Strength & Utility stats ?

at 800+ they are all capped at 50 and the only remaining to put into is core :)

**Comment by d07RiV** [comment]
I think it already does that if you import a P800+ characer?

**Comment by wow-config** [comment]
Yes on import but not if you custom change it to 800+ :) like when you test builds ^^
