### ISSUE TITLE
Hammer of Ancients shows no damage in Simulator

### ISSUE THREAD

**Issue by Andy88488** [d07RiV/d3planner#59]
My Seasonal Barbarian, Thora (http://www.d3planner.com/729613282) is doing a lot of damage with her Hammer of Ancients. Unfortunately, when I use the Simulator to test my build, Hammer of Ancients shows up with zero damage.

**Comment by Andy88488** [comment]
Actually, Leap and Earthquake are also showing no damage.

**Comment by dominiklohmann** [comment]
You have set the distance in the simulator to 40 yards, which is with HotA doesn't hit anything.

For reference, here is a distance map for Diablo III: 
![d3_distance_map](https://cloud.githubusercontent.com/assets/4488655/13986744/65e11eea-f104-11e5-87a1-c2ee27bc336e.jpg)

**Comment by Andy88488** [comment]
Thank you! Somehow the simulator defaulted to that when I opened up the new profile.
