### ISSUE TITLE
Inna's Mantra gives you all Mystic Allies regardless of whether or not you have the rune on your bar

### ISSUE THREAD

**Issue by dominiklohmann** [d07RiV/d3planner#6]
This is currently not working in the simulation. The only thing you lose is the active effect.

Crudest Boots + Inna's Mantra also work without having Mystic Ally on your bar.

**Comment by d07RiV** [comment]
Oh whoops forgot about that case. Just to clarify, it doesn't spawn the unruned version?

**Comment by dominiklohmann** [comment]
No, only the runed versions. But even if you have the unruned version on your bar and you have the set bonus you won't get the unruned allies.
