### ISSUE TITLE
Blade of the Tribes passive

### ISSUE THREAD

**Issue by n1gus** [d07RiV/d3planner#64]
When using Threatening Shout or War Cry, Blade of the Tribes passive (with Earthen Might passive) become generate Fury.
Threatening Shout generate **75** (15(Threatening Shout) + 30(Earthquake) + 30(Avalanche))
Threatening Shout (with Animosity passive) **82**
War Cry **80**
War Cry(with Animosity passive) **88**

**Comment by d07RiV** [comment]
Oh, I think I broke it at some point. It should generate fury correctly on live, I think.

Just to confirm, avalanche/EQ should both (1) generate fury when triggered via Blade of the Tribes/earth set, and (2) count as a resource generator for F/R? That doesn't quite fit with my understanding of the game mechanics (I thought it would be either one or the other), but oh well.
