### ISSUE TITLE
Explosive Blast's rune Chain Reaction DPS is bugged in sim

### ISSUE THREAD

**Issue by plopinou** [d07RiV/d3planner#65]
I made some sims with the PTR version of the planner, and then checked in game to see how the known specs are behaving in reality.
The EB ones seemed to be godly dps wise with the 2.4.1 buffs, but while I was supposed to kill some elites in GR 70 in something like 7 to 8s with my gear, it often took at least the double, even when face tanking them 100% of the time.

So I did some number check in the sim, and quickly found out that the Chain Reaction rune is doing around 2 times more DPS than what it should.

You can check it out very simply with this test set : http://ptr.d3planner.com/914841999

with Short Fuse : 1,984,356 DPS on sheet, 1,962,403 in the sim
with Chain Reaction : 3,405,495 DPS on sheet, 6,093,591 in the sim

**Comment by d07RiV** [comment]
Oops I forgot to put in the 520% and used the base damage instead :F
