### ISSUE TITLE
Fists of Fury proc behaviour

### ISSUE THREAD

**Issue by dominiklohmann** [d07RiV/d3planner#7]
Fists of Fury seems broken in the simulation.
Here's how Fists of Fury works: 

- When you hit an enemy, you apply a DoT that ticks every 12 frames for a total of 179 frames on the target. Every DoT tick ticks with the same proc coefficient as the hit you applied the DoT with.
- Hitting a target again refreshes the DoT, but does not change the DoT proc coefficient. It also adds a stack to the DoT, but does not make the DoT tick more often for damage.
- The damage of the FoF DoT is `4% holy damage * FoF-stacks`, but this damage  is limited to `9 * Sheet APS * 4% holy damage` (this can be a fractional value). This damage cap is snapshotted when the DoT is first applied.

**Comment by d07RiV** [comment]
Oh thanks for the info I'll try to fix that, does the second hit add 7 stacks then?

**Comment by dominiklohmann** [comment]
Yes, it does.

**Comment by d07RiV** [comment]
Fixed with commit 3fa9ee196db0b26fe5034daf03dcf2d7cc0fc169

**Comment by d07RiV** [comment]
It seems to already have worked very similarly, except it only added one stack with the second hit, and had a cap on stacks instead of capping damage (which means the cap was always rounded).
