### ISSUE TITLE
earthquake and might of the earth bugging

### ISSUE THREAD

**Issue by Hartwall** [d07RiV/d3planner#70]
http://www.d3planner.com/202451163

http://ptr.d3planner.com/202451163

The damage of earthquake is not showing on the simulation, alone or with might of the earth set bonus. The set bonus is supposed to make Leap cast earthquake on each Leap, but it's not showing any damage. Same thing with blade of the tribes, it's only casting avalanche on both skills, but no earthquake.

**Comment by dominiklohmann** [comment]
Set the `Distance` setting in the simulator to a proper value. Earthquakes don't hit enemies 40 yards away from yourself.

Distance map for reference: http://www.diabloii.net/gallery/data/632/medium/D3_Distance_Map.jpg

**Comment by d07RiV** [comment]
Yep I should really make it more obvious somehow :(

**Comment by dominiklohmann** [comment]
Maybe display a warning when an ability is cast and hits no enemies at all?

**Comment by d07RiV** [comment]
Yeah I've been thinking of something like that, but there is no straightforward way to do that since abilities can deal damage with some delayed triggers and such. I think the easiest way would be to simply set a range for every ability and check them before even running the simulator.
