### ISSUE TITLE
Axe Hack analysis : PTR sim need some update

### ISSUE THREAD

**Issue by plopinou** [d07RiV/d3planner#71]
I did some Hack analysis on the PTR for fun, trying to make it work even with a wizard.
So I tested how it behaves exactly in game, and here are the results :
- Hack procs 100% of the time **only on the first target your ability hits**, whatever its proc coefficient. The sim currently considers that all the mobs hit procs it.
- For channeled skills, **only the first tick procs it**. All the following ticks will never proc it again as long as you continue your current channel. Also confirmed with barb's WW (too bad).
- For skills with multiple hits like Spectral Blade, **only the first hit triggers it**. The sim currently count 3 procs per Spectral Blade cast instead of 1.
- Pets never proc hack.
- Area damage doesn't proc from thorns, **but an area damage proc'ed on a mob nearby will 100% of the time procs hack on it. 1 AD proc = 1 hack proc.** _Update :_ reconfirmed it with some very precise testing using multiple accounts in the act 1 pvp zone.

This means that even though hack only triggers on the first target, if on average there's 5 mobs in range of AD  for each mob hit by an AE skill, you'll do as much damage as if hack was hitting every mob.
This also means that in very high density, this behavior is far superior. Large AE spells that ticks very fast are the thing to look for. A skill like Magic Weapon : Electicity combined with Spectral Blade doubles the AD procs, and so the Thorn DPS.

It's funny to see a dot ticking for 1k damage on 50 mobs, but chain triggering multiple millions thorns damage while in yellow gear :)

I don't know if this behavior with AD is only from the PTR or not.

**Update : ** I confirm that it's only on the PTR, but AD seems to also behave differently. Will check it out later.

_Fun fact :_
The combinaison of the channeled spell behavior + AD proc "proc" will result in you killing every targets except the one you're aiming at :D

**Comment by plopinou** [comment]
Some new additionnal info on the Area damage proccing Hack. This is a long post because this is a very specific in-game behavior (bug ?), so I need to develop to explain how I found it and why it's happening.

**Problematic :**
If the videos all showed without fail that 1 area damage number is always accompanied by a hack proc, something was bugging me : very dense AE wasn't doing the theorical DPS it were supposed to do.

### How I'm testing thing in general to validate the sim, _you can skip that part_.
I'm always validating the theory by practical tests, this is my way of having fun with the game. I theorycraft, then if I confirm something's working in game, I have fun playing the spec, even if under-geared.
One thing I'm specifically doing is finding the right params of the sim for a specific spec, that will make it somewhat "valid".
Example : If I have 50 mobs in a GR on the screen, and pull them all together to AE everything down, I record me killing them, then try to find the right spread/size combination with the same health to have the sim showing that everything's should be killed in the same amount of time it took in game.
Different spec are not behaving in game the same, that's why a spread of 30 and a size of 4 can be valid for one spec, but is completely wrong for another. This is normal, actual in-game skills are a lot more complex than just immobile AE with a diminishing factor depending on its natural radius and the spread used.
The perfect example for barbs being Dust Devil, which actually move in game, hitting way more mobs than just its default 9 yard radius would make you believe.

So, one of the thing I'm doing, is validation in a very dense AE situation that never happens in a GR, but is stable enough to reproduce in game to make validate the sim numbers.
The spot to do it is simply the Crypt of the Ancients in the Festering Woods. We can always pull around 80 mobs in it, and make them a very dense pack. If there's not enough, just recreate a game.

For a lot of specs, the numbers I found are very close to what the sim shows. For WW with DD, the sim show kill time much lower than what's in game, so we have to tweak the spread to fit it (generaly ~4 to 5 yard less).

## **Ok, so what's the problem ?**
Well, even if the hack procc'ed on AD is not in the sim yet, it's easy to anticipate what it's gonna do. We just have to run a sim without any AD, and then with 150% AD, and see the DPS increase.
Then we look the average AD damage of the main skill doing damage. I use the Slaughter rune of WotB with a IK spec without Skull Grasp. It does ~80% of all the damage.
We just have to replace the AD damage by the Hack damage. and see what should be the dps increase.

**And that is the problem, without hack the damage is what is supposed to be, but with hack, I'm finding a actual in-game DPS much lower than what the theory shows.**

I double/triple checked my math, everything's fine, so I took time to check in game with a very precise test setup :
- 3 accounts in the pvp zone of act 1
- 2 chars in AD range, with life regen
- 1 char doing the dps (a few thousand DPS at most), using Shi Mizu's Haori to have 100% crit on every skill, with the crit number hidden in the options. This allows me to see 100% of the AD procs, and only them, as long as the hack procs
- I then record everything, and count all the number in slow motion

## Here are my findings :
**AD total damage is as much as it theoretically should with 2 targets, but there's less seen procs that the theory.**
The explanation is simple, the more AD procs you get per second, the more the game can combine the multiple close AD procs (possibly in the same frame) in one bigger number shown.
- simply doing WW at 10 FPA without any rune show some combined damage, but not too much, and you get very close to the theoretical 2.4 AD proc per s (I saw ~2.2 to 2.3)
- simply hitting the 2 targets with the DD rune (no WW direct hit, I managed to do it), is also very close to the theoretical 1.6 AD proc per s (~1.4 to 1.5).
- WW+DD directly on top of the 2 targets show a much lower seen proc : 3.2 instead of 4 per s. But there's much more bigger number, because the AD procs were combined.
- Adding Slaughter on top is the same.

**So what of hack ?**
### **It never shows double a double/triple damage number.**
So it seems that Hack is not proc'ing once per AD theoretical proc, but per AD actual tick which can already be combined from multiple AD procs.
This means that if you use a lot of skills that hit very fast, you're not going to get the expected hack proc count you'd think. In the case of a WW spec with < 10 FPA with DD and slaughter procs everywhere, this is especially true.

That's all the info I found about the hack procs. I took quite some time, and I may post a topic on the official bug section forum about this.

**Comment by plopinou** [comment]
It's just been confirmed that it's a nasty bug that will be hotfixed.
I feel stupid having spent so much time on this :/
Issue can be closed, thanks to the guys who dared to read even half of those 2 last posts.

**Comment by d07RiV** [comment]
:(

**Comment by vaelrock** [comment]
I don't know, I'm gonna do a quick test on the PTR to see exactly how it behaves their and report back.

**Comment by d07RiV** [comment]
So basically the only difference is that it should proc exactly once per ability, even channeled spells?
