### ISSUE TITLE
PTR Patch 2.4.1 - v2.4.1.36510

### ISSUE THREAD

**Issue by dominiklohmann** [d07RiV/d3planner#73]
Official patch notes: http://us.battle.net/d3/en/blog/20057106/patch-241-ptr-patch-notes-4-5-2016

There seem to be a few under the hood changes (Shield Bash, Furious Charge, Tal Rasha 2pc mechanics), can you update the datamine?

**Comment by d07RiV** [comment]
Oh, I didn't realize there's a new build. Will do.

**Comment by d07RiV** [comment]
I'm having problems unpacking the new PTR build, hope its just a small bug in CascLib.

**Comment by dominiklohmann** [comment]
Depth Diggers and Simplicity's Strength now work with Carnevil again apparently. So far no other unlisted changes I've found.

Good luck with CascLib, never got that to work for me personally... :/

**Comment by d07RiV** [comment]
Ok done, I probably won't upload the diff between this and the previous PTR build as the changes are minimal: Swamp Land Waders now seem to roll any element, and Vyr's 4pc has been nerfed back to 1%.

**Comment by dominiklohmann** [comment]
They just uploaded another small patch, this time with changes heavily affecting the 4-player meta. Are there any changes that are not in the official changelog?

http://us.battle.net/d3/en/blog/20057106/patch-241-ptr-patch-notes-4-12-2016

**Comment by d07RiV** [comment]
No, I already ran the tool on it when it first appeared, there were no changes to items/sets/powers at all.
