### ISSUE TITLE
PE and Gem of Efficacious Toxin are conflicting in sim

### ISSUE THREAD

**Issue by vaelrock** [d07RiV/d3planner#75]
http://ptr.d3planner.com/886624079

If you sim the DPS on a single white mob you get 17.752 M DPS for GET and 52.571 M for PE while on the detailed skills/effects you see 17,948,189 DPS for GET (very close), but 64,100,676 DPS for PE (22% more).

If you simply remove the GET from the equipment and rerun the sim, you then get 56.015 M DPS for PE (increased), while you can see 57,546,330 DPS on the skills/effects tab (very close).

So there must be some kind of conflict between the two dots.
Except if there's some kind of in-game behavior I'm not aware of ?

**Comment by d07RiV** [comment]
Seems there was a bug that causes some buffs to skip ticks if they are refreshed when they are about to tick.
