### ISSUE TITLE
Simulator does not factor in all Movement Speed buffs correctly for Standoff

### ISSUE THREAD

**Issue by Lothrik** [d07RiV/d3planner#76]
Under group buffs, if I add "Haunt - Poisoned Spirit" as an active effect, my simulated DPS goes up from 68.711T to 71.931T. However, if I activate a Fleeting Shrine under group buffs, my simulated DPS does not change at all.

This is with zero movement speed from gear/paragon/skills, and a standard Furious Charge/Standoff skill rotation.

There also seems to be some sort of bug with Sprint in the simulator, no matter how I add it or what conditions I set it completely breaks the simulation: http://puu.sh/ogITc/e7598d2693.png http://puu.sh/ogIU9/b6405488c4.png

**Comment by Lothrik** [comment]
Adding Dimensional Channelling also breaks this rotation for some reason (simulator keeps spamming Boulder Toss because it thinks Bastions of Will - Restraint never activates): http://puu.sh/ogJ0V/13daeab7a9.png

**Comment by Lothrik** [comment]
Forgot to mention this is all under ptr.d3planner.com, not live (though I assume these bugs all exist there as well).

**Comment by d07RiV** [comment]
Actually, Fleeting Shrine currently just adds 6437 regen, in all modes. I must've forgotten to put in the right stats when making the list.

**Comment by d07RiV** [comment]
I've fixed Fleeting shrine, and Channeling pylon preventing Restraint from activating.

**Comment by Lothrik** [comment]
Profile where Sprint breaks the simulation: http://ptr.d3planner.com/177481618

**Comment by Lothrik** [comment]
Channeling Pylon still seems broken, Fleeting works now though.

**Comment by d07RiV** [comment]
I'm getting the Restraint buff when Channeling pylon is up. Maybe your cache didn't update yet. Does this profile http://www.d3planner.com/307348466 have 100% Restraint uptime for you?

**Comment by d07RiV** [comment]
Fixed sprint.
