### ISSUE TITLE
[Suggestion] Add Support for Old-Gen Consoles

### ISSUE THREAD

**Issue by KawariHenkan** [d07RiV/d3planner#78]
I apologize if this already exists, but I wanted to use this to help build my character on ps3. Is there a way to access the items and skills from that version (I believe they are closest to PC patch 2.0.6)? Even just adding a way to go back to previous versions would be helpful.

**Comment by d07RiV** [comment]
You mean they weren't updated since the early RoS patch? I don't have the data from that version, and re-doing them again would take too long I'm afraid.

**Comment by KawariHenkan** [comment]
Yeah, old-gen doesnt get the latest updates. Oh well, it doesn't hurt to ask. I'll just use the program to help estimate my DPS. Thanks for responding.
