### ISSUE TITLE
In-Geom for skills with a cooldown like Explosive blast

### ISSUE THREAD

**Issue by VitaKaninen** [d07RiV/d3planner#80]
The DPS numbers reflected for skills like Explosive Blast do not change when In-Geom is in the cube, and the "Show in Stats" box is checked.  When In-Geom is procced in the game, Explosive blast cooldown is reduced to the hero's attack speed, since it's cooldown is 6 seconds by default, and In-Geom reduces this by 10 seconds.

There are probably many other skills like this, but I don't know which ones they are.  It probably applies to all skills that have a cooldown, and do not work off of charges.

**Comment by d07RiV** [comment]
Oh good point; doesn't it have a 0.5 second cooldown by the way, like Teleport with Aether Walker does? I.e. what happens if your attack speed is above 2 seconds?

**Comment by dominiklohmann** [comment]
The cooldown is always 0.5 seconds, or effectively 0.5 seconds + latency.

**Comment by d07RiV** [comment]
Done, it seems that cooldown is only included in Explosive Blast DPS calculations.
