### ISSUE TITLE
Invoker 6p working with Area and Elemental

### ISSUE THREAD

**Issue by Kai-Jones** [d07RiV/d3planner#85]
I think that the simulation is taking into account area damage and elemental damage increase for the Invoker 6p bonus which doesn't work with either making the damage numbers that are coming out inflated and not what they should be. If I am wrong then my mistake but from the numbers coming out they seem inflated.

**Comment by d07RiV** [comment]
It was indeed benefiting from physical damage on gear, but as far as I can tell it is not affected by area damage. You can verify it here: http://www.d3planner.com/631938897 - change the number of targets, and observer that the DPS barely changes.
