### ISSUE TITLE
Blade of the Tribes and Lut Socks now procs procs

### ISSUE THREAD

**Issue by vaelrock** [d07RiV/d3planner#86]
The PTR has been hotfixed and a few items are now working as they were intended from the start : they are proccing procs like Area Damage or other things.

Amongst them are :
- Blade of the Tribes
- Lut Socks
- Belt of the Throve

More info here : http://us.battle.net/d3/en/forum/topic/20743254715

**Comment by d07RiV** [comment]
Ok so they now behave as if the skill was actually cast by the user?
