### ISSUE TITLE
Some images not available in item database

### ISSUE THREAD

**Issue by dominiklohmann** [d07RiV/d3planner#87]
http://ptr.d3planner.com/game/items

![gwh6ii6](https://cloud.githubusercontent.com/assets/4488655/14727926/49bab846-0830-11e6-8940-6e0845070777.png)

![gp3il8s](https://cloud.githubusercontent.com/assets/4488655/14727976/f3f4fd62-0830-11e6-8865-2e948c2bc87f.png)

**Comment by d07RiV** [comment]
Oh it was using the old icon database which I haven't updated in a while >.>
