### ISSUE TITLE
WhirlWind and Battle Rage should not trigger MotE 2P in sim

### ISSUE THREAD

**Issue by vaelrock** [d07RiV/d3planner#88]
Currently in the sim, Whirlwind and Battle Rage are both triggering the 2P set bonus of Might of the Earth, while it's not the case on live/PTR.
The Whirlwind issue is probably a bug from blizzard's side (but implementing it would be great), and the Battle Rage issue is not a bug and should be updated in the sim.
After all the 2P bonus reads "for every 30 Fury you spend with an attack", and Battle Rage is not an attack.

**Comment by d07RiV** [comment]
I'll probably leave Whirlwind as is, unless there is an actual build that uses WW with MOTE despite it being broken?

**Comment by vaelrock** [comment]
I actually tried to see if a "volcano" WW build could be better with MotE instead of LoN, and that's when I saw the bug.
Leaving WW like this is ok, the build isn't better anyway (too squishy).

Thanks !
