### ISSUE TITLE
Invigorating Gemstone

### ISSUE THREAD

**Issue by Scarloc** [d07RiV/d3planner#89]
Currently The Invigorating Gemstone shows 80% reduc at lvl 50. It should be 50% reduc, in fact it is 0.4% reduc per lvl + lvl 50 as max (same for patch 2.4.1)

![gemstone](https://cloud.githubusercontent.com/assets/18629185/14761058/4e75acc6-0955-11e6-83d9-ad30970ef1d5.JPG)

**Comment by d07RiV** [comment]
Ah, just to confirm, what other gems are currently capped?
I don't have level caps implemented atm since I figured people wouldn't put in higher levels anyway, but I might add them eventually.
