### ISSUE TITLE
Support Class / Frostburn

### ISSUE THREAD

**Issue by dubcat** [d07RiV/d3planner#90]
Would be great if you could remove the main stat restriction. Support classes are running around in Int and Str gear to get more AllRes/Armor.
Example: Select Int on Barbarian gear.

On PTR Frostburn has "% Cold DMG", the one on Char Planner does not.

**Comment by tw33dl3dee** [comment]
I guess you can just remove mainstat and add allres instead (should be virtually the same).

**Comment by dominiklohmann** [comment]
<img width="477" alt="screen shot 2016-04-23 at 16 34 07" src="https://cloud.githubusercontent.com/assets/4488655/14762046/7c3abb80-0971-11e6-82dc-b4b60cb4956c.png">

**Comment by dubcat** [comment]
Doh, stupid me. Thanks dominiklohmann :)

**Comment by d07RiV** [comment]
Cheers :)

**Comment by dominiklohmann** [comment]
Safari running on an iPad... it has checkbox alignment issues on more sites than just d3planner tho.
