### ISSUE TITLE
APS breakpoints table disappeared

### ISSUE THREAD

**Issue by tw33dl3dee** [d07RiV/d3planner#91]
The table with APS breakpoints, that was previously shown in tooltip if you hover "Frames per attack: N" on a skill is no longer there. This table was incredibly useful, could we get it back?

**Comment by d07RiV** [comment]
What skills doesn't it work for? I just checked whirlwind, the table is still there.

I think its only disabled for Explosive Blast atm, because otherwise the breakpoint would show up even without InGeom active and might be confusing.

**Comment by tw33dl3dee** [comment]
Apparently, it only disappeared for some pet skills (or maybe it wasn't there before but I presumed it was?). For example: http://www.d3planner.com/905629470 -> Summon Zombie Dogs.

**Comment by d07RiV** [comment]
For most WD pets, attack speed directly affects their damage, but does not make them hit faster. Their attack speed can only be increased with TnT.
