### ISSUE TITLE
Suggestion:  Enchant (Caldessan's Despair) button for all gear

### ISSUE THREAD

**Issue by Idyar** [d07RiV/d3planner#95]
Would be nice if you could just set all your gear to a certain enchant level for setting up theorycrafting comparisons.  Love the site and thanks!

**Comment by d07RiV** [comment]
I do need to add a few 'global' operations such as upgrading all items to ancient/max stats and adding enchants, but I don't have a good place to put them in atm.

Meanwhile, you can simply add more mainstat via paragons, it does the same thing as far as theorycrafting is concerned.

**Comment by Idyar** [comment]
Yeah good idea I will do that.  Thanks

**Comment by d07RiV** [comment]
Done (0000e24bd1538c851969130b5e94ee94c236e658).
