### ISSUE TITLE
Taeguk is still in the DIBS category

### ISSUE THREAD

**Issue by vaelrock** [d07RiV/d3planner#96]
Saw a guy talking about it on a twitch stream chat, and checked it quickly in game, but what I took for granted (like d3planner) is in fact wrong : Taeguk does not have a separate multiplier, it's sill in the DIBS category.
It's visible on the character sheet in game, but just in case I confirmed it in the Act I PvP zone too with a second account.

**Comment by dominiklohmann** [comment]
That's interesting, because the D3 devs actually said they intended to make it a multiplier. Never bothered to check in the game afterwards... Was somewhere in the PTR Feedback forums.

How do things like this keep happening?!

**Comment by vaelrock** [comment]
I recall to have read that having a separate multiplier was intended for Bane of the Powerful, but not for Taeguk. So I'm not 100% sure it is omission.

I opened an issue about it on the official forum anyway : http://us.battle.net/d3/en/forum/topic/20743654390
