### ISSUE TITLE
Flair of the ascended

### ISSUE THREAD

**Issue by opelit** [d07RiV/d3planner#97]
the bonus is benefit also from roland set :)

**Comment by opelit** [comment]
Edit: it also benefit from elemental damage of shield bash rune.

**Comment by dominiklohmann** [comment]
On PTR (first version) it always benefitted of holy damage.

**Comment by d07RiV** [comment]
Oh I guess the method I'm using isn't working >.>

**Comment by opelit** [comment]
%dominiklohmann it benefit from shield bash rune , i tested for phys and holy dmg and it always deal more dmg when CoE was on the Elemental damage of Shield bash.

**Comment by dominiklohmann** [comment]
Yeah was just confused because on the first version of PTR it benefitted from holy CoE... never tested it after because it's not competitive anyways, so whatever.... makes me wonder how many under the hood changes there were besides this.

**Comment by d07RiV** [comment]
I simply changed it to cast shield bash X times, but that isn't quite right because it should hit all the targets that were affected by shield glare, right?

**Comment by dominiklohmann** [comment]
Yeah, also if one of your previous shield bashes missed the enemies it won't deal 5x shield bash damage.

**Comment by d07RiV** [comment]
Huh wouldn't it just fail to give a stack? If you hit 5 bashes, then miss one, and shield glare, it will still hit 5x right?

**Comment by d07RiV** [comment]
Also, how does it interact with Drakon's Lesson?

**Comment by opelit** [comment]
great , can you also fix it in Skill/Effect tab? :)

**Comment by opelit** [comment]
> Also, how does it interact with Drakon's Lesson?

always proc.

**Comment by d07RiV** [comment]
Uh that's pretty weird, but then in the sim it will always be either *1 or *5 so its not too bad.
