### ISSUE TITLE
Can't Sim Archon build

### ISSUE THREAD

**Issue by iamleejn** [d07RiV/d3planner#99]
While trying to sim this [http://www.d3planner.com/173244029] I discovered that it would not sim. After changing skills, items, etc. I checked the source (F12) and found the following error:

Uncaught ReferenceError: buffs is not defined

I'm not entirely sure what the issue is, but this is a total block to the sim.

**Comment by d07RiV** [comment]
Fixed, might take some time for your cache to update. Alternatively, open the following two pages and press F5:

http://www.d3planner.com/sim
http://www.d3planner.com/sim/wizard
